/* Generated by scripts/a1_images/slice_sheets.py - do not edit by hand.
   Pictures for A1.1 words that had none, keyed by "chapter|headword".
   Loaded after data_a11_vocab.js; it only fills cards that still have no picture. */
window.A1_VOCAB_11_IMAGES = {};

(function applyA11Images(){
  if(!Array.isArray(window.A1_BOOK)) return;
  window.A1_BOOK.forEach(chapter=>{
    (chapter.vocab||[]).forEach(card=>{
      const src=window.A1_VOCAB_11_IMAGES[chapter.num+'|'+card.w];
      if(src&&!card.img) card.img=src;
    });
  });
})();
