/* Original A1.1 learning content aligned with the six Netzwerk neu A1.1 themes. */
(() => {
const V=(w,d,ex,ar)=>({w,d,ex,ar});
const RM=(cat,catAr,items)=>({cat,catAr,items:items.map(([de,ar])=>({de,ar}))});
const READ=(kind,title,text,ar,glossary,questions)=>({kind,title,text,ar,glossary,questions});
const GR=(t,tAr,body)=>({t,tAr,body});
const S=(de,ar)=>({de,ar});
const Q=(q,o,a,fb,fbAr)=>({q,o,a,fb,fbAr});

window.A1_BOOK = [
{
num:1, route:"a1/k1", title:"Guten Tag!", titleAr:"صباح الخير! التحية والتعارف الأول",
subtitle:"Grüßen · sich vorstellen · Zahlen 1-20 · Länder und Sprachen",
intro:"Du lernst, Menschen zu begrüßen und dich kurz vorzustellen. Du fragst nach Namen, Herkunft, Befinden, Telefonnummer und E-Mail-Adresse. Außerdem buchstabierst du Wörter und sprichst über Länder und Sprachen.",
introAr:"هتتعلم التحية والتعارف الأول: الاسم، البلد، اللغة، الحالة، رقم التليفون والإيميل، وكمان تهجئة الكلمات.",
badges:["Begrüßung","Vorstellung","Zahlen 1-20","Alphabet","Länder","Sprachen"],
goals:[S("Begrüßen und verabschieden","تلقي التحية وتودع"),S("Name, Herkunft und Sprache nennen","تقول اسمك وبلدك ولغتك"),S("Nach dem Befinden fragen","تسأل عن الحال وترد"),S("Telefonnummer und E-Mail-Adresse nennen","تقول رقم التليفون والإيميل"),S("Einfache W-Fragen bilden","تكوّن أسئلة بسيطة بأدوات استفهام")],
vocab:[
 V("Guten Tag","Formelle Begrüßung am Tag.","Guten Tag, ich bin Anna.","صباح الخير / نهارك سعيد"),
 V("Hallo","Informelle Begrüßung.","Hallo, wie heißt du?","أهلا / مرحبا"),
 V("Guten Morgen","Begrüßung am Morgen.","Guten Morgen, Frau Bauer.","صباح الخير"),
 V("Guten Abend","Begrüßung am Abend.","Guten Abend, Herr Ali.","مساء الخير"),
 V("Gute Nacht","Man sagt es vor dem Schlafen.","Gute Nacht und bis morgen.","تصبح على خير"),
 V("Auf Wiedersehen","Formelle Verabschiedung.","Auf Wiedersehen, Frau Klein.","إلى اللقاء"),
 V("Tschüss","Informelle Verabschiedung.","Tschüss, bis später!","باي / مع السلامة"),
 V("bis bald","Man sieht sich bald wieder.","Danke und bis bald!","أشوفك قريب"),
 V("willkommen","Gruß für einen Gast.","Herzlich willkommen in Berlin!","أهلا بك"),
 V("danke","Man sagt es für etwas Nettes.","Danke für die Hilfe.","شكرا"),
 V("bitte","Antwort auf danke; auch eine höfliche Bitte.","Bitte schön!","من فضلك / عفوا"),
 V("ja","Positive Antwort.","Ja, das stimmt.","نعم / أيوه"),
 V("nein","Negative Antwort.","Nein, danke.","لا"),
 V("heißen","Einen Namen haben.","Ich heiße Omar.","يُسمى / اسمي"),
 V("kommen aus","Die Herkunft nennen.","Ich komme aus Ägypten.","يأتي من / أصله من"),
 V("wohnen in","Den Wohnort nennen.","Ich wohne in Berlin.","يسكن في"),
 V("buchstabieren","Ein Wort mit einzelnen Buchstaben sagen.","Kannst du deinen Namen buchstabieren?","يتهجى"),
 V("Wie geht es dir?","Frage nach dem Befinden unter Freunden.","Hallo Sara, wie geht es dir?","عامل إيه؟"),
 V("Wie geht es Ihnen?","Formelle Frage nach dem Befinden.","Wie geht es Ihnen, Herr Müller?","حضرتك عامل إيه؟"),
 V("gut","Positive Antwort auf das Befinden.","Danke, mir geht es gut.","كويس / جيد"),
 V("sehr gut","Stärker als gut.","Mir geht es sehr gut.","كويس جدا"),
 V("nicht so gut","Keine gute Antwort auf das Befinden.","Heute geht es mir nicht so gut.","مش كويس قوي"),
 V("der Name, -n","So heißt eine Person.","Mein Name ist Karim.","الاسم"),
 V("der Vorname, -n","Der erste Name.","Mein Vorname ist Lena.","الاسم الأول"),
 V("der Nachname, -n","Der Familienname.","Mein Nachname ist Hassan.","اسم العائلة"),
 V("das Land, -er","Staat oder Herkunftsort.","Deutschland ist ein Land in Europa.","بلد"),
 V("Deutschland","Land in Europa.","Ich wohne in Deutschland.","ألمانيا"),
 V("Österreich","Land in Europa.","Wien ist in Österreich.","النمسا"),
 V("die Schweiz","Land in Europa.","Bern ist in der Schweiz.","سويسرا"),
 V("Ägypten","Land in Nordafrika.","Kairo ist in Ägypten.","مصر"),
 V("die Sprache, -n","Deutsch, Arabisch oder Englisch.","Welche Sprachen sprichst du?","لغة"),
 V("Deutsch","Die deutsche Sprache.","Ich lerne Deutsch.","الألمانية"),
 V("Arabisch","Die arabische Sprache.","Ich spreche Arabisch.","العربية"),
 V("Englisch","Die englische Sprache.","Sprichst du Englisch?","الإنجليزية"),
 V("sprechen","Eine Sprache benutzen; reden.","Ich spreche zwei Sprachen.","يتكلم"),
 V("lernen","Neues Wissen bekommen.","Ich lerne gern Deutsch.","يتعلم"),
 V("ein bisschen","Eine kleine Menge.","Ich spreche ein bisschen Deutsch.","شوية / قليلا"),
 V("die Telefonnummer, -n","Eine Nummer für das Telefon.","Meine Telefonnummer ist kurz.","رقم التليفون"),
 V("die E-Mail-Adresse, -n","Adresse für elektronische Post.","Wie ist deine E-Mail-Adresse?","الإيميل"),
 V("die Adresse, -n","Straße, Hausnummer und Ort.","Meine Adresse ist in Hamburg.","العنوان"),
 V("der Buchstabe, -n","Ein Zeichen im Alphabet.","A ist ein Buchstabe.","حرف"),
 V("das Alphabet","Alle Buchstaben einer Sprache.","Wir lernen das Alphabet.","الأبجدية"),
 V("wer","Frage nach einer Person.","Wer ist das?","مين"),
 V("was","Frage nach einer Sache.","Was ist das?","إيه / ماذا"),
 V("wie","Frage nach Art oder Name.","Wie heißt du?","إزاي / كيف"),
 V("wo","Frage nach dem Ort.","Wo wohnst du?","فين / أين"),
 V("woher","Frage nach der Herkunft.","Woher kommst du?","منين"),
 V("und","Verbindet Wörter oder Sätze.","Ich komme aus Kairo und wohne in Berlin.","و"),
 V("oder","Zeigt eine Alternative.","Tee oder Kaffee?","أو")
],
redemittel:[
 RM("Begrüßung und Abschied","التحية والوداع",[["Guten Morgen! Wie geht es Ihnen?","صباح الخير! حضرتك عامل إيه؟"],["Hallo! Wie geht's?","أهلا! عامل إيه؟"],["Danke, gut. Und dir?","شكرا، كويس. وأنت؟"],["Auf Wiedersehen. Bis bald!","إلى اللقاء. أشوفك قريب."]]),
 RM("Sich vorstellen","تقديم النفس",[["Ich heiße ...","اسمي ..."],["Ich komme aus ... und wohne in ...","أنا من ... وأسكن في ..."],["Ich spreche Arabisch und ein bisschen Deutsch.","أتكلم عربي وقليل ألماني."],["Meine Telefonnummer ist ...","رقم تليفوني هو ..."]]),
 RM("Nachfragen","السؤال للتوضيح",[["Wie bitte?","نعم؟ / ممكن تعيد؟"],["Kannst du das bitte buchstabieren?","ممكن تتهجى ده؟"],["Wie schreibt man das?","ده بيتكتب إزاي؟"]])
],
readings:[READ("Dialog","Im Deutschkurs",
 "Mona ist neu im Deutschkurs. Sie sitzt neben Leo. Leo sagt: Hallo, ich heiße Leo. Wie heißt du? Mona antwortet: Ich heiße Mona und komme aus Ägypten. Ich wohne jetzt in Hamburg. Leo fragt: Welche Sprachen sprichst du? Mona sagt: Arabisch, Englisch und ein bisschen Deutsch. In der Pause tauschen sie Telefonnummern aus.",
 "منى جديدة في كورس الألماني. تجلس بجانب ليو. ليو يعرّف نفسه ويسألها عن اسمها وبلدها واللغات التي تتكلمها. في الاستراحة يتبادلان أرقام التليفون.",
 [["neu","جديد"],["neben","بجانب"],["austauschen","يتبادل"]],
 [["Wo ist Mona neu?","Im Deutschkurs."],["Wo wohnt sie jetzt?","In Hamburg."],["Welche Sprachen spricht Mona?","Arabisch, Englisch und ein bisschen Deutsch."]])],
grammar:[
 GR("W-Fragen","أسئلة W",`<p>W-Fragen beginnen mit Fragewörtern: <b>wie, wo, woher, was, welche</b>. Das Verb steht auf Position 2.</p><div class="exbox"><b>Wie</b> heißt du? - Ich heiße Mona.<br><b>Woher</b> kommst du? - Ich komme aus Ägypten.<br><b>Welche</b> Sprachen sprichst du? - Arabisch und Deutsch.</div>`),
 GR("Verben und Personalpronomen","الأفعال والضمائر",`<p>Im Präsens bekommt das Verb eine Endung. Am Anfang lernst du die wichtigsten Formen.</p><div class="gt-wrap"><table class="gt"><tr><th>Pronomen</th><th>heißen</th><th>kommen</th><th>sprechen</th></tr><tr><td>ich</td><td>heiße</td><td>komme</td><td>spreche</td></tr><tr><td>du</td><td>heißt</td><td>kommst</td><td>sprichst</td></tr><tr><td>er/sie</td><td>heißt</td><td>kommt</td><td>spricht</td></tr></table></div>`),
 GR("Das deutsche Alphabet","الأبجدية الألمانية ونطقها",`<p>Das Alphabet hat 26 Buchstaben plus die Umlaute <b>Ä Ö Ü</b> und <b>ß</b>. So sprichst du die Buchstabennamen:</p><div class="gt-wrap"><table class="gt"><tr><th>Buchstabe</th><th>Name</th><th>نطق تقريبي</th></tr><tr><td>A a</td><td>a</td><td>آ</td></tr><tr><td>B b</td><td>be</td><td>به</td></tr><tr><td>C c</td><td>ce</td><td>تسيه</td></tr><tr><td>D d</td><td>de</td><td>ده</td></tr><tr><td>E e</td><td>e</td><td>إيه</td></tr><tr><td>F f</td><td>ef</td><td>إف</td></tr><tr><td>G g</td><td>ge</td><td>گيه</td></tr><tr><td>H h</td><td>ha</td><td>ها</td></tr><tr><td>I i</td><td>i</td><td>إي</td></tr><tr><td>J j</td><td>jot</td><td>يوت</td></tr><tr><td>K k</td><td>ka</td><td>كا</td></tr><tr><td>L l</td><td>el</td><td>إل</td></tr><tr><td>M m</td><td>em</td><td>إم</td></tr><tr><td>N n</td><td>en</td><td>إن</td></tr><tr><td>O o</td><td>o</td><td>أو</td></tr><tr><td>P p</td><td>pe</td><td>په</td></tr><tr><td>Q q</td><td>ku</td><td>كو</td></tr><tr><td>R r</td><td>er</td><td>إغ</td></tr><tr><td>S s</td><td>es</td><td>إس</td></tr><tr><td>T t</td><td>te</td><td>ته</td></tr><tr><td>U u</td><td>u</td><td>أوو</td></tr><tr><td>V v</td><td>vau</td><td>فاو</td></tr><tr><td>W w</td><td>we</td><td>ڤيه</td></tr><tr><td>X x</td><td>ix</td><td>إكس</td></tr><tr><td>Y y</td><td>ypsilon</td><td>إبسِلون</td></tr><tr><td>Z z</td><td>zett</td><td>تسِت</td></tr><tr><td>Ä ä</td><td>ä</td><td>إيه مفتوحة</td></tr><tr><td>Ö ö</td><td>ö</td><td>أوه (شفايف مدورة)</td></tr><tr><td>Ü ü</td><td>ü</td><td>أوي (شفايف مدورة)</td></tr><tr><td>ß</td><td>eszett</td><td>إس قوية (ss)</td></tr></table></div><p>Beim Buchstabieren sagst du jeden Buchstaben einzeln: <b>M-O-N-A</b>.</p>`),
 GR("Zahlen 0–20","الأرقام من 0 إلى 20 ونطقها",`<div class="gt-wrap"><table class="gt"><tr><th>Zahl</th><th>Deutsch</th><th>نطق تقريبي</th></tr><tr><td>0</td><td>null</td><td>نُل</td></tr><tr><td>1</td><td>eins</td><td>آينس</td></tr><tr><td>2</td><td>zwei</td><td>تسفاي</td></tr><tr><td>3</td><td>drei</td><td>دراي</td></tr><tr><td>4</td><td>vier</td><td>فير</td></tr><tr><td>5</td><td>fünf</td><td>فُنف</td></tr><tr><td>6</td><td>sechs</td><td>زِكس</td></tr><tr><td>7</td><td>sieben</td><td>زيبن</td></tr><tr><td>8</td><td>acht</td><td>أخت</td></tr><tr><td>9</td><td>neun</td><td>نوين</td></tr><tr><td>10</td><td>zehn</td><td>تسين</td></tr><tr><td>11</td><td>elf</td><td>إلف</td></tr><tr><td>12</td><td>zwölf</td><td>تسفولف</td></tr><tr><td>13</td><td>dreizehn</td><td>درايتسين</td></tr><tr><td>14</td><td>vierzehn</td><td>فيرتسين</td></tr><tr><td>15</td><td>fünfzehn</td><td>فُنفتسين</td></tr><tr><td>16</td><td>sechzehn</td><td>زِشتسين</td></tr><tr><td>17</td><td>siebzehn</td><td>زيبتسين</td></tr><tr><td>18</td><td>achtzehn</td><td>أختتسين</td></tr><tr><td>19</td><td>neunzehn</td><td>نوينتسين</td></tr><tr><td>20</td><td>zwanzig</td><td>تسفانتسيش</td></tr></table></div>`),
 GR("Aussprache: Buchstaben und Vokale","النطق: الحروف وحروف العلة",`<p>Übe die Buchstabennamen laut. Wichtig sind die langen Vokale:</p><div class="exbox"><b>a</b> wie in „Tag" · <b>e</b> wie in „gehen" · <b>i</b> wie in „wie" · <b>o</b> wie in „wohnen" · <b>u</b> wie in „du".</div><p>Stell dich vor und buchstabiere deinen Namen: „Ich heiße … – M wie Mona, O, N, A."</p>`)
],
speaking:{questions:[S("Stell dich vor: Name, Land, Wohnort und Sprachen.","قدم نفسك: الاسم، البلد، مكان السكن واللغات."),S("Buchstabiere deinen Namen.","اتهجى اسمك."),S("Frage eine Person nach der Telefonnummer.","اسأل شخصا عن رقم التليفون.")],
model:"Hallo, ich heiße Karim. Ich komme aus Ägypten und wohne in Kairo. Ich spreche Arabisch und Englisch. Ich lerne Deutsch. Meine Telefonnummer ist 0155 123456.",
modelAr:"أهلا، اسمي كريم. أنا من مصر وأسكن في القاهرة. أتكلم عربي وإنجليزي وأتعلم ألماني. رقم تليفوني هو ..."},
quiz:[Q("Ich ___ Mona.",["heiße","heißt","heißen"],0,"Mit ich: heiße.","مع ich نقول heiße."),Q("___ kommst du?",["Woher","Was","Welche"],0,"Woher fragt nach Herkunft.","Woher للسؤال عن الأصل."),Q("Er ___ Deutsch.",["spreche","spricht","sprichst"],1,"er/sie: spricht.","مع er/sie نقول spricht."),Q("Formell sagt man ...",["Tschüss","Auf Wiedersehen","Hallo du"],1,"Auf Wiedersehen ist formell.","دي صيغة رسمية للوداع."),Q("1-20 gehören zum Thema ...",["Zahlen","Berufe","Essen"],0,"Zahlen = أرقام.","Zahlen يعني أرقام."),Q("Welche Antwort passt? Wie geht es dir?",["Danke, gut.","Ich wohne in Hamburg.","M-O-N-A"],0,"Man antwortet mit dem Befinden.","السؤال عن الحال.")]}
,

{
num:2, route:"a1/k2", title:"Freunde, Kollegen und ich", titleAr:"الأصدقاء والزملاء وأنا",
subtitle:"Hobbys · Wochentage · Berufe · Zahlen ab 20",
intro:"Du sprichst über Hobbys, Arbeit, Beruf und Arbeitszeiten. Du verabredest dich, nennst Wochentage und Zahlen ab 20 und füllst einfache Formulare aus.",
introAr:"هتتكلم عن الهوايات والعمل والمهنة ومواعيد الشغل، وتتعلم الاتفاق على موعد وملء استمارة بسيطة.",
badges:["Hobbys","Wochentage","Berufe","Ja/Nein-Fragen","Artikel","haben/sein"],
goals:[S("über Hobbys sprechen","تتكلم عن الهوايات"),S("Sich verabreden","تتفق على مقابلة"),S("Beruf und Arbeitszeit nennen","تقول المهنة ومواعيد العمل"),S("Ja/Nein-Fragen verstehen","تفهم أسئلة نعم/لا"),S("Artikel der, das, die benutzen","تستخدم أدوات التعريف")],
vocab:[
 V("das Hobby, -s","Etwas, das man gern in der Freizeit macht.","Mein Hobby ist Fußball.","هواية"),
 V("die Freizeit","Die Zeit ohne Arbeit.","In der Freizeit treffe ich Freunde.","وقت الفراغ"),
 V("Fußball spielen","Als Hobby Fußball machen.","Wir spielen am Samstag Fußball.","يلعب كورة"),
 V("Musik hören","Musik mit Handy oder Radio hören.","Ich höre gern Musik.","يسمع موسيقى"),
 V("lesen","Bücher oder Texte verstehen.","Ich lese gern Romane.","يقرأ"),
 V("tanzen","Sich mit Musik bewegen.","Wir tanzen am Freitag.","يرقص"),
 V("schwimmen","Sich im Wasser bewegen.","Im Sommer schwimme ich gern.","يعوم"),
 V("joggen","Langsam laufen als Sport.","Ich jogge am Morgen.","يجري"),
 V("fotografieren","Fotos machen.","Sie fotografiert gern Menschen.","يصوّر"),
 V("malen","Mit Farben Bilder machen.","Kinder malen gern.","يرسم"),
 V("singen","Mit der Stimme Musik machen.","Er singt im Chor.","يغني"),
 V("spielen","Ein Spiel oder ein Instrument machen.","Ich spiele Gitarre.","يلعب / يعزف"),
 V("das Instrument, -e","Gitarre, Klavier oder Geige.","Ich lerne ein Instrument.","آلة موسيقية"),
 V("treffen","Mit jemandem zusammenkommen.","Ich treffe meine Freunde.","يقابل"),
 V("der Freund, -e","Eine männliche Person, die man mag.","Mein Freund heißt Max.","صاحب / صديق"),
 V("die Freundin, -nen","Eine weibliche Person, die man mag.","Meine Freundin heißt Lina.","صاحبة / صديقة"),
 V("zusammen","Mit anderen Personen.","Wir lernen zusammen.","مع بعض"),
 V("gern","Mit Freude.","Ich koche gern.","بحب (أعمل)"),
 V("sich verabreden","Einen Treffpunkt ausmachen.","Wir verabreden uns am Sonntag.","يتفق على مقابلة"),
 V("der Montag","Der erste Wochentag.","Am Montag arbeite ich.","الاثنين"),
 V("der Dienstag","Wochentag nach Montag.","Am Dienstag habe ich Kurs.","الثلاثاء"),
 V("der Mittwoch","Wochentag in der Mitte.","Am Mittwoch spiele ich.","الأربعاء"),
 V("der Donnerstag","Wochentag nach Mittwoch.","Am Donnerstag arbeite ich lange.","الخميس"),
 V("der Freitag","Wochentag vor Samstag.","Am Freitag treffe ich Freunde.","الجمعة"),
 V("der Samstag","Tag am Wochenende.","Am Samstag habe ich Zeit.","السبت"),
 V("der Sonntag","Tag am Wochenende.","Am Sonntag habe ich frei.","الأحد"),
 V("der Wochentag, -e","Ein Tag der Woche.","Montag ist ein Wochentag.","يوم في الأسبوع"),
 V("das Wochenende, -n","Samstag und Sonntag.","Am Wochenende habe ich Zeit.","نهاية الأسبوع"),
 V("heute","Dieser Tag.","Heute lerne ich Deutsch.","النهاردة"),
 V("der Beruf, -e","Die Arbeit einer Person.","Was bist du von Beruf?","مهنة"),
 V("arbeiten","Einen Beruf ausüben.","Ich arbeite im Hotel.","يشتغل"),
 V("die Arbeit","Was man im Beruf macht.","Die Arbeit beginnt um acht.","الشغل"),
 V("der Lehrer, -","Ein Mann, der unterrichtet.","Der Lehrer erklärt gut.","مدرّس"),
 V("die Lehrerin, -nen","Eine Frau, die unterrichtet.","Sie ist Deutschlehrerin.","مدرّسة"),
 V("der Ingenieur, -e","Technischer Beruf.","Mein Vater ist Ingenieur.","مهندس"),
 V("die Ingenieurin, -nen","Technischer Beruf für eine Frau.","Sie ist Ingenieurin.","مهندسة"),
 V("der Verkäufer, -","Mann, der im Geschäft verkauft.","Der Verkäufer ist freundlich.","بائع"),
 V("die Verkäuferin, -nen","Frau, die im Geschäft verkauft.","Die Verkäuferin hilft mir.","بائعة"),
 V("der Koch, -e","Person, die in einem Restaurant kocht.","Mein Bruder ist Koch.","طباخ"),
 V("frei haben","Nicht arbeiten müssen.","Am Sonntag habe ich frei.","عنده أجازة"),
 V("das Formular, -e","Ein Papier zum Ausfüllen.","Bitte füllen Sie das Formular aus.","استمارة"),
 V("ausfüllen","In ein Formular schreiben.","Ich fülle das Formular aus.","يملأ"),
 V("nett","Freundlich und sympathisch.","Omar ist sehr nett.","لطيف")
],
redemittel:[RM("über Hobbys","عن الهوايات",[["Was machst du gern?","بتحب تعمل إيه؟"],["Ich spiele gern Fußball.","أحب ألعب كرة."],["Ich koche nicht so gern.","مش بحب الطبخ قوي."],["Am Wochenende höre ich Musik.","في الويك إند أسمع موسيقى."]]),RM("Sich verabreden","الاتفاق على موعد",[["Hast du am Samstag Zeit?","عندك وقت يوم السبت؟"],["Gehen wir zusammen ins Kino?","نروح السينما مع بعض؟"],["Ja, gern. Wann?","نعم بكل سرور. إمتى؟"],["Leider habe ich keine Zeit.","للأسف معنديش وقت."]]),RM("Beruf und Arbeit","المهنة والعمل",[["Was sind Sie von Beruf?","حضرتك مهنتك إيه؟"],["Ich bin Ingenieurin.","أنا مهندسة."],["Ich arbeite von acht bis vier.","أعمل من 8 إلى 4."]])],
readings:[READ("Profil","Meine Woche",
 "Jonas arbeitet im Supermarkt. Er arbeitet von Montag bis Freitag, immer von acht bis sechzehn Uhr. Am Mittwoch spielt er nach der Arbeit Fußball. Am Freitag trifft er Freunde. Am Wochenende hat Jonas frei. Dann kocht er gern und hört Musik.",
 "يوناس يعمل في سوبر ماركت من الاثنين للجمعة من الثامنة للرابعة. يوم الأربعاء يلعب كرة بعد العمل، ويوم الجمعة يقابل أصدقاءه. في الويك إند عنده أجازة ويحب الطبخ وسماع الموسيقى.",
 [["immer","دائما"],["nach der Arbeit","بعد العمل"],["treffen","يقابل"]],
 [["Wo arbeitet Jonas?","Im Supermarkt."],["Wann spielt er Fußball?","Am Mittwoch."],["Was macht er am Wochenende?","Er kocht und hört Musik."]])],
grammar:[GR("Ja/Nein-Fragen","أسئلة نعم/لا",`<p>Bei Ja/Nein-Fragen steht das Verb auf Position 1.</p><div class="exbox"><b>Kommst</b> du am Samstag? - Ja, gern.<br><b>Arbeiten</b> Sie am Montag? - Nein, ich habe frei.</div>`),GR("Bestimmte Artikel und haben/sein","أدوات التعريف وفعلا haben/sein",`<div class="gt-wrap"><table class="gt"><tr><th>Artikel</th><th>Beispiel</th></tr><tr><td>der</td><td>der Beruf, der Montag</td></tr><tr><td>das</td><td>das Hobby, das Formular</td></tr><tr><td>die</td><td>die Lehrerin, die Woche</td></tr></table></div><p><b>haben</b>: ich habe, du hast, er hat. <b>sein</b>: ich bin, du bist, er ist.</p>`),GR("Zahlen ab 20","الأرقام من 20 وطريقة تكوينها",`<p>Ab 21 sagt man zuerst die <b>Einer</b>, dann <b>und</b>, dann die <b>Zehner</b>: <b>einundzwanzig</b> (1+20).</p><div class="gt-wrap"><table class="gt"><tr><th>Zahl</th><th>Deutsch</th><th>نطق تقريبي</th></tr><tr><td>20</td><td>zwanzig</td><td>تسفانتسيش</td></tr><tr><td>21</td><td>einundzwanzig</td><td>آين-اوُنت-تسفانتسيش</td></tr><tr><td>22</td><td>zweiundzwanzig</td><td>تسفاي-اوُنت-تسفانتسيش</td></tr><tr><td>30</td><td>dreißig</td><td>درايسيش</td></tr><tr><td>40</td><td>vierzig</td><td>فيرتسيش</td></tr><tr><td>50</td><td>fünfzig</td><td>فُنفتسيش</td></tr><tr><td>60</td><td>sechzig</td><td>زِشتسيش</td></tr><tr><td>70</td><td>siebzig</td><td>زيبتسيش</td></tr><tr><td>80</td><td>achtzig</td><td>أختتسيش</td></tr><tr><td>90</td><td>neunzig</td><td>نوينتسيش</td></tr><tr><td>100</td><td>(ein)hundert</td><td>هوُندِرت</td></tr></table></div>`),GR("Aussprache: Satzmelodie","النطق: نغمة الجملة (صعود/هبوط)",`<p>Die Stimme zeigt die Satzart:</p><div class="exbox">Aussage ↘: Ich komme aus Ägypten.<br>W-Frage ↘: Woher kommst du?<br>Ja/Nein-Frage ↗: Kommst du aus Kairo?</div><p>Bei Ja/Nein-Fragen geht die Stimme am Ende nach <b>oben</b>.</p>`)],
speaking:{questions:[S("Was machst du gern am Wochenende?","بتعمل إيه في الويك إند؟"),S("Was bist du von Beruf?","مهنتك إيه؟"),S("Verabrede dich mit einem Freund.","اتفق على موعد مع صديق.")],model:"Ich bin Ahmed. Ich arbeite im Restaurant. Am Wochenende habe ich frei. Ich spiele gern Fußball und treffe Freunde. Am Samstag gehe ich mit Omar ins Kino.",modelAr:"أنا أحمد. أعمل في مطعم. في الويك إند عندي أجازة. أحب لعب الكرة ومقابلة الأصدقاء. يوم السبت أذهب مع عمر إلى السينما."},
quiz:[Q("___ du am Samstag Zeit?",["Hast","Bist","Hat"],0,"du hast.","مع du نقول hast."),Q("Sie ___ Lehrerin.",["bin","ist","bist"],1,"sie ist.","هي = sie ist."),Q("___ Montag arbeite ich.",["Am","Im","Aus"],0,"Wochentage: am Montag.","مع أيام الأسبوع نستخدم am."),Q("Das ist ___ Formular.",["der","das","die"],1,"das Formular.","الأداة das."),Q("Verb auf Position 1 ist ...",["Ja/Nein-Frage","Aussage","Name"],0,"Kommst du?","السؤال نعم/لا يبدأ بالفعل."),Q("Leider habe ich keine Zeit bedeutet ...",["رفض مهذب","تحية","رقم"],0,"Das sagt man beim Absagen.","رفض/اعتذار مهذب.")]}
,

{
num:3, route:"a1/k3", title:"In Hamburg", titleAr:"في هامبورغ",
subtitle:"Plätze · Gebäude · Verkehrsmittel · Richtungen · Monate",
intro:"Du benennst Orte in der Stadt, fragst nach Dingen und Wegen und beschreibst einfache Wege. Du sprichst über Hobbys, Monate und Jahreszeiten.",
introAr:"هتتعلم أسماء الأماكن والمباني والمواصلات والاتجاهات، وتسأل عن الطريق وتوصفه ببساطة.",
badges:["Stadt","Wegbeschreibung","Verkehrsmittel","Monate","Imperativ Sie","Negation"],
goals:[S("Orte und Gebäude benennen","تسمي أماكن ومباني"),S("Nach dem Weg fragen","تسأل عن الطريق"),S("Einen Weg einfach beschreiben","توصف طريق بسيط"),S("Monate und Jahreszeiten nennen","تقول الشهور والفصول"),S("Mit kein und nicht verneinen","تنفي بـ kein و nicht")],
vocab:[
 V("die Stadt, -e","Großer Ort mit vielen Häusern.","Hamburg ist eine große Stadt.","مدينة"),
 V("das Dorf, -er","Kleiner Ort auf dem Land.","Mein Opa wohnt in einem Dorf.","قرية"),
 V("das Zentrum, Zentren","Die Mitte der Stadt.","Das Museum ist im Zentrum.","وسط البلد"),
 V("der Bahnhof, -e","Ort für Züge.","Der Bahnhof ist links.","محطة القطار"),
 V("der Flughafen, -","Ort für Flugzeuge.","Der Flughafen ist weit.","المطار"),
 V("der Markt, -e","Offener Ort zum Einkaufen.","Der Markt ist heute voll.","سوق"),
 V("das Museum, Museen","Gebäude mit Kunst oder Geschichte.","Wir gehen ins Museum.","متحف"),
 V("die Kirche, -n","Religiöses Gebäude.","Die Kirche ist alt.","كنيسة"),
 V("die Moschee, -n","Religiöses Gebäude für Muslime.","Die Moschee ist groß.","جامع / مسجد"),
 V("der Park, -s","Grüner Ort in der Stadt.","Ich gehe im Park spazieren.","حديقة"),
 V("der Platz, -e","Offener Ort in der Stadt.","Der Platz ist vor dem Rathaus.","ميدان"),
 V("das Rathaus, -er","Gebäude der Stadtverwaltung.","Das Rathaus ist schön.","مبنى البلدية"),
 V("das Kino, -s","Ort für Filme.","Das Kino ist am Markt.","سينما"),
 V("die Schule, -n","Ort zum Lernen für Kinder.","Die Schule ist groß.","مدرسة"),
 V("die Bibliothek, -en","Ort mit vielen Büchern.","In der Bibliothek ist es ruhig.","مكتبة"),
 V("die Straße, -n","Weg für Autos und Menschen.","Die Straße ist lang.","شارع"),
 V("die Brücke, -n","Sie geht über Wasser.","Die Brücke ist alt.","كوبري / جسر"),
 V("das Verkehrsmittel, -","Bus, Bahn, Auto oder Fahrrad.","Welches Verkehrsmittel nimmst du?","وسيلة مواصلات"),
 V("der Bus, -se","Verkehrsmittel in der Stadt.","Ich fahre mit dem Bus.","أتوبيس"),
 V("die U-Bahn, -en","Bahn unter der Erde.","Die U-Bahn ist schnell.","مترو"),
 V("die Straßenbahn, -en","Bahn auf der Straße.","Die Straßenbahn hält hier.","ترام"),
 V("das Fahrrad, -er","Man fährt mit zwei Rädern.","Ich fahre Fahrrad zur Schule.","عجلة"),
 V("das Auto, -s","Man fährt damit auf der Straße.","Mein Auto ist alt.","عربية"),
 V("das Taxi, -s","Auto, das man bezahlt.","Wir nehmen ein Taxi.","تاكسي"),
 V("fahren","Mit Bus, Bahn oder Auto unterwegs sein.","Ich fahre mit der U-Bahn.","يركب / يسوق"),
 V("gehen","Zu Fuß laufen.","Wir gehen zum Markt.","يمشي"),
 V("die Haltestelle, -n","Ort für Bus oder Bahn.","Die Haltestelle ist da vorne.","موقف"),
 V("nach dem Weg fragen","Fragen, wie man zu einem Ort kommt.","Ich frage nach dem Weg.","يسأل عن الطريق"),
 V("der Weg, -e","Die Route zu einem Ort.","Der Weg ist einfach.","طريق"),
 V("links","Auf der linken Seite.","Gehen Sie links.","شمال / يسار"),
 V("rechts","Auf der rechten Seite.","Biegen Sie rechts ab.","يمين"),
 V("geradeaus","Nicht links und nicht rechts.","Gehen Sie geradeaus.","على طول"),
 V("abbiegen","Die Richtung wechseln.","Biegen Sie an der Ampel ab.","يحوّد"),
 V("die Ampel, -n","Rotes und grünes Licht für den Verkehr.","Warte an der Ampel!","إشارة المرور"),
 V("die Ecke, -n","Wo zwei Straßen sich treffen.","Das Café ist an der Ecke.","ناصية / ركن"),
 V("weit","Nicht nah.","Der Bahnhof ist weit.","بعيد"),
 V("nah","Nicht weit.","Der Park ist nah.","قريب"),
 V("der Monat, -e","Januar, Februar, März usw.","Welcher Monat ist jetzt?","شهر"),
 V("der Januar","Der erste Monat.","Im Januar ist es kalt.","يناير"),
 V("der Juli","Ein Monat im Sommer.","Im Juli mache ich Urlaub.","يوليو"),
 V("die Jahreszeit, -en","Frühling, Sommer, Herbst, Winter.","Welche Jahreszeit magst du?","فصل من فصول السنة"),
 V("der Frühling","Die Jahreszeit nach dem Winter.","Im Frühling wird es warm.","الربيع"),
 V("der Sommer","Die warme Jahreszeit.","Im Sommer ist es heiß.","الصيف"),
 V("der Herbst","Die Jahreszeit mit Wind und Blättern.","Im Herbst regnet es oft.","الخريف"),
 V("der Winter","Die kalte Jahreszeit.","Im Winter schneit es.","الشتاء"),
 V("das Jahr, -e","Zwölf Monate.","Ein Jahr hat vier Jahreszeiten.","سنة")
],
redemittel:[RM("Nach Orten fragen","السؤال عن مكان",[["Entschuldigung, wo ist der Bahnhof?","عفوا، فين محطة القطار؟"],["Gibt es hier ein Museum?","هل يوجد هنا متحف؟"],["Ist der Markt weit?","هل السوق بعيد؟"]]),RM("Den Weg beschreiben","وصف الطريق",[["Gehen Sie geradeaus.","امش حضرتك على طول."],["Biegen Sie links ab.","ادخل شمال."],["Der Bahnhof ist rechts.","المحطة على اليمين."],["Nehmen Sie den Bus Nummer 5.","اركب الأتوبيس رقم 5."]]),RM("über Monate sprechen","عن الشهور",[["Im Januar ist es kalt.","في يناير الجو بارد."],["Im Sommer fahre ich gern weg.","في الصيف أحب السفر."]])],
readings:[READ("Stadtplan","Ein Tag in Hamburg",
 "Sara ist zum ersten Mal in Hamburg. Sie möchte zum Hafen und fragt eine Frau nach dem Weg. Die Frau sagt: Gehen Sie geradeaus bis zur U-Bahn. Fahren Sie zwei Stationen. Dann gehen Sie rechts. Der Hafen ist nicht weit. Sara macht Fotos und besucht am Nachmittag ein Museum.",
 "سارة في هامبورغ لأول مرة. تريد الذهاب إلى الميناء وتسأل سيدة عن الطريق. تركب المترو محطتين ثم تمشي يمين. بعد ذلك تزور متحفا.",
 [["zum ersten Mal","لأول مرة"],["der Hafen","الميناء"],["besuchen","يزور"]],
 [["Wohin möchte Sara?","Zum Hafen."],["Wie viele Stationen fährt sie?","Zwei Stationen."],["Was besucht sie am Nachmittag?","Ein Museum."]])],
grammar:[GR("Unbestimmter Artikel und Negation","أداة النكرة والنفي",`<div class="gt-wrap"><table class="gt"><tr><th>positiv</th><th>negativ</th></tr><tr><td>Das ist ein Park.</td><td>Das ist kein Park.</td></tr><tr><td>Hier ist eine Kirche.</td><td>Hier ist keine Kirche.</td></tr></table></div><p><b>nicht</b> negiert Verben oder Adjektive: Der Bahnhof ist <b>nicht</b> weit.</p>`),GR("Imperativ mit Sie","الأمر الرسمي مع Sie",`<p>Für höfliche Wegbeschreibungen benutzt man den Imperativ mit <b>Sie</b>.</p><div class="exbox">Gehen Sie geradeaus. Nehmen Sie den Bus. Biegen Sie rechts ab.</div>`),GR("Aussprache: lange und kurze Vokale","النطق: حروف العلة الطويلة والقصيرة",`<p>Ein Vokal ist meist <b>lang</b> vor <b>h</b> oder vor nur einem Konsonanten, und <b>kurz</b> vor zwei Konsonanten.</p><div class="gt-wrap"><table class="gt"><tr><th>lang (طويلة)</th><th>kurz (قصيرة)</th></tr><tr><td>wohnen, Bahn</td><td>kommen, Mann</td></tr><tr><td>Stuhl, gut</td><td>muss, Bus</td></tr><tr><td>Weg, Reise</td><td>Bett, Stadt</td></tr></table></div><p>Hör genau: <b>ah/oh/uh</b> klingen lang und ruhig.</p>`)],
speaking:{questions:[S("Beschreibe den Weg zum Bahnhof.","اوصف الطريق لمحطة القطار."),S("Welche Orte gibt es in deiner Stadt?","ما الأماكن الموجودة في مدينتك؟"),S("Welche Jahreszeit magst du?","أي فصل تحب؟")],model:"In meiner Stadt gibt es einen Bahnhof, viele Cafés und einen großen Park. Der Park ist nicht weit. Gehen Sie geradeaus und biegen Sie links ab. Im Sommer gehe ich gern in den Park.",modelAr:"في مدينتي توجد محطة قطار وكافيهات كثيرة وحديقة كبيرة. الحديقة ليست بعيدة. امش على طول وادخل شمال. في الصيف أحب الذهاب إلى الحديقة."},
quiz:[Q("Der Bahnhof ist nicht ___.",["weit","eine","kein"],0,"nicht + Adjektiv.","النفي مع الصفة بـ nicht."),Q("Das ist ___ Museum.",["ein","eine","einen"],0,"das Museum -> ein.","Museum محايد."),Q("Gehen Sie ___.",["geradeaus","Bahnhof","Monat"],0,"Das ist eine Richtung.","اتجاه."),Q("___ ist die Haltestelle?",["Wo","Wer","Wie alt"],0,"Wo fragt nach Ort.","Wo للمكان."),Q("Nehmen ___ den Bus.",["Sie","du","ich"],0,"Imperativ formell: Sie.","أمر رسمي."),Q("Januar ist ein ...",["Monat","Beruf","Hobby"],0,"Januar = Monat.","شهر.")]}
,

{
num:4, route:"a1/k4", title:"Guten Appetit!", titleAr:"بالهنا والشفا",
subtitle:"Mahlzeiten · Lebensmittel · Getränke · Geschäfte · Akkusativ",
intro:"Du planst einen Einkauf, führst einfache Gespräche beim Einkaufen und Essen und sprichst über Vorlieben. Du benutzt Akkusativ und die Verben mögen und möchten.",
introAr:"هتتعلم التخطيط للشراء والكلام في السوبر ماركت والمطعم، وتقول بتحب أو عايز إيه باستخدام Akkusativ و mögen/möchten.",
badges:["Essen","Einkaufen","Akkusativ","mögen","möchten","Position im Satz"],
goals:[S("Lebensmittel und Getränke nennen","تسمي أطعمة ومشروبات"),S("Einen Einkauf planen","تخطط للشراء"),S("Im Geschäft fragen und antworten","تتكلم في محل"),S("Vorlieben ausdrücken","تقول تفضيلاتك"),S("Akkusativ nach brauchen/möchten benutzen","تستخدم Akkusativ")],
vocab:[
 V("das Essen","Was man isst.","Das Essen ist fertig.","الأكل"),
 V("essen","Nahrung zu sich nehmen.","Ich esse einen Apfel.","يأكل"),
 V("trinken","Eine Flüssigkeit zu sich nehmen.","Ich trinke Wasser.","يشرب"),
 V("kochen","Essen warm machen.","Am Abend koche ich gern.","يطبخ"),
 V("das Frühstück","Die erste Mahlzeit am Tag.","Zum Frühstück esse ich Brot.","الفطار"),
 V("das Mittagessen","Essen am Mittag.","Das Mittagessen ist um eins.","الغداء"),
 V("das Abendessen","Essen am Abend.","Wir kochen Abendessen.","العشاء"),
 V("die Mahlzeit, -en","Frühstück, Mittag- oder Abendessen.","Drei Mahlzeiten am Tag.","وجبة"),
 V("das Lebensmittel, -","Essen aus dem Geschäft.","Wir kaufen Lebensmittel.","مواد غذائية"),
 V("das Brot, -e","Lebensmittel aus Mehl.","Ich kaufe ein Brot.","عيش / خبز"),
 V("das Brötchen, -","Kleines Brot.","Zum Frühstück esse ich ein Brötchen.","عيش صغير"),
 V("der Käse","Milchprodukt.","Ich mag Käse.","جبنة"),
 V("die Butter","Streicht man aufs Brot.","Butter und Marmelade, bitte.","زبدة"),
 V("das Ei, -er","Lebensmittel vom Huhn.","Ich esse ein Ei.","بيضة"),
 V("das Fleisch","Lebensmittel vom Tier.","Ich esse wenig Fleisch.","لحمة"),
 V("der Fisch, -e","Lebensmittel aus dem Wasser.","Der Fisch ist frisch.","سمك"),
 V("das Gemüse","Tomaten, Zwiebeln, Kartoffeln usw.","Gemüse ist gesund.","خضار"),
 V("die Tomate, -n","Rotes Gemüse.","Wir brauchen Tomaten.","طماطم"),
 V("die Kartoffel, -n","Gemüse aus der Erde.","Ich koche Kartoffeln.","بطاطس"),
 V("die Zwiebel, -n","Gemüse mit starkem Geschmack.","Ich schneide eine Zwiebel.","بصلة"),
 V("der Reis","Lebensmittel, oft als Beilage.","Heute essen wir Reis.","أرز"),
 V("die Nudeln","Lebensmittel aus Teig.","Kinder mögen Nudeln.","مكرونة"),
 V("das Obst","Äpfel, Bananen, Orangen usw.","Obst ist gesund.","فاكهة"),
 V("der Apfel, -","Rundes Obst.","Ich esse einen Apfel.","تفاحة"),
 V("die Banane, -n","Gelbes Obst.","Eine Banane, bitte.","موزة"),
 V("die Orange, -n","Obst mit viel Saft.","Ich esse eine Orange.","برتقالة"),
 V("das Wasser","Getränk ohne Geschmack.","Ich möchte Wasser.","مياه"),
 V("der Saft, -e","Getränk aus Obst.","Ich trinke Orangensaft.","عصير"),
 V("die Milch","Weißes Getränk von der Kuh.","Ich trinke Milch.","لبن"),
 V("der Kaffee","Heißes Getränk, oft am Morgen.","Morgens trinke ich Kaffee.","قهوة"),
 V("der Tee","Heißes Getränk mit Blättern.","Am Abend trinke ich Tee.","شاي"),
 V("die Suppe, -n","Warmes, flüssiges Essen.","Die Suppe ist heiß.","شوربة"),
 V("der Salat, -e","Kaltes Essen mit Gemüse.","Ich nehme einen Salat.","سلطة"),
 V("kaufen","Geld geben und etwas nehmen.","Ich kaufe Milch.","يشتري"),
 V("einkaufen","Mehrere Dinge im Geschäft kaufen.","Am Samstag kaufe ich ein.","يتسوّق"),
 V("brauchen","Etwas nötig haben.","Wir brauchen Reis.","يحتاج"),
 V("der Supermarkt, -e","Großes Geschäft für Lebensmittel.","Ich gehe in den Supermarkt.","سوبر ماركت"),
 V("die Bäckerei, -en","Geschäft für Brot.","Ich kaufe Brot in der Bäckerei.","مخبز"),
 V("das Geschäft, -e","Ein Ort zum Einkaufen.","Das Geschäft ist offen.","محل"),
 V("der Preis, -e","Wie viel etwas kostet.","Der Preis ist gut.","السعر"),
 V("kosten","Einen Preis haben.","Was kostet das?","يكلف / بكام"),
 V("das Kilo, -s","Tausend Gramm.","Ich nehme ein Kilo Äpfel.","كيلو"),
 V("die Flasche, -n","Behälter für Getränke.","Eine Flasche Wasser, bitte.","إزازة"),
 V("die Packung, -en","Eine verpackte Menge.","Eine Packung Reis.","علبة / باكو"),
 V("lecker","Schmeckt sehr gut.","Das Essen ist lecker.","لذيذ"),
 V("süß","Geschmack wie Zucker.","Der Kuchen ist süß.","حلو (طعم)"),
 V("salzig","Geschmack mit Salz.","Die Suppe ist salzig.","مالح"),
 V("frisch","Neu und gut, nicht alt.","Das Brot ist frisch.","طازة"),
 V("teuer","Kostet viel Geld.","Der Käse ist teuer.","غالي"),
 V("billig","Kostet wenig Geld.","Die Tomaten sind billig.","رخيص"),
 V("schmecken","Einen Geschmack haben.","Die Suppe schmeckt gut.","طعمه حلو")
],
redemittel:[RM("Einkaufen","الشراء",[["Was brauchen wir?","نحتاج إيه؟"],["Wir brauchen Brot, Milch und Tomaten.","نحتاج عيش ولبن وطماطم."],["Wie viel kostet das?","ده بكام؟"],["Ich nehme zwei Kilo Kartoffeln.","هاخد 2 كيلو بطاطس."]]),RM("Essen und Trinken","الأكل والشرب",[["Was möchtest du trinken?","تحب تشرب إيه؟"],["Ich möchte einen Kaffee.","أريد قهوة."],["Magst du Käse?","بتحب الجبنة؟"],["Nein, ich mag keinen Käse.","لا، لا أحب الجبنة."]]),RM("Im Restaurant","في المطعم",[["Die Speisekarte, bitte.","قائمة الطعام من فضلك."],["Ich möchte bezahlen.","أريد الحساب."],["Guten Appetit!","بالهنا والشفا!"]])],
readings:[READ("Einkaufsliste","Heute kochen wir",
 "Nina und Paul kochen am Abend. Sie schreiben eine Einkaufsliste: Reis, Tomaten, Käse, Brot und Wasser. Im Supermarkt fragt Paul: Brauchen wir auch Obst? Nina sagt: Ja, bitte zwei Äpfel. Zu Hause kochen sie Reis mit Gemüse. Danach trinken sie Tee.",
 "نينا وباول سيطبخان مساء. يكتبان قائمة مشتريات: أرز وطماطم وجبنة وعيش وماء. في السوبر ماركت يضيفان تفاحا. في البيت يطبخان أرزا بالخضار ثم يشربان شاي.",
 [["die Einkaufsliste","قائمة مشتريات"],["zu Hause","في البيت"],["danach","بعد ذلك"]],
 [["Was kaufen sie?","Reis, Tomaten, Käse, Brot, Wasser und Äpfel."],["Was kochen sie?","Reis mit Gemüse."],["Was trinken sie danach?","Tee."]])],
grammar:[GR("Akkusativ","المفعول به",`<p>Nach Verben wie <b>brauchen, kaufen, nehmen, möchten</b> steht oft Akkusativ. Nur maskulin ändert sich deutlich.</p><div class="gt-wrap"><table class="gt"><tr><th>Nominativ</th><th>Akkusativ</th></tr><tr><td>der Apfel</td><td>einen Apfel</td></tr><tr><td>das Brot</td><td>ein Brot</td></tr><tr><td>die Tomate</td><td>eine Tomate</td></tr></table></div>`),GR("mögen und möchten","يحب ويريد",`<div class="exbox">Ich <b>mag</b> Kaffee. = Ich finde Kaffee gut.<br>Ich <b>möchte</b> einen Kaffee. = Ich will jetzt einen Kaffee.</div><p>Mit Negation im Akkusativ: Ich mag <b>keinen</b> Käse.</p>`),GR("Aussprache: Umlaute ä, ö, ü","النطق: الحروف المعدّلة ä ö ü",`<p>Die Umlaute haben eigene Laute:</p><div class="gt-wrap"><table class="gt"><tr><th>Umlaut</th><th>Beispiel</th><th>نطق تقريبي</th></tr><tr><td>ä</td><td>Käse, Mädchen</td><td>بين A و E (إيه مفتوحة)</td></tr><tr><td>ö</td><td>schön, hören</td><td>قُل E والشفايف مدورة</td></tr><tr><td>ü</td><td>über, Tür, für</td><td>قُل I والشفايف مدورة</td></tr></table></div><p>Übe laut: <b>möchten</b>, <b>für</b>, <b>Getränke</b>.</p>`)],
speaking:{questions:[S("Was isst du zum Frühstück?","بتأكل إيه في الفطار؟"),S("Plane einen Einkauf für ein Abendessen.","خطط لمشتريات عشاء."),S("Bestelle etwas im Restaurant.","اطلب شيئا في مطعم.")],model:"Zum Frühstück esse ich Brot mit Käse und trinke Kaffee. Heute Abend koche ich Reis mit Tomaten. Ich brauche Reis, Tomaten und Wasser. Im Restaurant möchte ich eine Suppe und einen Tee.",modelAr:"في الفطار آكل عيش بالجبنة وأشرب قهوة. مساء اليوم أطبخ أرز بالطماطم. أحتاج أرزا وطماطم وماء. في المطعم أريد شوربة وشاي."},
quiz:[Q("Ich möchte ___ Kaffee.",["einen","ein","eine"],0,"der Kaffee -> einen Kaffee.","مذكر Akkusativ."),Q("Wir brauchen ___ Brot.",["ein","einen","eine"],0,"das Brot bleibt ein.","محايد."),Q("Ich mag ___ Käse.",["keinen","kein","keine"],0,"der Käse -> keinen.","مذكر في Akkusativ."),Q("Guten Appetit sagt man ...",["beim Essen","am Bahnhof","beim Buchstabieren"],0,"Beim Essen.","عند الأكل."),Q("Tomate ist ...",["Gemüse","Getränk","Beruf"],0,"Tomate = Gemüse.","خضار."),Q("Was möchtest du trinken?",["Wasser, bitte.","Ich heiße Max.","Am Montag."],0,"Passende Antwort.","إجابة مناسبة.")]}
,

{
num:5, route:"a1/k5", title:"Alltag und Familie", titleAr:"الحياة اليومية والعائلة",
subtitle:"Uhrzeit · Termine · Familie · Possessivartikel · Modalverben",
intro:"Du verstehst und nennst Uhrzeiten, machst Zeitangaben, sprichst über Familie und vereinbarst Termine telefonisch. Du entschuldigst dich für Verspätung und reagierst darauf.",
introAr:"هتتعلم الساعة والمواعيد والكلام عن العائلة، وتعمل اتفاق تليفوني وتعتذر عن التأخير.",
badges:["Uhrzeit","Familie","Termine","Possessivartikel","Modalverben","Telefon"],
goals:[S("Die Uhrzeit nennen","تقول الساعة"),S("über Tagesablauf sprechen","تتكلم عن الروتين اليومي"),S("Familienmitglieder vorstellen","تقدم أفراد العائلة"),S("Termine vereinbaren","تحدد مواعيد"),S("Modalverben müssen, können, wollen benutzen","تستخدم الأفعال الناقصة")],
vocab:[
 V("die Uhr, -en","Sie zeigt die Zeit.","Die Uhr hängt an der Wand.","الساعة (الأداة)"),
 V("die Uhrzeit, -en","Die Zeit auf der Uhr.","Wie ist die Uhrzeit?","الوقت / الساعة كام"),
 V("die Zeit","Minuten, Stunden, Tage.","Ich habe keine Zeit.","وقت"),
 V("die Stunde, -n","Sechzig Minuten.","Ich arbeite acht Stunden.","ساعة (مدة)"),
 V("die Minute, -n","Sechzig Sekunden.","Warte fünf Minuten.","دقيقة"),
 V("halb","Dreißig Minuten nach einer Stunde.","Es ist halb acht.","ونص"),
 V("das Viertel","Fünfzehn Minuten.","Viertel nach acht.","ربع"),
 V("um","Präposition für die genaue Uhrzeit.","Ich komme um acht Uhr.","الساعة (في تمام)"),
 V("früh","Vor der normalen Zeit.","Ich stehe früh auf.","بدري"),
 V("spät","Nach der richtigen Zeit.","Der Bus kommt spät.","متأخر"),
 V("pünktlich","Genau zur richtigen Zeit.","Ich bin immer pünktlich.","في الميعاد"),
 V("der Morgen","Zeit am Anfang des Tages.","Am Morgen trinke ich Kaffee.","الصبح"),
 V("der Vormittag","Zeit vor dem Mittag.","Am Vormittag arbeite ich.","قبل الضهر"),
 V("der Mittag","Zeit um zwölf Uhr.","Am Mittag mache ich Pause.","الضهر"),
 V("der Nachmittag","Zeit nach dem Mittag.","Am Nachmittag lerne ich.","بعد الضهر"),
 V("der Abend","Zeit am Ende des Tages.","Am Abend sehe ich fern.","بالليل / المسا"),
 V("die Nacht, -e","Die dunkle Zeit.","In der Nacht schlafe ich.","الليل"),
 V("der Tagesablauf, -e","Was man den ganzen Tag macht.","Mein Tagesablauf ist einfach.","الروتين اليومي"),
 V("aufstehen","Morgens aus dem Bett gehen.","Ich stehe um sieben auf.","يصحى / يقوم"),
 V("aufwachen","Wach werden.","Ich wache um sechs auf.","يستيقظ"),
 V("frühstücken","Frühstück essen.","Wir frühstücken um acht.","يفطر"),
 V("duschen","Den Körper mit Wasser waschen.","Ich dusche am Morgen.","يستحمى"),
 V("schlafen","Im Bett ruhen.","Ich schlafe acht Stunden.","ينام"),
 V("fernsehen","Filme im Fernseher ansehen.","Am Abend sehe ich fern.","يتفرج تلفزيون"),
 V("nach Hause kommen","Zur Wohnung zurückkommen.","Ich komme um sechs nach Hause.","يرجع البيت"),
 V("die Familie, -n","Eltern und Kinder zusammen.","Meine Familie ist groß.","العائلة"),
 V("der Vater, -","Der Papa.","Mein Vater arbeitet viel.","الأب / بابا"),
 V("die Mutter, -","Die Mama.","Meine Mutter heißt Salma.","الأم / ماما"),
 V("die Eltern","Vater und Mutter.","Meine Eltern wohnen in Kairo.","الوالدين"),
 V("der Bruder, -","Männliches Geschwister.","Mein Bruder studiert.","الأخ"),
 V("die Schwester, -n","Weibliches Geschwister.","Meine Schwester ist klein.","الأخت"),
 V("die Geschwister","Bruder und Schwester.","Hast du Geschwister?","إخوات"),
 V("der Sohn, -e","Männliches Kind.","Mein Sohn ist zehn.","الابن"),
 V("die Tochter, -","Weibliches Kind.","Meine Tochter lernt Deutsch.","البنت"),
 V("das Kind, -er","Junge Person.","Das Kind spielt.","طفل"),
 V("der Mann, -er","Erwachsene männliche Person; auch Ehemann.","Ihr Mann heißt Adam.","راجل / زوج"),
 V("die Frau, -en","Erwachsene weibliche Person; auch Ehefrau.","Seine Frau arbeitet.","ست / زوجة"),
 V("die Großeltern","Oma und Opa.","Meine Großeltern sind alt.","الأجداد"),
 V("der Opa, -s","Der Vater von Vater oder Mutter.","Mein Opa erzählt gern.","جدّو"),
 V("die Oma, -s","Die Mutter von Vater oder Mutter.","Meine Oma kocht gut.","تيتة"),
 V("der Termin, -e","Eine feste Zeit für etwas.","Ich habe einen Termin beim Arzt.","موعد"),
 V("vereinbaren","Einen Termin zusammen festlegen.","Wir vereinbaren einen Termin.","يتفق على موعد"),
 V("anrufen","Mit dem Telefon jemanden erreichen.","Ich rufe meine Mutter an.","يتصل"),
 V("telefonieren","Am Telefon sprechen.","Wir telefonieren am Abend.","يتكلم في التليفون"),
 V("sich verspäten","Zu spät kommen.","Entschuldigung, ich verspäte mich.","يتأخر"),
 V("warten","Bleiben, bis etwas passiert.","Ich warte auf den Bus.","يستنى"),
 V("absagen","Sagen, dass man nicht kommt.","Ich muss den Termin absagen.","يلغي")
],
redemittel:[RM("Uhrzeit und Alltag","الساعة والروتين",[["Wie spät ist es?","الساعة كام؟"],["Es ist halb acht.","الساعة سبعة ونصف."],["Ich stehe um sieben Uhr auf.","أستيقظ الساعة 7."],["Ich arbeite von neun bis fünf.","أعمل من 9 إلى 5."]]),RM("Familie","العائلة",[["Das ist mein Vater.","ده والدي."],["Meine Schwester wohnt in Alexandria.","أختي تسكن في الإسكندرية."],["Hast du Geschwister?","هل عندك إخوات؟"]]),RM("Am Telefon","على التليفون",[["Können wir einen Termin machen?","ممكن نحدد موعد؟"],["Ich kann leider nicht kommen.","للأسف لا أستطيع الحضور."],["Entschuldigung, ich verspäte mich.","آسف، سأتأخر."]])],
readings:[READ("Nachricht","Ich komme später",
 "Lena hat heute um 16 Uhr einen Termin beim Arzt. Um 15:30 Uhr schreibt sie eine Nachricht: Entschuldigung, ich verspäte mich. Der Bus kommt nicht. Ich bin um 16:15 Uhr da. Die Praxis antwortet: Kein Problem. Wir warten.",
 "لينا عندها موعد عند الطبيب الساعة 4. الساعة 3:30 تكتب رسالة تعتذر فيها أنها ستتأخر لأن الأتوبيس لم يأت. العيادة ترد: لا مشكلة، سننتظر.",
 [["die Praxis","عيادة"],["antworten","يرد"],["warten","ينتظر"]],
 [["Wann hat Lena einen Termin?","Um 16 Uhr."],["Warum verspätet sie sich?","Der Bus kommt nicht."],["Wann ist sie da?","Um 16:15 Uhr."]])],
grammar:[GR("Zeitangaben","تعبيرات الوقت",`<p>Für genaue Uhrzeiten benutzt man <b>um</b>. Für Tage benutzt man <b>am</b>. Für Zeiträume: <b>von ... bis</b>.</p><div class="exbox">um acht Uhr - am Montag - von neun bis fünf</div>`),GR("Possessivartikel und Modalverben","ضمائر الملكية والأفعال الناقصة",`<div class="gt-wrap"><table class="gt"><tr><th>ich</th><td>mein Vater, meine Mutter</td></tr><tr><th>du</th><td>dein Bruder, deine Schwester</td></tr><tr><th>er</th><td>sein Termin</td></tr><tr><th>sie</th><td>ihr Kind</td></tr></table></div><p>Modalverben: ich <b>muss</b>, ich <b>kann</b>, ich <b>will</b>. Das zweite Verb steht am Ende: Ich muss heute arbeiten.</p>`),GR("Aussprache: der r-Laut","النطق: حرف الـ r",`<p>Am Wortanfang oder vor einem Vokal spricht man <b>r</b> hinten im Hals (مثل غ خفيفة): <b>r</b>ot, <b>R</b>eis, hö<b>r</b>en.</p><p>Am Wortende klingt <b>-er</b> fast wie ein kurzes „a": Vat<b>er</b> ← „fata", Mutt<b>er</b>, imm<b>er</b>.</p>`)],
speaking:{questions:[S("Beschreibe deinen Tagesablauf.","اوصف يومك."),S("Stell deine Familie kurz vor.","قدم عائلتك باختصار."),S("Entschuldige dich für eine Verspätung.","اعتذر عن التأخير.")],model:"Ich stehe um sieben Uhr auf und frühstücke um halb acht. Von neun bis fünf arbeite ich. Meine Familie wohnt in Kairo. Mein Vater ist Lehrer und meine Mutter ist Ärztin. Heute kann ich leider nicht pünktlich kommen.",modelAr:"أستيقظ الساعة السابعة وأفطر السابعة والنصف. أعمل من التاسعة للخامسة. عائلتي تسكن في القاهرة. أبي مدرس وأمي طبيبة. اليوم للأسف لا أستطيع الحضور في الموعد."},
quiz:[Q("Ich komme ___ acht Uhr.",["um","am","von"],0,"Genaue Uhrzeit: um.","مع الساعة المحددة نستخدم um."),Q("___ Vater heißt Ali.",["Mein","Meine","Meinen"],0,"der Vater -> mein.","مذكر."),Q("___ Mutter arbeitet.",["Meine","Mein","Meinen"],0,"die Mutter -> meine.","مؤنث."),Q("Ich ___ heute arbeiten.",["muss","musst","müssen"],0,"ich muss.","مع ich نقول muss."),Q("von neun ___ fünf",["bis","um","am"],0,"von ... bis.","من ... إلى."),Q("Entschuldigung, ich verspäte mich bedeutet ...",["تأخير","طلب أكل","تحية"],0,"Verspätung.","اعتذار عن التأخير.")]}
,

{
num:6, route:"a1/k6", title:"Zeit mit Freunden", titleAr:"وقت مع الأصدقاء",
subtitle:"Freizeit · Datum · Geburtstag · Einladung · Restaurant · Ereignisse",
intro:"Du sprichst über Freizeit, Datum, Geburtstag und Einladungen. Du bestellst und bezahlst Essen und Getränke und sprichst über ein Ereignis.",
introAr:"هتتعلم الكلام عن وقت الفراغ والتاريخ وأعياد الميلاد والدعوات، والطلب والدفع في المطعم، والكلام عن حدث حصل.",
badges:["Freizeit","Datum","Einladung","Restaurant","trennbare Verben","Präteritum haben/sein"],
goals:[S("Das Datum nennen","تقول التاريخ"),S("Eine Einladung verstehen und schreiben","تفهم وتكتب دعوة"),S("Essen bestellen und bezahlen","تطلب أكل وتدفع"),S("über Freizeit und Veranstaltungen sprechen","تتكلم عن الفعاليات ووقت الفراغ"),S("über ein Ereignis mit war/hatte sprechen","تتكلم عن حدث بالماضي البسيط")],
vocab:[
 V("das Datum, Daten","Tag, Monat und Jahr.","Welches Datum ist heute?","التاريخ"),
 V("der Geburtstag, -e","Der Tag, an dem man geboren ist.","Mein Geburtstag ist im Mai.","عيد الميلاد"),
 V("die Ordinalzahl, -en","erste, zweite, dritte usw.","Erste ist eine Ordinalzahl.","رقم ترتيبي"),
 V("erste","Ordinalzahl eins.","Heute ist der erste April.","الأول"),
 V("zweite","Ordinalzahl zwei.","Am zweiten Mai habe ich Zeit.","الثاني"),
 V("dritte","Ordinalzahl drei.","Der dritte Tag ist frei.","الثالث"),
 V("die Einladung, -en","Ein Text: Komm bitte!","Danke für die Einladung.","دعوة"),
 V("einladen","Jemanden bitten zu kommen.","Ich lade dich ein.","يعزم / يدعو"),
 V("feiern","Eine Party machen.","Wir feiern am Samstag.","يحتفل"),
 V("die Feier, -n","Ein Fest.","Die Feier war schön.","حفلة"),
 V("die Party, -s","Ein Treffen mit Musik und Gästen.","Die Party beginnt um acht.","بارتي"),
 V("das Fest, -e","Ein großes Feiern.","Das Fest ist im Garten.","احتفال / عيد"),
 V("der Gast, -e","Eine eingeladene Person.","Die Gäste kommen um sieben.","ضيف"),
 V("das Geschenk, -e","Etwas für eine Person zum Fest.","Ich kaufe ein Geschenk.","هدية"),
 V("der Kuchen, -","Süßes Gebäck zum Fest.","Der Kuchen ist lecker.","كيكة / تورتة"),
 V("die Kerze, -n","Sie brennt auf dem Kuchen.","Auf dem Kuchen sind Kerzen.","شمعة"),
 V("gratulieren","Glückwünsche sagen.","Ich gratuliere dir!","يهنّي"),
 V("Alles Gute!","Glückwunsch zum Geburtstag.","Alles Gute zum Geburtstag!","كل سنة وانت طيب"),
 V("mitbringen","Etwas zur Party bringen.","Bring bitte Saft mit.","يجيب معاه"),
 V("beginnen","Anfangen.","Die Party beginnt um sechs.","يبدأ"),
 V("enden","Aufhören.","Das Fest endet um zehn.","يخلص"),
 V("das Restaurant, -s","Ein Ort, wo man essen kann.","Wir gehen ins Restaurant.","مطعم"),
 V("das Café, -s","Ort für Kaffee und Kuchen.","Wir sitzen im Café.","كافيه"),
 V("bestellen","Im Restaurant sagen, was man möchte.","Ich bestelle eine Suppe.","يطلب أكل"),
 V("die Speisekarte, -n","Die Liste mit Essen und Preisen.","Die Speisekarte, bitte.","المنيو"),
 V("die Bedienung","Die Person, die im Restaurant bringt.","Die Bedienung ist freundlich.","الجرسون / الخدمة"),
 V("bezahlen","Geld für etwas geben.","Wir möchten bezahlen.","يدفع"),
 V("die Rechnung, -en","Das Papier mit dem Preis.","Die Rechnung, bitte.","الحساب / الفاتورة"),
 V("das Trinkgeld","Extra-Geld für den Service.","Wir geben Trinkgeld.","بقشيش"),
 V("reservieren","Vorher einen Platz buchen.","Wir reservieren für acht Uhr.","يحجز"),
 V("zusammen bezahlen","Eine Rechnung für alle.","Wir bezahlen zusammen.","ندفع مع بعض"),
 V("getrennt bezahlen","Jeder zahlt allein.","Wir bezahlen getrennt.","كل واحد لوحده"),
 V("die Freizeitaktivität, -en","Was man in der Freizeit macht.","Kino ist eine Freizeitaktivität.","نشاط ترفيهي"),
 V("das Konzert, -e","Eine Musikveranstaltung.","Wir gehen ins Konzert.","حفلة موسيقية"),
 V("die Veranstaltung, -en","Ein Konzert, Fest oder Treffen.","Die Veranstaltung ist heute.","فعالية"),
 V("der Eintritt","Geld für den Zugang.","Der Eintritt kostet fünf Euro.","تذكرة الدخول"),
 V("gestern","Der Tag vor heute.","Gestern war die Party.","امبارح"),
 V("vorgestern","Der Tag vor gestern.","Vorgestern hatte ich frei.","أول امبارح"),
 V("letztes Jahr","Das Jahr vor diesem Jahr.","Letztes Jahr war ich in Berlin.","السنة اللي فاتت"),
 V("war","Vergangenheit von sein.","Die Party war schön.","كان"),
 V("hatte","Vergangenheit von haben.","Ich hatte viel Spaß.","كان عندي"),
 V("der Spaß","Freude und gute Laune.","Wir hatten viel Spaß.","متعة / تسلية"),
 V("schenken","Ein Geschenk geben.","Ich schenke ihr Blumen.","يهدي"),
 V("die Blume, -n","Eine Pflanze als Geschenk.","Ich bringe Blumen mit.","وردة / زهرة"),
 V("für","Präposition mit Akkusativ.","Das Geschenk ist für dich.","لـ / علشان")
],
redemittel:[RM("Einladen","الدعوة",[["Ich lade dich zu meinem Geburtstag ein.","أدعوك لعيد ميلادي."],["Die Party ist am Samstag um sieben.","الحفلة يوم السبت الساعة 7."],["Kannst du etwas mitbringen?","ممكن تحضر معك حاجة؟"],["Danke für die Einladung. Ich komme gern.","شكرا على الدعوة. سأحضر بكل سرور."]]),RM("Im Restaurant","في المطعم",[["Ich hätte gern eine Pizza.","أريد بيتزا من فضلك."],["Was möchten Sie trinken?","تحب تشرب إيه؟"],["Zusammen oder getrennt?","الحساب مع بعض ولا منفصل؟"],["Wir möchten bezahlen.","نريد الدفع."]]),RM("über ein Ereignis","عن حدث",[["Die Party war sehr schön.","الحفلة كانت جميلة جدا."],["Ich hatte viel Spaß.","استمتعت جدا."],["Das Essen war lecker.","الأكل كان لذيذ."]])],
readings:[READ("Einladung","Lucas hat Geburtstag",
 "Lucas hat am 12. Juni Geburtstag. Er schreibt eine Einladung an seine Freunde: Hallo zusammen, ich feiere am Samstag um 18 Uhr im Garten. Bitte bringt etwas zu trinken mit. Wir grillen und hören Musik. Am Abend schreibt Mia: Danke für die Einladung. Ich komme gern und bringe Saft mit.",
 "لوكاس عيد ميلاده يوم 12 يونيو. يكتب دعوة لأصدقائه: سيحتفل السبت الساعة 6 في الحديقة، ويطلب منهم إحضار مشروبات. ميا ترد أنها ستحضر ومعها عصير.",
 [["feiern","يحتفل"],["grillen","يشوي"],["Saft","عصير"]],
 [["Wann hat Lucas Geburtstag?","Am 12. Juni."],["Wo feiert er?","Im Garten."],["Was bringt Mia mit?","Saft."]])],
grammar:[GR("Datumsangaben und für + Akkusativ","التاريخ و für",`<p>Beim Datum benutzt man Ordinalzahlen: <b>am ersten Mai, am zweiten Juni, am dritten Juli</b>.</p><p><b>für</b> steht mit Akkusativ: ein Geschenk <b>für meinen</b> Freund, Blumen <b>für meine</b> Mutter.</p>`),GR("Trennbare Verben und Präteritum von haben/sein","الأفعال المنفصلة وماضي haben/sein",`<p>Bei trennbaren Verben steht das Präfix im Hauptsatz am Ende.</p><div class="exbox">Ich lade dich ein. Bring bitte Saft mit.</div><p>Präteritum: ich <b>war</b>, du <b>warst</b>, er <b>war</b>; ich <b>hatte</b>, du <b>hattest</b>, er <b>hatte</b>.</p>`),GR("Aussprache: ei, eu, äu","النطق: ei و eu و äu",`<div class="gt-wrap"><table class="gt"><tr><th>Schreibweise</th><th>Laut</th><th>Beispiel</th></tr><tr><td>ei</td><td>آي</td><td>mein, eins, Wein</td></tr><tr><td>eu</td><td>أوي</td><td>neu, Freund, heute</td></tr><tr><td>äu</td><td>أوي</td><td>Häuser, Verkäufer</td></tr></table></div><p><b>eu</b> und <b>äu</b> klingen gleich: „أوي".</p>`)],
speaking:{questions:[S("Wann hast du Geburtstag?","عيد ميلادك إمتى؟"),S("Schreib eine kurze Einladung.","اكتب دعوة قصيرة."),S("Erzähl von einer Party oder einem Restaurantbesuch.","احكِ عن حفلة أو زيارة مطعم.")],model:"Mein Geburtstag ist am zehnten Oktober. Ich lade meine Freunde am Samstag ein. Die Party beginnt um sieben Uhr. Bitte bringt etwas zu trinken mit. Letztes Jahr war die Party sehr schön und ich hatte viel Spaß.",modelAr:"عيد ميلادي يوم 10 أكتوبر. أدعو أصدقائي يوم السبت. الحفلة تبدأ الساعة 7. من فضلكم أحضروا شيئا للشرب. السنة الماضية كانت الحفلة جميلة جدا واستمتعت كثيرا."},
quiz:[Q("Mein Geburtstag ist ___ dritten Mai.",["am","um","im"],0,"Datum: am dritten Mai.","مع التاريخ نستخدم am."),Q("Ich lade dich ___.",["ein","mit","auf"],0,"einladen ist trennbar.","الفعل einladen منفصل."),Q("Bring bitte Saft ___.",["mit","ein","aus"],0,"mitbringen.","يحضر معه."),Q("Die Party ___ schön.",["war","hatte","ist haben"],0,"Präteritum von sein: war.","ماضي sein هو war."),Q("Ich ___ viel Spaß.",["hatte","war","hat"],0,"Präteritum von haben: hatte.","ماضي haben هو hatte."),Q("für meinen Freund ist ...",["Akkusativ","Nominativ","Plural immer"],0,"für + Akkusativ.","für يأخذ Akkusativ.")]}
];


const A1_AI_IMAGE_CHAPTERS = new Set([1, 2, 3, 4, 5, 6]);
const A1_TOPIC_TITLES = {
  1:["Begrüßung","Vorstellung","Länder und Sprachen","Alphabet und W-Fragen"],
  2:["Hobbys","Verabreden","Berufe","Fragen und Artikel"],
  3:["Stadt und Gebäude","Verkehrsmittel","Wegbeschreibung","Monate und Jahreszeiten"],
  4:["Essen und Getränke","Einkaufen","Im Geschäft","Vorlieben und Akkusativ"],
  5:["Uhrzeit und Tagesablauf","Familie","Termine und Telefon","Modalverben"],
  6:["Datum und Geburtstag","Einladung und Party","Restaurant","Veranstaltungen und Vergangenheit"]
};
window.A1_BOOK.forEach(chapter => {
  chapter.visual = {
    src:`assets/a1/chapters/chapter-${chapter.num}.webp`,
    alt:`A1 Kapitel ${chapter.num}: ${chapter.title}`,
    caption:`A1 Kapitel ${chapter.num}: ${chapter.title}`,
    captionAr:chapter.titleAr
  };
  chapter.vocab.forEach((card, index) => {
    card.img = A1_AI_IMAGE_CHAPTERS.has(chapter.num)
      ? `assets/a1/vocab_ai/k${chapter.num}/${String(index + 1).padStart(2, "0")}.webp`
      : "";
  });
  chapter.topicVisuals = (A1_TOPIC_TITLES[chapter.num] || []).map((title, index) => ({
    title,
    src:`assets/a1/topics/k${chapter.num}/${String(index + 1).padStart(2, "0")}.webp`,
    alt:`A1 Kapitel ${chapter.num}: ${title}`
  }));
});
})();
