/* B1.1 verb reference: key verbs from Netzwerk neu B1.1 chapters 1-6 with
   3rd person present, Präteritum, Perfekt and typical government (Rektion). */
window.B1_VERBS = [
  {chapter:1,inf:"sich erholen",praes:"erholt sich",praet:"erholte sich",aux:"haben",part:"sich erholt",rektion:"sich erholen von + D",ar:"يرتاح / يتعافى",example:"Im Urlaub habe ich mich gut von der Arbeit erholt."},
  {chapter:1,inf:"erfahren",praes:"erfährt",praet:"erfuhr",aux:"haben",part:"erfahren",rektion:"etwas erfahren über + A / von + D",ar:"يعرف / يعلم بـ",example:"Von meiner Schwester habe ich erfahren, dass sie umzieht."},
  {chapter:1,inf:"enthalten",praes:"enthält",praet:"enthielt",aux:"haben",part:"enthalten",rektion:"etwas enthalten",ar:"يحتوي على",example:"Der Preis enthält das Frühstück."},
  {chapter:1,inf:"tragen",praes:"trägt",praet:"trug",aux:"haben",part:"getragen",rektion:"etwas tragen",ar:"يحمل / يلبس",example:"Er hat den schweren Koffer zum Bahnhof getragen."},
  {chapter:1,inf:"brennen",praes:"brennt",praet:"brannte",aux:"haben",part:"gebrannt",rektion:"—",ar:"يحترق / يشتعل",example:"Am Strand hat die Sonne sehr gebrannt."},
  {chapter:1,inf:"schiefgehen",praes:"geht schief",praet:"ging schief",aux:"sein",part:"schiefgegangen",rektion:"—",ar:"يفشل / يمشي غلط",example:"Auf unserer Reise ist alles schiefgegangen."},
  {chapter:1,inf:"sich entschließen",praes:"entschließt sich",praet:"entschloss sich",aux:"haben",part:"sich entschlossen",rektion:"sich entschließen zu + D",ar:"يقرر",example:"Wir haben uns zu einer Reise nach Norwegen entschlossen."},
  {chapter:1,inf:"sich erkälten",praes:"erkältet sich",praet:"erkältete sich",aux:"haben",part:"sich erkältet",rektion:"—",ar:"يصاب بالبرد",example:"Beim Zelten habe ich mich erkältet."},
  {chapter:1,inf:"aufbauen",praes:"baut auf",praet:"baute auf",aux:"haben",part:"aufgebaut",rektion:"etwas aufbauen",ar:"يبني / ينصب",example:"Wir haben das Zelt am Fluss aufgebaut."},
  {chapter:1,inf:"liegen",praes:"liegt",praet:"lag",aux:"haben",part:"gelegen",rektion:"liegen an + D (Ursache)",ar:"يستلقي / يقع",example:"Den ganzen Tag habe ich am Strand gelegen."},
  {chapter:2,inf:"benötigen",praes:"benötigt",praet:"benötigte",aux:"haben",part:"benötigt",rektion:"etwas benötigen",ar:"يحتاج",example:"Für die Installation benötigt man ein Passwort."},
  {chapter:2,inf:"anschließen",praes:"schließt an",praet:"schloss an",aux:"haben",part:"angeschlossen",rektion:"etwas anschließen an + A",ar:"يوصّل",example:"Ich habe den Drucker an den Laptop angeschlossen."},
  {chapter:2,inf:"aufladen",praes:"lädt auf",praet:"lud auf",aux:"haben",part:"aufgeladen",rektion:"etwas aufladen",ar:"يشحن",example:"Hast du dein Handy schon aufgeladen?"},
  {chapter:2,inf:"herunterfallen",praes:"fällt herunter",praet:"fiel herunter",aux:"sein",part:"heruntergefallen",rektion:"—",ar:"يقع / يسقط",example:"Mein Handy ist heruntergefallen und jetzt ist das Display kaputt."},
  {chapter:2,inf:"kaputtgehen",praes:"geht kaputt",praet:"ging kaputt",aux:"sein",part:"kaputtgegangen",rektion:"—",ar:"يتعطل / ينكسر",example:"Die Kaffeemaschine ist nach einem Jahr kaputtgegangen."},
  {chapter:2,inf:"sich lohnen",praes:"lohnt sich",praet:"lohnte sich",aux:"haben",part:"sich gelohnt",rektion:"—",ar:"يستاهل / يستحق",example:"Die Reparatur hat sich gelohnt."},
  {chapter:2,inf:"streichen",praes:"streicht",praet:"strich",aux:"haben",part:"gestrichen",rektion:"etwas streichen",ar:"يدهن",example:"Am Wochenende haben wir die Küche gestrichen."},
  {chapter:2,inf:"anhaben",praes:"hat an",praet:"hatte an",aux:"haben",part:"angehabt",rektion:"etwas anhaben",ar:"يلبس (حاليًا)",example:"Was hattest du auf der Party an?"},
  {chapter:2,inf:"verraten",praes:"verrät",praet:"verriet",aux:"haben",part:"verraten",rektion:"jemandem etwas verraten",ar:"يكشف سرًا",example:"Kannst du mir verraten, wo du die Jacke gekauft hast?"},
  {chapter:2,inf:"reklamieren",praes:"reklamiert",praet:"reklamierte",aux:"haben",part:"reklamiert",rektion:"etwas reklamieren",ar:"يقدم شكوى على منتج",example:"Ich habe die kaputte Lampe im Geschäft reklamiert."},
  {chapter:2,inf:"geschehen",praes:"geschieht",praet:"geschah",aux:"sein",part:"geschehen",rektion:"—",ar:"يحدث",example:"Was ist hier geschehen?"},
  {chapter:2,inf:"entsprechen",praes:"entspricht",praet:"entsprach",aux:"haben",part:"entsprochen",rektion:"etwas (D) entsprechen",ar:"يطابق / يتوافق مع",example:"Das Gerät entspricht nicht der Beschreibung."},
  {chapter:2,inf:"vertrauen",praes:"vertraut",praet:"vertraute",aux:"haben",part:"vertraut",rektion:"jemandem (D) vertrauen",ar:"يثق في",example:"Ich vertraue den Bewertungen im Internet nicht immer."},
  {chapter:2,inf:"verbieten",praes:"verbietet",praet:"verbot",aux:"haben",part:"verboten",rektion:"jemandem etwas verbieten",ar:"يمنع / يحظر",example:"Meine Eltern haben mir das Handy beim Essen verboten."},
  {chapter:3,inf:"sich ernähren",praes:"ernährt sich",praet:"ernährte sich",aux:"haben",part:"sich ernährt",rektion:"sich ernähren von + D",ar:"يتغذى",example:"Seit einem Jahr ernähre ich mich vegan."},
  {chapter:3,inf:"erben",praes:"erbt",praet:"erbte",aux:"haben",part:"geerbt",rektion:"etwas von + D erben",ar:"يرث",example:"Sie hat das Haus von ihrer Großmutter geerbt."},
  {chapter:3,inf:"sich ereignen",praes:"ereignet sich",praet:"ereignete sich",aux:"haben",part:"sich ereignet",rektion:"—",ar:"يحدث / يقع",example:"Der Unfall hat sich am frühen Morgen ereignet."},
  {chapter:3,inf:"kämpfen",praes:"kämpft",praet:"kämpfte",aux:"haben",part:"gekämpft",rektion:"kämpfen für / gegen + A",ar:"يكافح",example:"Sie hat lange für ihre Rechte gekämpft."},
  {chapter:3,inf:"stürzen",praes:"stürzt",praet:"stürzte",aux:"sein",part:"gestürzt",rektion:"—",ar:"يقع بقوة",example:"Er ist mit dem Fahrrad gestürzt."},
  {chapter:3,inf:"sich begeistern",praes:"begeistert sich",praet:"begeisterte sich",aux:"haben",part:"sich begeistert",rektion:"sich begeistern für + A",ar:"يتحمس لـ",example:"Schon als Kind hat sie sich für Musik begeistert."},
  {chapter:3,inf:"sich verlieben",praes:"verliebt sich",praet:"verliebte sich",aux:"haben",part:"sich verliebt",rektion:"sich verlieben in + A",ar:"يقع في الحب",example:"Mein Opa hat sich im Urlaub in meine Oma verliebt."},
  {chapter:3,inf:"verschwinden",praes:"verschwindet",praet:"verschwand",aux:"sein",part:"verschwunden",rektion:"—",ar:"يختفي",example:"Plötzlich war meine Tasche verschwunden."},
  {chapter:3,inf:"aufgeben",praes:"gibt auf",praet:"gab auf",aux:"haben",part:"aufgegeben",rektion:"etwas aufgeben",ar:"يستسلم / يتخلى عن",example:"Er hat seinen Job aufgegeben und ist ausgewandert."},
  {chapter:3,inf:"wegziehen",praes:"zieht weg",praet:"zog weg",aux:"sein",part:"weggezogen",rektion:"wegziehen aus + D",ar:"ينتقل بعيدًا",example:"Mit 20 ist sie aus ihrem Dorf weggezogen."},
  {chapter:3,inf:"veröffentlichen",praes:"veröffentlicht",praet:"veröffentlichte",aux:"haben",part:"veröffentlicht",rektion:"etwas veröffentlichen",ar:"ينشر",example:"Der Autor hat sein erstes Buch mit 60 veröffentlicht."},
  {chapter:3,inf:"sich aufhalten",praes:"hält sich auf",praet:"hielt sich auf",aux:"haben",part:"sich aufgehalten",rektion:"sich aufhalten in + D",ar:"يقيم / يتواجد",example:"Wir haben uns drei Wochen in Portugal aufgehalten."},
  {chapter:4,inf:"sich beschäftigen",praes:"beschäftigt sich",praet:"beschäftigte sich",aux:"haben",part:"sich beschäftigt",rektion:"sich beschäftigen mit + D",ar:"ينشغل بـ",example:"In meinem Job beschäftige ich mich mit Datenschutz."},
  {chapter:4,inf:"herstellen",praes:"stellt her",praet:"stellte her",aux:"haben",part:"hergestellt",rektion:"etwas herstellen",ar:"يصنع / ينتج",example:"Die Firma stellt Möbel aus Holz her."},
  {chapter:4,inf:"aushalten",praes:"hält aus",praet:"hielt aus",aux:"haben",part:"ausgehalten",rektion:"etwas aushalten",ar:"يتحمل",example:"Den Lärm im Großraumbüro halte ich kaum aus."},
  {chapter:4,inf:"sich irren",praes:"irrt sich",praet:"irrte sich",aux:"haben",part:"sich geirrt",rektion:"sich irren in + D",ar:"يخطئ",example:"Entschuldigung, da habe ich mich geirrt."},
  {chapter:4,inf:"verwechseln",praes:"verwechselt",praet:"verwechselte",aux:"haben",part:"verwechselt",rektion:"etwas mit + D verwechseln",ar:"يخلط بين",example:"Ich habe die Termine verwechselt."},
  {chapter:4,inf:"verzeihen",praes:"verzeiht",praet:"verzieh",aux:"haben",part:"verziehen",rektion:"jemandem etwas verzeihen",ar:"يسامح",example:"Verzeihen Sie bitte die Verspätung."},
  {chapter:4,inf:"sich eignen",praes:"eignet sich",praet:"eignete sich",aux:"haben",part:"sich geeignet",rektion:"sich eignen für + A",ar:"يصلح لـ",example:"Er eignet sich gut für die Stelle."},
  {chapter:4,inf:"sich erkundigen",praes:"erkundigt sich",praet:"erkundigte sich",aux:"haben",part:"sich erkundigt",rektion:"sich erkundigen nach + D",ar:"يستفسر عن",example:"Ich habe mich nach den Arbeitszeiten erkundigt."},
  {chapter:4,inf:"sich beziehen",praes:"bezieht sich",praet:"bezog sich",aux:"haben",part:"sich bezogen",rektion:"sich beziehen auf + A",ar:"يشير إلى",example:"Ich beziehe mich auf Ihre Anzeige vom 3. Mai."},
  {chapter:4,inf:"überzeugen",praes:"überzeugt",praet:"überzeugte",aux:"haben",part:"überzeugt",rektion:"jemanden von + D überzeugen",ar:"يقنع",example:"Die Bewerberin hat uns von ihren Ideen überzeugt."},
  {chapter:4,inf:"ankommen",praes:"kommt an",praet:"kam an",aux:"sein",part:"angekommen",rektion:"ankommen auf + A (wichtig sein)",ar:"يصل / يعتمد على",example:"Bei der Bewerbung kommt es auf die Erfahrung an."},
  {chapter:4,inf:"vorbeikommen",praes:"kommt vorbei",praet:"kam vorbei",aux:"sein",part:"vorbeigekommen",rektion:"vorbeikommen bei + D",ar:"يمر على",example:"Kommen Sie morgen einfach im Büro vorbei."},
  {chapter:5,inf:"verbrauchen",praes:"verbraucht",praet:"verbrauchte",aux:"haben",part:"verbraucht",rektion:"etwas verbrauchen",ar:"يستهلك",example:"Unser alter Kühlschrank hat viel Strom verbraucht."},
  {chapter:5,inf:"schützen",praes:"schützt",praet:"schützte",aux:"haben",part:"geschützt",rektion:"schützen vor + D",ar:"يحمي",example:"Bäume schützen die Stadt vor Hitze."},
  {chapter:5,inf:"ergreifen",praes:"ergreift",praet:"ergriff",aux:"haben",part:"ergriffen",rektion:"Maßnahmen ergreifen",ar:"يتخذ (إجراء)",example:"Die Stadt hat Maßnahmen gegen den Verkehr ergriffen."},
  {chapter:5,inf:"messen",praes:"misst",praet:"maß",aux:"haben",part:"gemessen",rektion:"etwas messen",ar:"يقيس",example:"Gestern wurden 38 Grad gemessen."},
  {chapter:5,inf:"unterstützen",praes:"unterstützt",praet:"unterstützte",aux:"haben",part:"unterstützt",rektion:"jemanden bei + D unterstützen",ar:"يدعم / يساعد",example:"Die Nachbarn haben uns beim Umzug unterstützt."},
  {chapter:5,inf:"verschwenden",praes:"verschwendet",praet:"verschwendete",aux:"haben",part:"verschwendet",rektion:"etwas verschwenden",ar:"يهدر",example:"Wir sollten kein Wasser verschwenden."},
  {chapter:5,inf:"zerstören",praes:"zerstört",praet:"zerstörte",aux:"haben",part:"zerstört",rektion:"etwas zerstören",ar:"يدمر",example:"Der Sturm hat viele Bäume zerstört."},
  {chapter:5,inf:"unterscheiden",praes:"unterscheidet",praet:"unterschied",aux:"haben",part:"unterschieden",rektion:"unterscheiden zwischen + D",ar:"يميز / يفرّق",example:"Man muss zwischen Papier und Plastik unterscheiden."},
  {chapter:5,inf:"entstehen",praes:"entsteht",praet:"entstand",aux:"sein",part:"entstanden",rektion:"entstehen aus + D",ar:"ينشأ",example:"Aus der Idee ist ein großes Projekt entstanden."},
  {chapter:5,inf:"vermeiden",praes:"vermeidet",praet:"vermied",aux:"haben",part:"vermieden",rektion:"etwas vermeiden",ar:"يتجنب",example:"Ich versuche, Plastikmüll zu vermeiden."},
  {chapter:5,inf:"widersprechen",praes:"widerspricht",praet:"widersprach",aux:"haben",part:"widersprochen",rektion:"jemandem (D) widersprechen",ar:"يعارض",example:"Da muss ich dir widersprechen."},
  {chapter:5,inf:"sich beteiligen",praes:"beteiligt sich",praet:"beteiligte sich",aux:"haben",part:"sich beteiligt",rektion:"sich beteiligen an + D",ar:"يشارك في",example:"Viele Schüler haben sich an der Aktion beteiligt."},
  {chapter:5,inf:"schaden",praes:"schadet",praet:"schadete",aux:"haben",part:"geschadet",rektion:"jemandem / etwas (D) schaden",ar:"يضر",example:"Zu viel Zucker schadet der Gesundheit."},
  {chapter:6,inf:"übernehmen",praes:"übernimmt",praet:"übernahm",aux:"haben",part:"übernommen",rektion:"etwas übernehmen",ar:"يتولى / يتحمل",example:"Ich übernehme die Organisation der Feier."},
  {chapter:6,inf:"sich vornehmen",praes:"nimmt sich vor",praet:"nahm sich vor",aux:"haben",part:"sich vorgenommen",rektion:"sich (D) etwas vornehmen",ar:"ينوي / يقرر",example:"Für das neue Jahr habe ich mir viel vorgenommen."},
  {chapter:6,inf:"gelingen",praes:"gelingt",praet:"gelang",aux:"sein",part:"gelungen",rektion:"jemandem (D) gelingen",ar:"ينجح (معه)",example:"Der Kuchen ist mir gut gelungen."},
  {chapter:6,inf:"ausgehen",praes:"geht aus",praet:"ging aus",aux:"sein",part:"ausgegangen",rektion:"ausgehen von + D (annehmen)",ar:"يخرج للسهر / يفترض",example:"Ich gehe davon aus, dass das Projekt klappt."},
  {chapter:6,inf:"sich befinden",praes:"befindet sich",praet:"befand sich",aux:"haben",part:"sich befunden",rektion:"sich befinden in / auf + D",ar:"يقع / يوجد",example:"Das Büro befindet sich im dritten Stock."},
  {chapter:6,inf:"begegnen",praes:"begegnet",praet:"begegnete",aux:"sein",part:"begegnet",rektion:"jemandem (D) begegnen",ar:"يقابل صدفة",example:"Gestern bin ich meiner alten Lehrerin begegnet."},
  {chapter:6,inf:"wachsen",praes:"wächst",praet:"wuchs",aux:"sein",part:"gewachsen",rektion:"—",ar:"ينمو",example:"Die Stadt ist in den letzten Jahren stark gewachsen."},
  {chapter:6,inf:"nachdenken",praes:"denkt nach",praet:"dachte nach",aux:"haben",part:"nachgedacht",rektion:"nachdenken über + A",ar:"يفكر في",example:"Ich habe lange über deinen Vorschlag nachgedacht."},
  {chapter:6,inf:"bewerten",praes:"bewertet",praet:"bewertete",aux:"haben",part:"bewertet",rektion:"etwas bewerten",ar:"يقيّم",example:"Die Kunden haben das Hotel sehr gut bewertet."},
  {chapter:6,inf:"bezeichnen",praes:"bezeichnet",praet:"bezeichnete",aux:"haben",part:"bezeichnet",rektion:"etwas als + A bezeichnen",ar:"يصف / يسمي",example:"Viele bezeichnen ihn als Genie."}
];
