/* Generated by scripts/a1_images/slice_sheets.py - do not edit by hand.
   Pictures for A1.1 words that had none, keyed by "chapter|headword".
   Loaded after data_a11_vocab.js; it only fills cards that still have no picture. */
window.A1_VOCAB_11_IMAGES = {
 "1|grüßen": "assets/a1/vocab_ai/new/k1-gruessen.webp",
 "1|sich verabschieden": "assets/a1/vocab_ai/new/k1-sich-verabschieden.webp",
 "1|der Herr, -en": "assets/a1/vocab_ai/new/k1-der-herr-en.webp",
 "1|der Reiseführer, -": "assets/a1/vocab_ai/new/k1-der-reisefuehrer.webp",
 "1|die Reiseführerin, -nen": "assets/a1/vocab_ai/new/k1-die-reisefuehrerin-nen.webp",
 "1|der Kranke, -n": "assets/a1/vocab_ai/new/k1-der-kranke-n.webp",
 "1|das Telefon, -e": "assets/a1/vocab_ai/new/k1-das-telefon-e.webp",
 "1|die Handynummer, -n": "assets/a1/vocab_ai/new/k1-die-handynummer-n.webp",
 "1|Algerien": "assets/a1/vocab_ai/new/k1-algerien.webp",
 "1|Brasilien": "assets/a1/vocab_ai/new/k1-brasilien.webp",
 "1|Frankreich": "assets/a1/vocab_ai/new/k1-frankreich.webp",
 "1|Griechenland": "assets/a1/vocab_ai/new/k1-griechenland.webp",
 "1|Italien": "assets/a1/vocab_ai/new/k1-italien.webp",
 "1|Japan": "assets/a1/vocab_ai/new/k1-japan.webp",
 "1|Mexiko": "assets/a1/vocab_ai/new/k1-mexiko.webp",
 "1|Polen": "assets/a1/vocab_ai/new/k1-polen.webp"
};

(function applyA11Images(){
  if(!Array.isArray(window.A1_BOOK)) return;
  window.A1_BOOK.forEach(chapter=>{
    (chapter.vocab||[]).forEach(card=>{
      const src=window.A1_VOCAB_11_IMAGES[chapter.num+'|'+card.w];
      if(src&&!card.img) card.img=src;
    });
  });
})();
