window.A1_GRAMMAR_FULL = [
  {
    "lesson": 1,
    "topic": 1,
    "title": "Verb - Konjugation",
    "pdfPage": 3,
    "lines": [
      "lern-en",
      "du lernst schreib-en",
      "ich schreibe",
      "Personalpronomen > Endung",
      "Ich lerne Deutsch. ich > -e",
      "Du lernst Deutsch. du > -st",
      "(Carlos) Er lernt Deutsch. Carlos > -t",
      "(Lena) Sie lernt Deutsch. Lena > -t",
      "(Carlos und ich) Wir lernen Deutsch. wir > -en",
      "(Lena und du) Ihr lernt Deutsch. ihr > -t",
      "(Lena und Carlos) Sie lernen Deutsch. Lena und Carlos > -en",
      "Übung 1",
      "Beispiel: gehen Du geh s t ins Kino.",
      "kommen kaufen",
      "a) Maria komm___ aus Rom. e) Martin kauf___ Obst.",
      "b) Carlos komm___ aus Madrid. f) Maria kauf___ Cola.",
      "c) Ich komm__ aus _______________. g) Robert und Inga kauf___ Eis.",
      "d) Karl und Eva komm___ aus Passau. h) Ich kauf___ Mineralwasser.",
      "wohnen trinken",
      "i) Ich wohn___ in Passau. m) Du trink___ Orangensaft.",
      "j) Carlos wohn___ auch in Passau. n) Ihr trink___ Kaffee.",
      "k) Wir wohn___ in Passau. o) Ich trink___ Bier.",
      "l) Ihr wohn__ auch in Passau. p) Robert trink___ Mineralwasser.",
      "Übung 2",
      "Beispiel: Max komm t aus Köln.",
      "wohnst gehen kommt hört studiert kauft trinken mache kennt lernst lebt",
      "a) Murat ____________ Musik. f) Wir ____________ nach Hause.",
      "b) Du ____________ in Passau. g) Theo ____________ Eva.",
      "c) Hanna ____________ in Wien. h) Du ____________ Deutsch.",
      "d) Ich ____________ eine Pause. i) Eva ____________ ein Eis.",
      "e) Ihr ____________ in Berlin. j) Wir ____________ Saft.",
      "Übung 3",
      "Beispiel: kaufen Lena kauft Cola. Und du? - Ich kaufe Saft.",
      "a) kommen Hatem komm__ aus Kairo. Und du? - Ich komm__ ______ ______________.",
      "b) trinken Ich trink__ Kaffee. Und du? - Ich trink__ Wasser.",
      "c) wohnen Maria wohn__ in Rom. Und du? - Ich wohn__ in _________________.",
      "d) fragen Wir frag__ Frau Lehmann. Und du? - Ich frag__ Theo.",
      "e) studieren Paul studier__ in München. Und du? Ich studier__ auch in München.",
      "f) gehen Ich geh__ nach Hause. Und du? - Ich geh__ auch nach Hause.",
      "arbeit-en, wart-en, bad-en, find-en, red-en > -t, -d arbeit-en",
      "Du arbeitest.",
      "Ich arbeite",
      "Lena arbeitet. Du arbeitest < + e",
      "Ihr arbeitet. Carlos arbeitet < + e",
      "Hanna arbeitet < + e",
      "Wir arbeiten",
      "Ihr arbeitet < + e",
      "Maria und Carlos arbeiten",
      "tanz-en tanz-en, küss-en, heiß-en, reis-en > -s, -ss, -ß, -z",
      "Du tanzt.",
      "Ich tanze",
      "Du tanzt < kein s",
      "Carlos tanzt",
      "Hanna tanzt",
      "Wir tanzen",
      "Ihr tanzt",
      "Maria und Carlos tanzen",
      "Achtung! Verben auf el-n: z. B. bügeln - ich bügle (selten: ich bügele)",
      "bügel-n, lächel-n, sammel-n, stempel-n, googel-n",
      "Übung 4",
      "Ergänzen Sie die Endungen.",
      "reden antworten",
      "a) Ich red___ mit Paul. e) Der Student antwort___.",
      "b) Du red___ mit Klaus. f) Ich antwort___ Carlos.",
      "c) Wir red___ mit Maria. g) Du antwort___ Maria.",
      "d) Paul red___ mit Eva. h) Ihr antwort___ nicht.",
      "reisen heißen",
      "i) Wir reis___ nach Spanien. m) Die Studentin heiß___ Elena.",
      "j) Ich reis___ nach Polen. n) Der Student heiß___ Carlos.",
      "k) Du reis___ nach Frankreich. o) Du heiß___ ________________________.",
      "l) Ihr reis___ nach Kanada. p) Ich heiß___ ________________________.",
      "Übung 5",
      "Beispiel: Du studierst .",
      "a) Ich studier___. b) Ihr arbeit___.",
      "Max studier___. Lena und Hanna arbeit___.",
      "Wir studier___. Wir arbeit___.",
      "Eva studier___. Du arbeit___.",
      "Paul und Maria studier___. Ich arbeit___.",
      "Ihr studier___. Max arbeit___.",
      "c) Wir reis___ nach Prag. d) Thomas und Eva red___ mit Lena.",
      "Ich reis___ nach Prag. Du red___ mit Lena.",
      "Carlos reis___ nach Prag. Ich red___ mit Lena.",
      "Ihr reis___ nach Prag. Hanna red___ mit Lena.",
      "Du reis___ nach Prag. Ihr red___ mit Lena.",
      "Lena und Theo reis___ nach Prag. Wir red___ mit Lena.",
      "sein",
      "Ich bin Student*in.",
      "Du bist Student*in.",
      "Lena ist Studentin.",
      "Theo ist Student.",
      "Wir sind Studenten.",
      "Ihr seid Studenten.",
      "Max und Paul sind Studenten.",
      "Eva und Lena sind Studentinnen.",
      "Ich bin Lena / Studentin. > Wer? / Was?",
      "Ich bin krank. > Wie?",
      "Ich bin hier. > Wo?",
      "Übung 6",
      "Beispiel: Paul und Eva - im Supermarkt Paul und Eva sind im Supermarkt.",
      "a) Max - im Kino c) Wir - im Hotel e) Ihr - im Bus",
      "b) Du - in Berlin d) Paul und Jana - zu Hause f) Ich - im Deutschkurs",
      "Übung 7",
      "Beispiel: Ich bin nicht zu Hause.",
      "a) Julia und Maria ________ in Italien. f) Carlos ________ Spanier.",
      "b) Du ________ hier. g) Ihr ________ im Bus.",
      "c) Wir ________ im Supermarkt. h) Ich ________ im Deutschkurs.",
      "d) Ihr ________ nicht in Rom. i) Du ________ nett.",
      "e) Lena ________ zu Hause. j) Pedro ________ krank."
    ],
    "id": "1.1",
    "exerciseCount": 0
  },
  {
    "lesson": 1,
    "topic": 2,
    "title": "Personalpronomen - Nominativ",
    "pdfPage": 6,
    "lines": [
      "Was studierst du? - Ich studiere Mathematik.",
      "Was studiert ihr? - Wir studieren Jura.",
      "Was studiert Max? - Er studiert Medizin.",
      "Was studiert Anna? - Sie studiert Informatik.",
      "Was studieren Carlos und Maria? - Sie studieren Deutsch.",
      "Ich trinke Limonade. (Peter und ich) Wir trinken Tee.",
      "Du trinkst Kaffee. (Maria und du) Ihr trinkt Orangensaft.",
      "(Carlos) Er trinkt Cola.",
      "(Maria) Sie trinkt Mineralwasser. (Paul und Lisa) Sie trinken Milch.",
      "(Mädchen) Es trinkt Apfelsaft.",
      "Übung 1",
      "Beispiel: Carlos - hören - Musik Hört Carlos Musik? - Ja, er hört Musik.",
      "a) Frau Weiß - arbeiten c) ihr - lernen e) ihr - trinken - Saft",
      "b) Peter - reden d) du - studieren f) Eva und Lisa - tanzen",
      "Übung 2",
      "Ergänzen Sie.",
      "a) Du lernst doch Deutsch, oder? - Ja, ______ lerne Deutsch.",
      "b) Du gehst doch jetzt nach Hause, oder? - Ja, ______ ________ nach Hause.",
      "c) Carlos lernt doch auch Deutsch, oder? - Ja, ______ ________ auch Deutsch.",
      "d) Maria kommt doch aus Italien, oder? - Ja, ______ __________ aus Italien.",
      "e) Ihr studiert doch in München, oder? - Ja, ______ ____________ in München.",
      "f) Eva und Max wohnen doch in Köln, oder? - Ja, ______ ______________ in Köln.",
      "Übung 3",
      "Ergänzen Sie.",
      "a) Herr Schneider wohn__ in München. Er ist Lehrer.",
      "b) Herr Schneider trinkt Wasser. _____ trinkt kein Bier.",
      "c) Wohnt Herr Schneider in München? - Ja, ______ ________ in München.",
      "d) Was ______ Herr Schneider von Beruf? - ______ _____ Lehrer.",
      "e) Wie heißt die Frau? - ______ ________ Frau Berg.",
      "f) Frau Berg _______ in Köln. ______ ist Reporterin.",
      "g) Wo ________ Frau Berg? - ______ _________ in Köln.",
      "h) Was ist _____ von Beruf? - ______ ______ Reporterin.",
      "Übung 4",
      "Beispiel: Wo wohnt Carlos? - Er wohnt in Rom.",
      "a) Wie heißt die Studentin? - ______ heißt Maria.",
      "b) Was trinkt Herr Klein? - ______ trinkt Orangensaft.",
      "c) Was studieren Max und Anna? - ______ studieren Jura.",
      "d) Wo wohnt ihr? - ______ wohnen in Passau.",
      "e) Was bist du von Beruf? - ______bin Reporter."
    ],
    "id": "1.2",
    "exerciseCount": 0
  },
  {
    "lesson": 1,
    "topic": 3,
    "title": "Wortstellung: Aussagesatz / Fragesätze",
    "pdfPage": 7,
    "lines": [
      "Aussagesatz: Maria kommt aus Rom. Information, Erklärung etc.",
      "Fragesatz ohne Fragewort: Kommt Maria aus Rom? Ja / Nein - Frage",
      "Fragesatz mit Fragewort: Woher kommt Maria? Frage nach bestimmter Information",
      "- Aussagesatz",
      "Position II",
      "Maria kommt aus Rom.",
      "Aus Rom kommt Maria",
      "Übung 1",
      "Beispiel: Wir lernen Deutsch. > Deutsch lernen wir.",
      "a) Ich komm__ morgen. d) Wir trink___ Saft.",
      "b) Maria studier__ Informatik. e) Ihr studier__ in Passau.",
      "c) Du wohn___ in Passau. f) Carlos kauf__ Obst.",
      "Übung 2",
      "Beispiel: wohnen Clara - in Wien Clara wohnt in Wien > In Wien wohnt Clara.",
      "a) hören wir - Musik e) kommen Dora - aus Ungarn",
      "b) reisen Max und Eva - nach Irland f) schreiben ich - eine SMS",
      "c) kaufen wir - Brot g) studieren Lena - in Wien",
      "d) arbeiten Herr Berg - in München h) sein du - zu Hause",
      "- Fragesatz mit Fragewort - W-Fragen",
      "Anna studiert Medizin.",
      "Wer studiert Medizin? > Anna.",
      "Was studiert Anna? > Medizin.",
      "Wie heißt die Studentin? > Anna.",
      "Übung 3",
      "Beispiel: Was machst du? - Ich lerne Deutsch.",
      "a) _______ kauft Brot? - Carlos __________ Brot.",
      "b) _______ heißt die Lehrerin? - Sie ___________ Frau Lehmann.",
      "c) _______ trinkt Paul? - Paul ________ Bier.",
      "d) _______ wohnt in Passau? - Peter und Maria __________ in Passau.",
      "e) _______ studiert ihr? - _____ studieren Jura.",
      "f) _______ lernt Deutsch? - Wir _____________ Deutsch.",
      "g) _______ alt ist Thomas? - _____ ______ 20 Jahre alt.",
      "h) _______ spät ist es? - Es _____ jetzt 12:00 Uhr.",
      "Wo bist du?",
      "=",
      "Wohin gehst du? > Wo gehst du hin?",
      "è",
      "ç",
      "Woher kommst du? > Wo kommst du her?",
      "=",
      "wo?",
      "in Ägypten",
      "è ç",
      "wohin? woher?",
      "nach Ägypten von zu Hause",
      "=",
      "wo?",
      "zu Hause",
      "ç",
      "è woher?",
      "wohin?",
      "aus Ägypten",
      "nach Hause",
      "Übung 4",
      "Ergänzen Sie.",
      "a) _______ ist das? - Das ist Käse.",
      "_______ kauft Käse? - Peter kauft Käse.",
      "_______ kauft Peter Käse? - Im Supermarkt.",
      "_______ komm__ der Käse? - Aus Frankreich.",
      "b) _______ ist das? - Das ist ___________________.",
      "_______ trink__ _____________? - Eva trink__ ________________.",
      "_______ kauft Eva ______________? - Im Supermarkt.",
      "_______ kommt der _____________? - _______ Spanien.",
      "c) _______ ist das? - Das _______ Brot.",
      "_______ kauf__ Brot? - Paul und Maria kauf__ Brot.",
      "_______ kauf__ Paul und Maria Brot? - Im Supermarkt.",
      "d) _______ ist das? - Das _______ __________.",
      "_______ trink__ ________? - Du trink__ _______.",
      "_______ komm__ der ________? - Aus Italien.",
      "wo? Max wohn__ ____Wien. Lisa arbeit___ ____ Hause. Wir studier___ ____ Zürich.",
      "wohin? Wir reis___ ______ Rom. Du flieg___ ______ Japan. Jana geh___ ______ Hause.",
      "woher? Ich komm___ _____ ____ Hause. Ihr komm___ _____ Syrien. Hatem komm__ _____ Kairo.",
      "Übung 5",
      "Ergänzen Sie: wo - wohin - woher",
      "a) ________ studierst du? d) ________ kommst du?",
      "b) ________ gehst du? e) ________ arbeitest du?",
      "c) ________ wohnst du? f) ________ bist du?",
      "- Fragesatz ohne Fragewort - Ja / Nein-Fragen",
      "Position I",
      "Arbeitest du in Passau? - Ja, ich arbeite in Passau. Fragen ohne Fragewort: Verb > Position I",
      "Übung 6",
      "Beispiel: Bist du Student*in? Ja, ich bin Student*in.",
      "Trinkt ihr Tee? Ja, wir trinken Tee.",
      "a) Fragst du Lisa? g) Studiert ihr in Wien?",
      "b) Reist du nach Italien? h) Lernt ihr Deutsch?",
      "c) Arbeitest du mit Hatem? i) Redet ihr mit Paul?",
      "d) Tanzt du gern? j) Wohnt ihr in Passau?",
      "e) Kaufst du Butter? k) Fliegt ihr nach Paris?",
      "f) Gehst du nach Hause? l) Seid ihr zu Hause?",
      "Übung 7",
      "Beispiel: Bestellst du Tee? (Kaffee) > Nein, ich bestel l e Kaffee.",
      "a) Trinkt ihr Cola? (Orangensaft)",
      "b) Arbeitest du in Berlin? (Köln)",
      "c) Kommt ihr aus Österreich? (Spanien)",
      "d) Antwortest du? (nicht)",
      "e) Geht ihr ins Kino? (nach Hause)",
      "f) Kaufst du Käse? (Wurst)",
      "g) Studiert ihr in Wien? (Passau)",
      "h) Fliegst du nach Tokio? (Kairo)",
      "Studierst du? + Ja, ich studiere.",
      "Und du? Studierst du auch? - Nein, ich studiere nicht.",
      "Studierst du nicht? + Doch, ich studiere.",
      "Und du? Studierst du nicht? - Nein, ich studiere nicht.",
      "Übung 8",
      "Antworten Sie auf die Fragen.",
      "a) Studiert Maria Mathematik? + Ja, __________________________________",
      "b) Kommt Carlos aus London? - Nein, ________________________________",
      "c) Reist du nach England? + ____________________________________",
      "d) Lernst du nicht Deutsch? + ____________________________________",
      "e) Kommst du nicht aus Tokio? - ____________________________________",
      "f) Gehst du nach Hause? - ____________________________________",
      "g) Trinkst du Tee? + ____________________________________",
      "h) Arbeitest du nicht in München? - ____________________________________",
      "i) Gehst du ins Kino? - ____________________________________",
      "j) Studieren Robert und Eva Jura? + ____________________________________"
    ],
    "id": "1.3",
    "exerciseCount": 0
  },
  {
    "lesson": 2,
    "topic": 1,
    "title": "Starke Verben",
    "pdfPage": 10,
    "lines": [
      "Ich fahre nach München. - Wohin fährst du? (a > ä) Ich lese Zeitung. - Was liest du? (e > i / ie)",
      "schwach (regulär) stark (irregulär) schwach (regulär) stark (irregulär)",
      "ich frage ich fahre ich lerne ich lese",
      "du fragst du fährst du lernst du liest",
      "er / sie / es fragt er / sie / es fährt er / sie / es lernt er / sie / es liest",
      "wir fragen wir fahren wir lernen wir lesen",
      "ihr fragt ihr fahrt ihr lernt ihr lest",
      "sie / Sie fragen sie / Sie fahren sie / Sie lernen sie / Sie lesen",
      "a > ä Übung 1",
      "braten ich brate - du brätst Beispiel: Schreibt Peter? (reden)",
      "fahren ich fahre - du fährst Peter schreibt nicht, er redet.",
      "halten ich halte - du hältst a) Trinkt Inge? (essen)",
      "schlafen ich schlafe - du schläfst",
      "b) Lernt Christian? (schlafen)",
      "tragen ich trage - du trägst",
      "c) Geht Lena? (laufen)",
      "waschen ich wasche - du wäschst",
      "d) Arbeitet Klaus? (Zeitung lesen)",
      "e > i e) Bleibt Claudia? (nach Hause fahren)",
      "essen ich esse - du isst",
      "geben ich gebe - du gibst Übung 2",
      "helfen ich helfe - du hilfst Beispiel: Ich schlafe lange. - Carlos - nicht lange",
      "nehmen ich nehme - du nimmst Carlos schläft nicht lange.",
      "sprechen ich spreche - du sprichst",
      "a) Ich fahre nach München. - Eva - nach Bremen",
      "treffen ich treffe - du triffst",
      "b) Ich spreche langsam. - du - schnell",
      "e > ie c) Ich lese Zeitung. - Max - ein Deutschbuch",
      "lesen ich lese - du liest d) Ich trage braune Schuhe. - Sandra - schwarze Schuhe",
      "sehen ich sehe - du siehst e) Ich esse Kuchen. - Pavel - Obst",
      "f) Ich helfe Peter. - du - Julia",
      "au > äu",
      "g) Ich laufe nicht schnell. - Laura - auch nicht schnell",
      "laufen ich laufe - du läufst",
      "schwache Verben (mit -t oder -d)",
      "warten ich warte du wartest er / sie / es wartet wir warten ihr wartet sie / Sie warten",
      "reden ich rede du redest er / sie / es redet wir reden ihr redet sie / Sie reden",
      "starke Verben (mit -t oder -d)",
      "halten ich halte du hältst er / sie / es hält wir halten ihr haltet sie / Sie halten",
      "Übung 3",
      "Beispiel: Ich wohne in Passau. Und du? Wohnst du auch in Passau?",
      "a) Ich lese viel. Und du? e) Ich laufe im Park. Und du?",
      "b) Ich esse gerne Eis. Und du? f) Ich fahre Fahrrad. Und du?",
      "c) Ich schlafe lange. Und du? g) Ich nehme eine Pizza. Und du?",
      "d) Ich helfe Klaus. Und du? h) Ich spreche mit Max. Und du?"
    ],
    "id": "2.1",
    "exerciseCount": 0
  },
  {
    "lesson": 2,
    "topic": 2,
    "title": "Nomen und Artikel - Nominativ",
    "pdfPage": 11,
    "lines": [
      "Bestimmte Artikel",
      "Der Student wohnt in Passau. maskulin der",
      "Die Reporterin wohnt in Köln. feminin die Nomen (Substantive)",
      "Das Mädchen wohnt in München. neutral das immer groß schreiben!",
      "Die Studenten lernen Deutsch. Plural die",
      "Le rne n Si e di e Nom e n i mme r m i t Ar ti k el !",
      "Übung 1",
      "Kennen Sie die Artikel?",
      "a) _____ Hotel e) _____ Stift i) _____ Supermarkt",
      "b) _____ Bier f) _____ Flasche j) _____ Kino",
      "c) _____ Milch g) _____ Brot k) _____ Freund",
      "d) _____ Orangensaft h) _____ Schule l) _____ Professorin",
      "Personennamen, Städtenamen etc. > meist kein Artikel (Paul, München, Italien)",
      "generell: Bier, Milch, Brot, Käse, Musik > Paul trinkt Bier. / Ich höre Musik",
      "bestimmt: das Bier, die Milch, das Brot, der Käse, die Musik > Paul trinkt das Bier. / Ich höre die Musik.",
      "Plural",
      " das Fenster die Fenster",
      "⠉+  der Mantel die Mäntel",
      "e das Brot die Brote",
      "⠉+ e die Hand die Hände",
      "-er das Kind die Kinder",
      "⠉+ er das Buch die Bücher",
      "[n/e]n die Übung die Übungen",
      "die Tasche die Taschen",
      "die Ärztin die Ärztinnen",
      "-s das Auto die Autos",
      "Kaffee, Tee, Milch, Wasser, Schnee, Musik, Ruhe etc. > meist kein Plural",
      "Übung 2",
      "Beispiel: das Brot - die Brote",
      "a) ____ Lehrer - die ____________ e) ____ Schule - die ____________",
      "b) ____ Übung - die ____________ f) ____ Stadt - die ____________",
      "c) ____ Frage - die ____________ g) ____ Baum - die ____________",
      "d) ____ Fahrrad - die ____________ h) ____ Beruf - die ____________",
      "Übung 3",
      "Beispiel: die Tomate - die Tomaten",
      "a) _____________________ c) _____________________",
      "b) _____________________ d) _____________________",
      "Unbestimmte Artikel",
      "ein Baum > maskulin ein",
      "eine Uhr > feminin eine Was ist das? - Das ist ein Baum.",
      "ein Buch > neutral ein",
      "Bücher > Plural Unbestimmt Plural: kein Artikel",
      "Was ist das? - Das sind Bücher.",
      "Übung 4",
      "Beispiel: Was ist das? (Tisch) Das ist ein Tisch.",
      "a) (Stuhl) d) (Stifte) g) (Jacke) j) (Deutschbücher)",
      "b) (Tasche) e) (Tasse) h) (Äpfel) k) (Blumen)",
      "c) (Mappe) f) (Computer) i) (Tür) l) (Schuhe)",
      "Negation",
      "Negation mit „nicht“",
      "Liest du? - Nein, ich lese nicht.",
      "Lernst du Spanisch? - Nein, ich lerne nicht Spanisch.",
      "Studierst du Jura? - Nein, ich studiere nicht Jura.",
      "Kennst du Lisa? - Nein, ich kenne Lisa nicht.",
      "Tanzt du gern? - Nein, ich tanze nicht gern.",
      "Wohnst du in Berlin? - Nein, ich wohne nicht in Berlin.",
      "Trinkst du das Wasser? - Nein, ich trinke das Wasser nicht.",
      "Negation mit „kein“",
      "Ist das ein Apfel? - Nein, das ist kein Apfel.",
      "Ist das eine Orange? - Nein, das ist keine Orange.",
      "Ist das ein Brot? - Nein, das ist kein Brot.",
      "Sind das Äpfel? - Nein, das sind keine Äpfel.",
      "Übung 5",
      "Beispiel: Lebst du in Köln? - Nein, ich lebe nicht in Köln.",
      "a) Reist du nach Hamburg? - Nein, ... d) Bist du krank? - Nein, ...",
      "b) Kommt Carlos aus Rom? - Nein, ... e) Gehst du ins Kino? - Nein, ...",
      "c) Besuchst du Klaus? - Nein, ... f) Lernt Carlos viel? - Nein, ...",
      "Getränke und Speisen oft ohne Artikel > Negation: kein",
      "Übung 6",
      "Ergänzen Sie.",
      "_____ ist das? Ist das Brot?",
      "Nein, das ist kein _________. Das ist ___________.",
      "______ ist das? Ist ______ Suppe?",
      "Nein, das ______ _______ Suppe. Das ______ _____________.",
      "______ ist _____ ? ______ das Milch?",
      "Nein, das _____ _______ Milch. Das ist _____________________.",
      "Was ______ ______? Ist ______ Apfelsaft?",
      "Nein, das _____ _______ __________________. Das ist ______________."
    ],
    "id": "2.2",
    "exerciseCount": 0
  },
  {
    "lesson": 2,
    "topic": 3,
    "title": "Anrede",
    "pdfPage": 13,
    "lines": [
      "Peter, wo wohnst du?",
      "familiär Singular - du Plural - ihr",
      "Herr Maier, wo wohnen Sie?",
      "offiziell Singular - Sie Plural - Sie",
      "Mark und Robert, wo wohnt ihr?",
      "Herr und Frau Müller, wo wohnen Sie?",
      "Übung 1",
      "Ergänzen Sie.",
      "a) Ich frage Carlos: c) Ich frage Anna und Maria:",
      "Wie heiß__ ___? Wie heiß__ _____?",
      "Lern__ ____ Deutsch? Studier__ _____ in Passau?",
      "Komm__ ____ aus Madrid? Lern__ _____ Deutsch?",
      "Wohn__ ____ in Passau? Komm__ _____ aus Italien?",
      "Trink__ ____ Bier? Trink__ _____ Wein?",
      "b) Ich frage Frau Mayer: d) Ich frage Frau Müller und Frau Berg:",
      "Wie heiß__ ___? Wo wohn__ _____?",
      "Arbeit__ ____ in Berlin? Fahr__ _____ nach Frankfurt?",
      "Komm__ ____ aus Köln? Lern__ _____ Deutsch?",
      "Wohn__ ____ in Dresden? Geh__ _____ ins Kino?",
      "Trink__ ____ Wein? Trink__ _____ Bier?",
      "Übung 2",
      "Maria fragt:",
      "a) Was studier___ ______, Robert? e) Wohn___ _____ in München, Frau Klein?",
      "b) Arbeit___ ______ in München, Herr Berg? f) Lern___ _____ auch Englisch, Peter?",
      "c) Trink___ _____ Wein, Carlos? g) Komm___ _____, Papa?",
      "d) Hallo Anna, hallo Eva! Komm__ _____? h) Herr und Frau Moor, haben ______ Zeit?",
      "Übung 3",
      "Ergänzen Sie die Sätze.",
      "a) Peter frag__ Julia: „Studier__ _____ Mathematik?“",
      "b) Der Reporter frag__ Frau Weiß: „Wie heiß__ _____?“",
      "c) Du frag__ Maria: „Geh__ _____ ins Kino?“",
      "d) Paul fragt Max und Julia: „Was mach__ _____ morgen?“",
      "e) Der Professor fragt Carlos und Peter: „Woher komm__ _____?“",
      "f) Ich frage Max und Robert: „Spiel__ _____ Fußball?“",
      "g) Du frag__ die Touristen: „Komm__ _____ aus Wien?“",
      "Übung 4",
      "Ergänzen Sie die Pronomen.",
      "Herr Klein: Entschuldigen _____, sind _____ nicht aus England?",
      "Carlos: Nein, _____ komme aus Spanien.",
      "Herr Klein: Ach so! Kommen _____ aus Malaga?",
      "Carlos: Nein, _____ komme aus Madrid. Und woher kommen _____?",
      "Herr Klein: _____ komme aus Meran.",
      "Carlos: Ach, _____ kommen aus Italien.",
      "Herr Klein: Ja, _____ komme aus Norditalien."
    ],
    "id": "2.3",
    "exerciseCount": 0
  },
  {
    "lesson": 3,
    "topic": 1,
    "title": "Nomen - Genusregeln",
    "pdfPage": 14,
    "lines": [
      "d e r d i e d a s",
      "männliche Personen und Tiere weibliche Personen und Tiere",
      "der Kollege, der Löwe die Studentin, die Katze",
      "männliche Berufe weibliche Berufe",
      "der Arzt die Ärztin",
      "Monate, Tage, Tageszeit* oft: Gemüse, Obst -chen, -lein",
      "der Mai, der Montag, der Morgen die Tomate, die Birne das Mädchen, das Tischlein",
      "-or -ei -ment",
      "der Motor die Bäckerei das Appartement",
      "-en -ung, -heit, -keit, schaft -um",
      "der Garten die Zeitung, die Krankheit, die Mannschaft das Zentrum",
      "-ismus -tät, -ion, -ik, -ur Infinitiv + das",
      "der Tourismus die Aktion das Lernen",
      "* aber: die Nacht",
      "Übung 1",
      "Sortieren Sie.",
      "Onkel Wohnung Wagen Lehrerin Tischchen Nachbar Brötchen Freundin Mai",
      "Zeitung Professor Polizei Datum Information Packung Reporterin Metzgerei Natur",
      "Musik Mittwoch Opa Optimismus Gesundheit Dokument Monitor Fabrik Wirtschaft",
      "der (mask.) die (fem.) das (neutr.)",
      "O n ke l,",
      "Endung -en > Schreiben Sie die Artikel.",
      "1. Nomen auf -en (meist mask.): der Wagen / der Ofen",
      "2. z. T. für Plural (oft mask. oder fem.): der Student > die Studenten / die Tür > die Türen",
      "3. Infinitiv als Nomen (neutr.): lernen > das Lernen",
      "Achtung: Manchmal gibt es mehr Möglichkeiten:",
      "z. B. Reisen >> das Reisen (Infinitiv als Nomen) / die Reisen (Pl. von die Reise)",
      "Übung 2",
      "Sortieren Sie.",
      "Jacken Essen Übungen Norden Augen Tanzen Kuchen Hosen Lesen Regen",
      "Taschen Garten Krankheiten Schinken Leben Antworten Sprechen Birnen Braten",
      "der (mask. Nomen) das (Infinitiv als Nomen) die (Plural)",
      "Jacken,"
    ],
    "id": "3.1",
    "exerciseCount": 0
  },
  {
    "lesson": 3,
    "topic": 2,
    "title": "Nomen - Komposita",
    "pdfPage": 15,
    "lines": [
      "der Kaffee + die Maschine > die Kaff ee ma sch in e",
      "Gru n dw o rt",
      "Übung 1",
      "Schreiben Sie den Artikel und markieren Sie das Grundwort.",
      "Beispiel: der Co mp ut e r k urs",
      "a) _____ W ört e rb u ch e) _____ Ca mp in gb u s",
      "b) _____ St au b sau ge r f) _____ Wasserko che r",
      "c) _____ Vid eo re co rde r g) _____ Min e ra lwa sse r",
      "d) _____ Mit ta ge sse n h) _____ K üh lsch ran k",
      "die Übung + s + das Buch > das Übungsbuch",
      "die Orange + n + der Saft > der Orangensaft",
      "das Kind + er + der Garten > der Kindergarten",
      "Gru n dw o rt",
      "Übung 2",
      "Bilden Sie Nomen.",
      "a) _____ Sonne + _____ Schirm > ______________________",
      "b) _____ Wohnung + _____ Tür > ______________________",
      "c) _____ Blume + _____ Vase > ______________________",
      "d) _____ Beruf + _____ Schule > ______________________",
      "e) _____ Wort + _____ Buch > ______________________",
      "hoch + das Haus > das Hochhaus",
      "Grundwort",
      "Übung 3",
      "Bilden Sie Nomen.",
      "a) schwarz + _____ Brot > _____________________________",
      "b) groß + _____ Stadt > _____________________________",
      "c) frisch + _____ Milch > _____________________________",
      "d) klein + _____Kind > _____________________________",
      "e) alt + _____ Papier > _____________________________",
      "schlafen + die Tablette > die Schlaftablette",
      "warten + das Zimmer > das Wartezimmer",
      "Grundwort",
      "Übung 4",
      "Was passt zusammen?",
      "a) waschen Wort _____________________________",
      "b) fragen Haus _____________________________",
      "c) spielen Büro _____________________________",
      "d) kaufen Maschine die Waschmaschine",
      "e) reisen Weg _____________________________",
      "f) tanzen Kurs _____________________________",
      "g) gehen Platz _____________________________"
    ],
    "id": "3.2",
    "exerciseCount": 0
  },
  {
    "lesson": 3,
    "topic": 3,
    "title": "Adjektiv",
    "pdfPage": 16,
    "lines": [
      "Ist das Auto neu? - Nein, es ist alt.",
      "Übung 1",
      "Beispiel: Buch - dick Ist das Buch dick? - Ja, es ist sehr dick.",
      "a) Haus - klein e) Laptop - teuer i) Tee - heiß",
      "b) Frage - schwierig f) Miete - hoch j) Musik - laut",
      "c) Getränke - kalt g) du - krank k) Äpfel - sauer",
      "d) Peter - faul h) Bananen - billig l) Paul und Eva - müde",
      "Übung 2",
      "Beispiel: Ist der Film interessant? - Nein, er ist lan g we i lig .",
      "a) Ist das Wasser warm? g) Ist das Auto langsam? m) Ist das Brot alt?",
      "b) Ist die Milch billig? h) Ist das Wetter gut? n) Ist der Mann alt?",
      "c) Ist die Prüfung einfach? i) Ist die Übung schwierig? o) Ist das Fahrrad alt?",
      "d) Ist Paul gesund? j) Sind die Kinder leise? p) Ist die Antwort richtig?",
      "e) Ist die Studentin faul? k) Ist der Apfel süß? q) Ist das Ei hart?",
      "f) Ist der Herr verheiratet? l) Ist die Jacke teuer? r) Bist du krank?",
      "Farben",
      "schwarz grau weiß",
      "hell- - dunkel-",
      "hellblau - dunkelblau",
      "hellrot - dunkelrot",
      "hellgrün - dunkelgrün",
      "Übung 3",
      "Beispiel: Welche Farbe hat eine Kirsche? - S ie ist ro t",
      "a) Welche Farbe hat eine Gurke? - ________________________",
      "b) Welche Farbe hat eine Banane? - ________________________",
      "c) Welche Farbe hat eine Tomate? - ________________________",
      "d) Welche Farbe hat der Ozean? - ________________________",
      "e) Welche Farbe hat Milch? - ________________________",
      "f) Welche Farbe hat Kaffee? - ________________________",
      "g) Welche Farbe hat Orangensaft? - ________________________",
      "h) Welche Farbe hat Blut? - ________________________"
    ],
    "id": "3.3",
    "exerciseCount": 0
  },
  {
    "lesson": 4,
    "topic": 1,
    "title": "Nicht trennbare und trennbare Verben",
    "pdfPage": 17,
    "lines": [
      "Nicht trennbare Verben",
      "Peter bekommt ein Schnitzel. > be kommen > nicht trennbar",
      "be-, emp-, ent-, er-, ge-, ver-, zer- sind nicht trennbar",
      "Übung 1",
      "Beispiel: besuchen - Max - die Tante Max besucht die Tante.",
      "a) bezahlen - du - die Rechnung f) genießen - du - die Freizeit",
      "b) beginnen - der Kurs - am Montag g) verstehen - ich - das Problem",
      "c) empfehlen - ich - das Steak h) vergessen - Paul - die Hausaufgabe",
      "d) entlassen - die Firma - viele Arbeiter i) verdienen - Karl - viel Geld",
      "e) erklären - Lehrer - die Grammatik j) zerreißen - Maria - die Notiz",
      "Trennbare Verben",
      "Der Zug kommt um 18.00 Uhr an. > an kommen > trennbar",
      "ab-, an-, auf-, aus-, ein-, mit-, her-, vor-, zu-, zurück- sind trennbar",
      "Übung 2",
      "Beispiel: abschließen - du - die Tür Du schließt die Tür ab.",
      "a) abfahren - der Bus - in 10 Minuten f) einladen - ich - Peter - ins Kino",
      "b) ankreuzen - du - die richtige Antwort g) herstellen - Siemens - Waschmaschinen",
      "c) aufstehen - er - um 7.00 Uhr h) vorlesen - die Studentin - das Referat",
      "d) aussteigen - ich - in Frankfurt i) zumachen - du - die Tür",
      "e) ankommen - der Zug - um 20.30 Uhr j) zurückgeben - er - das Buch",
      "Übung 3",
      "Setzen Sie die Verben ein.",
      "Beispiel: Ich rufe Anna an .",
      "abfahren ausfüllen einkaufen mitfahren einladen vorlesen zurückkommen zuhören",
      "anrufen bekommen erklären vergessen bestellen ankreuzen aussteigen",
      "a) Du _______ im Supermarkt _____. i) Jana _____ den Kindern eine Geschichte ____.",
      "b) Wir _______ morgen nicht nach München ____. j) Ich _________ Tee mit Zitrone.",
      "c) Ich ______ dich zum Essen ____. k) Nadja _______ morgen aus Rumänien ______.",
      "d) Klaus ___________ morgen Besuch. l) Wir _________ die richtige Antwort ____.",
      "e) Der Zug ________ in fünf Minuten _____. m) Der Lehrer _______ die Grammatik.",
      "f) Wir ________ dem Lehrer im Deutschkurs ___. n) Eva __________ oft Termine.",
      "g) Paul _______ an der nächsten Station ____. o) Maria ________ das Formular _____."
    ],
    "id": "4.1",
    "exerciseCount": 0
  },
  {
    "lesson": 4,
    "topic": 2,
    "title": "Nomen und Artikel - Akkusativ",
    "pdfPage": 18,
    "lines": [
      "Viele Verben haben ein Akkusativobjekt.",
      "Elena isst den Kuchen.",
      "Subjekt Prädikat Objekt / Akkusativ",
      "Bestimmte Artikel",
      "Subjekt Prädikat Objekt (Akk.)",
      "Elena isst den Kuchen. maskulin den",
      "Paul kennt die Lehrerin. feminin die",
      "Ich trinke das Mineralwasser. neutral das",
      "Wir lesen die Bücher. Plural die",
      "Übung 1",
      "Beispiel: Lehrer - fragen Ich frage den Lehrer.",
      "a) Koffer - packen d) Miete - bezahlen g) Termin - aufschreiben j) Text - vorlesen",
      "b) Fenster - schließen e) Problem - verstehen h) Schuhe - anziehen k) Kollegin - anrufen",
      "c) Freunde - treffen f) Leute - kennen i) Formular - ausfüllen l) Handy - aufladen",
      "Unbestimmte Artikel",
      "Subjekt Prädikat Objekt (Akk.)",
      "Ich esse einen Salat. maskulin einen",
      "Du bestellst eine Suppe. feminin eine",
      "Eva hat ein E-Bike. neutral ein",
      "Wir kaufen Orangen. Plural --",
      "Übung 2",
      "Akkusativobjekt",
      "Beispiele: fragen Du fragst (b) den Lehrer (b) > bestimmt",
      "nehmen Ich nehme (u) einen Tomatensalat. (u) > unbestimmt",
      "a) besuchen Du ___________ (b) _____ Großvater.",
      "b) bezahlen Ihr ___________ (b) _____ Fahrkarte.",
      "c) buchen Maria ___________ (u) _____ Reise.",
      "d) braten Karl ___________ (u) _____ Steak.",
      "e) kennen Ich ___________ (b) _____ Professor.",
      "f) kaufen Ihr ___________ (u) _____ Deutschbuch.",
      "g) lernen Wir ___________ (b) _____ Wörter.",
      "h) brauchen Du ___________ (u) _____ Wörterbuch.",
      "i) trinken Ich ___________ (u) _____ Orangensaft.",
      "j) verstehen Er ___________ (b) _____ Wort nicht.",
      "k) zählen Wir ___________ (b) _____ Stühle.",
      "l) bestellen Er ___________ (u) _____ Mineralwasser.",
      "m) lesen Du ___________ (b) _____ Zeitung.",
      "n) essen Ich ___________ (u) _____ Erdbeeren.",
      "o) sehen Du ___________ (u) _____ Film.",
      "p) tragen Eva ___________ (b) _____ Tasche.",
      "q) treffen Ich ___________ (b) _____ Freunde.",
      "r) haben Du ___________ (u) _____ Sonnenbrille.",
      "s) machen Sie ___________ (b) _____ Hausaufgabe.",
      "bestimmter Artikel - unbestimmter Artikel - kein Artikel",
      "Kaufst du den Mantel hier? - Ja, ich kaufe den Mantel. > definiert > bestimmter Artikel",
      "Trinkst du eine Tasse Tee? - Ja, ich trinke eine Tasse Tee. > nicht definiert, Menge > unbestimmter Artikel",
      "Isst du gern Gemüse? - Ja, ich esse gern Gemüse. > Speisen / Getränke allgemein > oft kein Artikel",
      "Isst du gerne Kuchen? - Hast du einen Kuchen für mich? - Ja, der Kuchen ist von meiner Mutter.",
      "Ich esse einen Apfel. - Was isst du? - Einen Apfel esse ich.",
      "S P O O P S",
      "Mengen Tee > eine Tasse Tee Toast > eine Scheibe Toast Schokolade > eine Tafel Schokolade",
      "Milch > ein Glas Milch Kuchen > ein Stück Kuchen Apfelsaft > eine Flasche Apfelsaft",
      "Übung 3",
      "Beispiele: Erdnüsse Ich esse Erdnüsse - Was isst du? - Erdnüsse esse ich.",
      "ein Glas Wasser Ich trinke ein Glas Wasser. - Was trinkst du? - Ein Glas W asser trinke ich.",
      "der Text hier Ich lese den Text hier. - Was liest du? - Den Text hier lese ich.",
      "a) ein Kotelett d) die Zeitung hier g) ein Stück Kuchen j) Orangensaft",
      "b) eine Tasse Kaffee e) Trauben h) der Döner hier k) der Salat hier",
      "c) die Banane hier f) ein Teller Suppe i) eine Portion Eis l) eine Tafel Schokolade",
      "Artikel - Negation",
      "Möchtest du einen Apfelsaft? Nein, ich möchte jetzt keinen Apfelsaft. maskulin keinen",
      "Isst du eine Gemüsesuppe? Nein, ich esse jetzt keine Gemüsesuppe. feminin keine",
      "Kaufst du ein Notebook? Nein, ich kaufe jetzt kein Notebook. neutral kein",
      "Hast du Probleme? Nein, ich habe jetzt keine Probleme. Plural keine",
      "Übung 4",
      "Beispiel: Tee Trinkst du Tee? - Nein danke, ich trinke jetzt keinen Tee.",
      "a) ein Stück Kuchen e) ein Steak i) ein Sandwich m) ein Apfel",
      "b) ein Eis f) Kirschsaft j) Mineralwasser n) Erdbeeren",
      "c) eine Pizza g) eine Orange k) eine Kiwi o) Milchkaffee",
      "d) Pommes h) Erdnüsse l) Gurkensalat p) ein Burger",
      "haben",
      "Ich habe einen Wagen.",
      "Du hast einen Wagen.",
      "Lena hat einen Wagen.",
      "Theo hat einen Wagen.",
      "Wir haben einen Wagen.",
      "Ihr habt einen Wagen.",
      "Max und Paul haben einen Wagen.",
      "Übung 5",
      "Beispiel: Uhr - ich Leider habe ich keine Uhr.",
      "a) Urlaub - ihr c) Garten - wir e) Auto - du g) E-Bike - ihr",
      "b) Notebook - du d) Zeit - Lena f) Stift - ich h) Informationen - Theo"
    ],
    "id": "4.2",
    "exerciseCount": 0
  },
  {
    "lesson": 4,
    "topic": 3,
    "title": "Personalpronomen - Akkusativ",
    "pdfPage": 20,
    "lines": [
      "„Hallo Anna! Besuchst du Peter?“ „Ja, ich besuche ihn.“",
      "„Kennst du Maria?“ „Ja, ich kenne sie.“",
      "Isst du den Kuchen hier? - Ja, ich esse ihn. maskulin",
      "Trinkst du die Milch hier? - Ja, ich trinke sie. feminin",
      "Liest du das Buch hier? - Ja, ich lese es. neutral",
      "Kaufst du die Erdbeeren hier? - Ja, ich kaufe sie. Plural",
      "Übung 1",
      "Beispiel: „Wer bekommt das Steak?“ - „Ich bekomme es .“",
      "a) „Wer bekommt ______ Suppe?“ - „Ich bekomme _____.“",
      "b) „Wer bekommt ______ Salat?“ - „Ich bekomme _____.“",
      "c) „Wer bekommt ______ Kotelett?“ - „Ich bekomme _____.“",
      "d) „Wer bekommt ______ Eis?“ - „Ich bekomme _____.“",
      "e) „Wer bekommt ______ Kaffee?“ - „Ich bekomme _____.“",
      "Nominativ ich du er sie es wir ihr sie, Sie",
      "Akkusativ mich dich ihn sie es uns euch sie, Sie",
      "Übung 2",
      "Subjekt Objekt (Akk.) Subjekt Objekt (Akk.)",
      "Beispiel: Ich kenne Maria, aber sie kennt mich nicht.",
      "a) Du kennst den Professor, aber _____ kennt _______ nicht.",
      "b) Maria kennt den Lehrer, aber _____ kennt _____ nicht.",
      "c) Wir kennen Arnold Schwarzenegger, aber _____ kennt _____ nicht.",
      "d) Ihr kennt mich, aber _____ kenne ______ nicht.",
      "e) Das Mädchen kennt Paul, aber _____ kennt ____ nicht.",
      "f) Herr Meier kennt Frau Schneider, aber _____ kennt _____ nicht.",
      "g) Frau Berg kennt dich, aber _____ kennst _____ nicht.",
      "Übung 3",
      "Beispiel: der Kaffee - Trinken Sie den Kaffee hier? - Nein, ich trinke ihn nicht.",
      "a) _____ Salat d) _____ Bier g) _____ Zeitung j) _____ Tee",
      "b) _____ Sandwich e) _____ Erdbeeren h) _____ Mineralwasser k) _____ Buch",
      "c) _____ Milch f) _____ Apfelsaft i) _____ Suppe l) _____ Kuchen",
      "Übung 4",
      "Beispiel: Kaffee - Mögen Sie Kaffee ? - Nein, ich mag keinen Kaffee .",
      "a) Erdbeereis c) Tomatensuppe e) Schokolade g) Salami",
      "b) Kakao d) Apfelsaft f) Bier h) Pommes"
    ],
    "id": "4.3",
    "exerciseCount": 0
  },
  {
    "lesson": 5,
    "topic": 1,
    "title": "Possessivartikel",
    "pdfPage": 21,
    "lines": [
      "Ist das deine Kamera? - Ja, das ist meine Kamera.",
      "maskulin feminin neutral Plural",
      "Nominativ mein meine mein meine",
      "Akkusativ meinen meine mein meine",
      "Übung 1",
      "Beispiele: Mein Wohnzimmer ist ziemlich klein. Ich besuche meinen Onkel.",
      "Subjekt Akkusativobjekt",
      "a) Ich bringe ___________ Fahrrad in die Garage. h) Ich suche ___________ Socken.",
      "b) ___________ Onkel fährt morgen nach Köln. i) Ich möchte ___________ Computer verkaufen.",
      "c) Ich treffe morgen ___________ Kollegin. j) ___________ Freundin sucht einen Job.",
      "d) Ich muss ___________ Zimmer aufräumen. k) ___________ Rucksack liegt hier.",
      "e) ___________ Eltern fahren in Urlaub. l) Ich muss ___________ Schuhe putzen.",
      "f) ___________ Bleistift ist weg. m) Ich finde ___________ Kugelschreiber nicht.",
      "g) Ich will ___________ Großvater einladen. n) ___________ Auto ist sehr teuer.",
      "Ich habe ein Fahrrad. Das ist mein Fahrrad.",
      "Du hast eine Uhr. Das ist deine Uhr.",
      "Peter hat einen Computer. Das ist sein Computer.",
      "Anna hat ein Tablet. Das ist ihr Tablet.",
      "Das Kind trägt eine Mütze. Das ist seine Mütze.",
      "Wir haben eine Wohnung. Das ist unsere Wohnung.",
      "Ihr habt ein Auto. Das ist euer Auto.",
      "Die Gäste holen das Gepäck. Das ist ihr Gepäck.",
      "Achtung!",
      "maskulin feminin neutral Plural",
      "Nominativ euer eure euer eure",
      "Akkusativ euren eure euer eure",
      "Übung 2",
      "Beispiel: Ich besuche meine Tante.",
      "a) Wir besuchen ___________ Eltern. h) Sie treffen ___________ Freunde.",
      "b) Paul fragt ___________ Vater. i) Wir räumen ___________ Wohnung auf.",
      "c) Eva sieht morgen ___________ Onkel. j) Max zählt ___________ Geld.",
      "d) Ihr ladet ___________ Tante ein. ! [e] k) Eva trifft heute Abend ___________ Geschwister.",
      "e) Du räumst ___________ Zimmer auf. l) Kennst du ___________ Nachbarin?",
      "f) Trifft Amira ___________ Freundin? m) Wir holen ___________ Gepäck.",
      "g) Besucht ihr ___________ Großvater? ! [e] n) Ihr bezahlt ___________ Rechnung. ! [e]"
    ],
    "id": "5.1",
    "exerciseCount": 0
  },
  {
    "lesson": 5,
    "topic": 2,
    "title": "Präteritum (Imperfekt) - haben / sein",
    "pdfPage": 22,
    "lines": [
      "haben sein",
      "ich hatte ich war",
      "du hattest du warst",
      "er / sie / es hatte er / sie / es war",
      "wir hatten wir waren",
      "ihr hattet ihr wart",
      "sie / Sie hatten sie/ Sie waren",
      "Übung 1",
      "Beispiel: Hatte er keine Zeit?",
      "a) _______ du gestern im Kino? g) _______ du krank?",
      "b) _______ ihr Besuch? h) _______ Sie letzte Woche in Köln?",
      "c) _______ er in Urlaub? i) _______ der Film interessant?",
      "d) _______ du Urlaub? j) _______ ihr schon in der neuen Disko?",
      "e) _______ ihr mit dem Essen zufrieden? k) _______ du viel Arbeit?",
      "f) _______ Sie Probleme? l) _______ du schon bei Klaus?"
    ],
    "id": "5.2",
    "exerciseCount": 0
  },
  {
    "lesson": 5,
    "topic": 3,
    "title": "Zeitadverbien",
    "pdfPage": 22,
    "lines": [
      "nie kaum manchmal oft meistens immer",
      "niemals sehr selten ab und zu häufig fast immer ständig",
      "fast nie hin und wieder zumeist",
      "Übung 2",
      "Beantworten Sie die Fragen.",
      "Beispiele: Trinkst du keinen Tee? - oft - Doch, ich trinke oft Tee.",
      "Trinkst du keinen Kaffee? - nie - Nein, ich trinke nie Kaffee.",
      "Trinkst du Cola? - manchmal - Ja, ich trinke manchmal Cola.",
      "a) Gehst du manchmal ins Kino? > ab und zu h) Spielst du Karten? > hin und wieder",
      "b) Isst du kein Obst? > oft i) Fährst du nie mit dem Fahrrad? > nie",
      "c) Spielst du oft Fußball? > selten j) Isst du nie Fleisch? > oft",
      "d) Kaufst du keinen Käse? > manchmal k) Fährst du nie mit dem Bus? > ab und zu",
      "e) Hörst du zu Hause Musik? > ständig l) Gehst du oft in die Disko? > fast nie",
      "f) Trinkst du keinen Alkohol? > nie m) Liest du immer die Zeitung? > kaum",
      "g) Gehst du oft ins Café? > kaum n) Lernst du die Wörter nicht? > immer",
      "Übung 3",
      "Beispiel: kaufen - Wein Kaufst du manchmal Wein? - Ja, ich kaufe hin und wieder Wein.",
      "a) fahren - mit dem Bus d) trinken - Bier g) reisen - nach Spanien",
      "b) essen - Obst e) lesen - Zeitung h) bestellen - Tee",
      "c) tragen - Jeans f) nehmen - Whisky i) fliegen - in Urlaub"
    ],
    "id": "5.3",
    "exerciseCount": 0
  },
  {
    "lesson": 6,
    "topic": 1,
    "title": "Nomen und Artikel - Dativ",
    "pdfPage": 23,
    "lines": [
      "bestimmte Artikel",
      "Subjekt Prädikat Objekt (Dativ)",
      "Ich danke dem Großvater. maskulin dem",
      "Du antwortest der Reporterin. feminin der",
      "Er hilft dem Mädchen. neutral dem",
      "Wir helfen den Leuten. Plural den -n",
      "unbestimmte Artikel",
      "Subjekt Prädikat Objekt (Dativ)",
      "Ich danke einem Freund. maskulin einem",
      "Du antwortest einer Journalistin. feminin einer",
      "Er gratuliert einem Mädchen. neutral einem",
      "Wir helfen Leuten. Plural -- -n",
      "Übung 1",
      "Subjekt: Person Dativobjekt: Person",
      "Beispiel: helfen Du hilfs t dem Onkel",
      "a) antworten Paul __________ _____ Professor.",
      "b) danken Er __________ _____ Tante.",
      "c) glauben Ich __________ _____ Reporterin.",
      "d) gratulieren Du __________ _____ Onkel.",
      "e) vertrauen Er __________ _____ Großvater.",
      "f) verzeihen Ich __________ _____ Freund.",
      "g) zuhören Der Student __________ _____ Professorin ____.",
      "Übung 2",
      "Subjekt: Sache (unpers.) Dativobjekt: Person",
      "Beispiel: gehören Das Haus gehör t dem Onkel.",
      "a) schmecken Das Eis __________ _____ Kindern.",
      "b) gehören Das Buch __________ _____ Lehrer.",
      "c) gefallen Die Musik __________ _____ Studentin",
      "d) passen Die Jacke __________ _____ Mädchen.",
      "Position I Position II Position III",
      "Das Essen schmeckt den Leuten",
      "Den Leuten schmeckt das Essen",
      "Übung 3",
      "Bilden Sie Sätze mit gehören - schmecken - gefallen.",
      "Beispiel: Haus - Onkel Das Haus gehört dem Onkel oder Dem Onkel gehört das Haus .",
      "a) Pizza - Kinder d) Wein - Gäste g) Bücher - Studenten",
      "b) Jacke - Großvater e) Wagen - Chef h) Erdbeeren - Mädchen",
      "c) Film - Studentin f) Hund - Nachbarin i) Bilder - Touristen"
    ],
    "id": "6.1",
    "exerciseCount": 0
  },
  {
    "lesson": 6,
    "topic": 2,
    "title": "Pronomen - Dativ",
    "pdfPage": 24,
    "lines": [
      "Personalpronomen",
      "Maria telefoniert mit Robert.",
      "Hört Maria Robert zu?",
      "Ja, sie hört ihm zu.",
      "Hört Robert Maria zu?",
      "Ja, er hört ihr zu.",
      "Nominativ ich du er sie es wir ihr sie, Sie",
      "Akkusativ mich dich ihn sie es uns euch sie, Sie",
      "Dativ mir dir ihm ihr ihm uns euch ihnen, Ihnen",
      "Glaubst du mir? - Ja, ich glaube dir. / Glaubst du uns? - Ja, ich glaube euch.",
      "Übung 1",
      "Beispiel: Glaubst du der Studentin? Nein, ich glaube ihr nich t.",
      "a) Antwortest du Peter? d) Glaubst du Max und Maria? g) Verzeihst du uns?",
      "b) Dankst du den Leuten? e) Hörst du uns zu? h) Gratulierst du Maria?",
      "c) Vertraust du Eva? f) Hilfst du Paul? i) Hörst du Klaus zu?",
      "Aussagesatz: - Der Film gefällt dir. > Subjekt - Prädikat - Dativobjekt",
      "- Dir gefällt der Film. > Dativobjekt - Prädikat - Subjekt",
      "Fragesatz: [ - Gefällt der Film dir? > Prädikat - Subjekt - Dativobjekt ]",
      "- Gefällt dir der Film? > Prädikat - Dativobjekt - Subjekt > oft Pronomen vor Nomen",
      "- Gefällt er dir? > Prädikat - Subjekt (Personalpronomen) - Dativobjekt",
      "Übung 2",
      "Beispiele: Maria - Wein Schmeckt Maria der Wein? - Ja, er schmeckt i hr ziemlich gut .",
      "DATIVOBJEKT SUBJEKT SUBJEKT DATIVOBJEKT",
      "Max - Pommes Schmecken Max die Pommes? - Ja, sie schmecken i hm ziemlich gut .",
      "DATIVOBJEKT SUBJEKT SUBJEKT DATIVOBJEKT",
      "a) euch - Suppe c) dir - Steak e) Robert - Schnitzel g) dir - Fisch",
      "b) Julia - Erdnüsse d) Ihnen - Salat f) euch - Trauben h) Kindern - Eis",
      "Fragewort",
      "Subjekt Objekt/Dat. Dativ Subjekt",
      "Das Buch gehört dem Professor. Wem gehört das Buch? - Es gehört dem Professor.",
      "- Dem Professor gehört es.",
      "Übung 3",
      "Beispiel: Haus - Onkel Wem gehört das Haus? - Dem Onkel gehört es.",
      "a) Rucksack - Touristin d) Brief - ich g) Handschuhe - du",
      "b) Kamera - Reporter e) Tasche - Tante h) Bücher - wir",
      "c) Tablet - Mädchen f) Auto - Lehrer i) Fahrräder - Studentinnen"
    ],
    "id": "6.2",
    "exerciseCount": 0
  },
  {
    "lesson": 6,
    "topic": 3,
    "title": "Imperativ",
    "pdfPage": 25,
    "lines": [
      "Singular: Bitte, komm! Bitte, warte! Bitte, lies!",
      "Plural: Bitte, kommt! Bitte, wartet! Bitte, lest!",
      "Singular und Plural: Bitte, kommen Sie! Bitte, warten Sie! Bitte, lesen Sie!",
      "Übung 1",
      "Infinitiv informell / Singular informell / Plural offiziell",
      "Beispiel: gehen Geh ! Geh t! Gehen Sie !",
      "a) fragen _________ _________ ___________",
      "b) kaufen _________ _________ ___________",
      "c) arbeiten _________ _________ ___________ !",
      "d) antworten _________ _________ ___________ !",
      "e) reden _________ _________ ___________ !",
      "f) laufen _________ _________ ___________",
      "g) fahren _________ _________ ___________",
      "h) schlafen _________ _________ ___________",
      "i) geben __________ _________ ___________ !",
      "j) sprechen _________ _________ ___________ !",
      "k) essen _________ _________ ___________ !",
      "l) nehmen _________ _________ ___________ !",
      "m) sein _________ _________ ___________ !",
      "Übung 2",
      "Beispiel: Bitte, ergänzen Sie die Sätze, Herr Peters! (ergänzen)",
      "a) Maria, ________ bitte die Tasche! (nehmen)",
      "b) Carlos und Peter, ________ bitte nicht so laut. (sprechen)",
      "c) Claudia, _________ Max bitte das Besteck! (geben)",
      "d) Herr Meier, _____________ bitte das Paket! (holen)",
      "e) Klaus, ______ nicht so schnell! (essen)",
      "f) Robert, _______ bitte leise! (sein)",
      "g) _______ bitte 5 Minuten, Julia! (warten)",
      "Übung 3",
      "Beispiel: Ich habe Durst. (ein Bier - trinken) Dann trink ein Bier !",
      "a) Ich bin müde. (zu Bett - gehen)",
      "b) Ich habe Kopfschmerzen. (eine Tablette - nehmen)",
      "c) Ich arbeite zu viel. (Urlaub - machen)",
      "d) Ich habe Hunger. (ein Käsebrot - essen)",
      "e) Ich habe Zahnschmerzen. (zum Zahnarzt - gehen)",
      "Halt! Bleiben Sie hier!",
      "Übung 4",
      "Beispiel: herkommen > Komm her ! Kommt her! Kommen Sie her!",
      "a) anrufen >",
      "b) einsteigen >",
      "c) zuhören >",
      "d) ankreuzen >",
      "e) vorlesen >"
    ],
    "id": "6.3",
    "exerciseCount": 0
  },
  {
    "lesson": 7,
    "topic": 1,
    "title": "Satzstrukturen - Aussagesatz",
    "pdfPage": 26,
    "lines": [
      "Ergänzen Sie die Sätze.",
      "Subjekt Prädikat",
      "Klaus schläft",
      "Subjekt Prädikat Objekt / Dativ",
      "Der Schirm gehört der Kollegin.",
      "Objekt / Dativ Prädikat Subjekt",
      "gehört .",
      "Subjekt Prädikat lokal",
      "Der Bus fährt zum Rathaus",
      "lokal Prädikat Subjekt",
      "fährt .",
      "Subjekt Prädikat temporal",
      "Ich verreise nächste Woche.",
      "temporal Prädikat Subjekt",
      ".",
      "Subjekt Prädikat Objekt / Dativ modal",
      "Du hilfst den Kollegen gerne.",
      "modal Prädikat Subjekt Objekt / Dativ",
      "Objekt / Dativ Prädikat Subjekt modal",
      ".",
      "Subjekt Prädikat temporal lokal",
      "Mein Onkel fliegt am Montag nach Malta.",
      "temporal Prädikat Subjekt lokal",
      "fliegt .",
      "lokal Prädikat Subjekt temporal",
      "fliegt .",
      "Subjekt Prädikat temporal Objekt / Akkusativ lokal",
      "Max trifft jeden Freitag seine Freunde in der Kneipe.",
      "Objekt / Akkusativ Prädikat Subjekt temporal lokal",
      ".",
      "lokal Prädikat Subjekt temporal Objekt / Akkusativ",
      "trifft .",
      "temporal Prädikat Subjekt Objekt / Akkusativ lokal",
      "."
    ],
    "id": "7.1",
    "exerciseCount": 0
  },
  {
    "lesson": 7,
    "topic": 2,
    "title": "Modalverben",
    "pdfPage": 27,
    "lines": [
      "Position II Position II",
      "Paul arbeitet am Sonntag. Eva besucht die Tante.",
      "Position II Ende Position II Ende",
      "Robert muss auch am Sonntag arbeiten. Julia will auch die Tante besuchen.",
      "können dürfen müssen sollen wollen mögen / möchten",
      "ich kann darf muss soll will mag / möchte",
      "du kannst darfst musst sollst willst magst / möchtest",
      "er / sie / es kann darf muss soll will mag / möchte",
      "wir können dürfen müssen sollen wollen mögen / möchten",
      "ihr könnt dürft müsst sollt wollt mögt / möchtet",
      "sie / Sie können dürfen müssen sollen wollen mögen / möchten",
      "Ich mag Erdbeeren. (generell)",
      "Ich möchte Erdbeeren essen. (aktueller Wunsch)",
      "Trennbare Verben: Eva steigt jetzt ein > Eva muss jetzt einsteigen.",
      "Übung 1",
      "Bilden Sie Sätze mit Modalverben.",
      "wollen a) Wir kommen nicht mit. dürfen a) Robert geht nicht aus.",
      "b) Ihr steht nicht früh auf. b) Ihr kommt nicht mit.",
      "c) Du triffst Klaus nicht. c) Ich rauche nicht mehr.",
      "d) Ich esse den Kuchen nicht. d) Kinder trinken keinen Alkohol.",
      "e) Eva trinkt kein Bier. e) Du isst keinen Zucker.",
      "können a) Julia versteht den Satz nicht. müssen a) Carlos lernt die Wörter.",
      "b) Du trägst den Koffer nicht. b) Ihr kauft noch ein.",
      "c) Carlos läuft sehr schnell. c) Ich nehme das Medikament.",
      "d) Ich schlafe nicht ein. d) Paul repariert das Fahrrad.",
      "e) Wir sehen euch nicht. e) Wir warten lange.",
      "Übung 2",
      "Beispiel: Spielst du ...? - Ja, ich kann ...",
      "- Nein, ich kann nicht ...",
      "a) Schach",
      "b) Tischtennis",
      "c) Karten",
      "d) Theater",
      "e) Roulette",
      "f) Geige",
      "g) Golf",
      "h) Fußball"
    ],
    "id": "7.2",
    "exerciseCount": 0
  },
  {
    "lesson": 7,
    "topic": 3,
    "title": "Präpositionen mit Dativ",
    "pdfPage": 28,
    "lines": [
      "Präposition Bedeutung Beispiele",
      "Ort aus München, aus Tunesien",
      "aus",
      "Material aus Glas",
      "Ort bei meinen Eltern, bei Hamburg",
      "bei",
      "Zeit bei Nacht",
      "Art und Weise mit dir, mit Glück",
      "mit",
      "Instrument mit dem Auto, mit einem Messer",
      "seit Zeit seit einem Jahr",
      "Ort nach Köln, nach Italien",
      "nach",
      "Zeit nach dem Konzert",
      "Ort von der Universität, von dort",
      "von",
      "Täter von dir, von einem Freund",
      "zu Ort zu Paul, zu Hause",
      "gegenüber Ort dem Hotel gegenüber (nachgestellt)",
      "Manchmal sind diese Präpositionen mit dem Artikel verbunden:",
      "beim > bei dem vom > von dem zum > zu dem zur > zu der",
      "Übung 1",
      "Ergänzen Sie die Endungen.",
      "a) Paul fährt mit d____ Taxi nach Hause. g) Peter wohnt bei d____ Eltern.",
      "b) Maria wohnt seit ein____ Jahr in Wien. h) Eva arbeitet seit ein____ Woche in Bonn.",
      "c) Ich hole das Paket von d____ Post ab. i) Klaus nimmt die Jacke aus d____ Schrank.",
      "d) Wann gehst du morgens aus d____ Haus? j) Nach d____ Arbeit besucht er Maria.",
      "e) Wohin gehst du nach d____ Essen? k) Das Hotel liegt d____ Bahnhof gegenüber.",
      "f) Hol bitte den Wein aus d____ Keller! l) Max wohnte lange bei sein____ Tante.",
      "Übung 2",
      "Ergänzen Sie eine Präposition mit Dativ.",
      "a) Paul geht _______ dem Hund spazieren. h) Ich bringe dich _______ Bahnhof.",
      "b) Diese Tomaten kommen _______ Spanien. i) Maria wohnt _______ ihren Eltern.",
      "c) Ich wohne _______ drei Monaten in Passau. j) Sie fährt _______ dem Taxi nach Hause.",
      "d) Die Tankstelle liegt dem Parkhaus ____________. k) Wir holen unsere Tante _______ Bahnhof ab.",
      "e) Wie viel Geld hast du _______ dir? l) Heute Nachmittag gehe ich _______ Klaus.",
      "f) Kannst du mich _______ Flughafen abholen? m) _______ Regen mag ich nicht joggen.",
      "g) Maria will nicht _______ mir in Urlaub fahren. n) _______ wem ist das Geschenk?",
      "Übung 3",
      "Beispiel: Gehst du zu Klaus? - Nein, ich gehe nicht zu ihm .",
      "a) Kommst du von Julia? e) Lernst du mit den Studentinnen?",
      "b) Telefonierst du mit dem Großvater? f) Fährst du zu Frau Berg?",
      "c) Sprichst du mit der Sekretärin? g) Wohnst du bei deinen Eltern?",
      "d) Sind die Blumen von Max? h) Ist das Geschenk von Christian?"
    ],
    "id": "7.3",
    "exerciseCount": 0
  },
  {
    "lesson": 8,
    "topic": 1,
    "title": "Perfekt",
    "pdfPage": 29,
    "lines": [
      "Perfekt - schwache Verben",
      "Präsens: Ich kaufe ein Eis. Ein Unfall passiert mir.",
      "Perfekt: Ich habe ein Eis gekauft. Ein Unfall ist mir passiert.",
      "Infinitiv kauf-en arbeit-en telefonier-en reis-en",
      "Partizip II ge-kauf-t ge-arbeit-et telefonier-t ge-reis-t",
      "Ich habe gekauft. Ich habe gearbeitet. Ich habe telefoniert. Ich bin gereist.",
      "Verben auf -ieren > kein ge",
      "Position II ENDE Position II ENDE",
      "Perfekt > haben Partizip II Perfekt > sein Partizip II",
      "ich habe ge k a uf t ich bin ge re is t",
      "du hast ge k a uf t du bist ge re is t",
      "er / sie / es hat ge k a uf t er / sie / es ist ge re is t",
      "wir haben ge k a uf t wir sind ge re is t",
      "ihr habt ge k a uf t ihr seid ge re is t",
      "sie haben ge k a uf t sie sind ge re is t",
      "Übung 1",
      "Beispiel: kaufen - du - den Wagen Du ha s t den Wagen ge ka uft .",
      "a) wohnen - er - in Köln g) spielen - sie - Fußball m) korrigieren - du - den Text",
      "b) lernen - Eva - Arabisch h) sagen - Max - kein Wort n) gratulieren - wir - ihm",
      "c) suchen - er - seine Brille i) passen - die Jacke - mir nicht o) studieren - Lisa - Informatik",
      "d) holen - du - Bier aus dem Keller j) warten - wir - auf den Bus p) reisen - Paul - nach Japan",
      "e) buchen - wir - einen Flug k) antworten - du - der Reporterin q) passieren - ein Unfall",
      "f) danken - ihr - euren Freunden l) mieten - Eva und Max - ein Auto r) starten - das Flugzeug - schon",
      "Perfekt - starke Verben",
      "Präsens: Julia spricht mit Klaus. Max geht ins Kino.",
      "Perfekt: Julia hat mit Klaus gesprochen. Max ist ins Kino gegangen.",
      "sprech-en geh-en",
      "ge-sproch-en ge-gang-en",
      "ich habe ge s proc h en ich bin ge ga ng en",
      "du hast ge s proc h en du bist ge ga ng en",
      "er / sie / es hat ge s proc h en er / sie / es ist ge ga ng en",
      "wir haben ge s proc h en wir sind ge ga ng en",
      "ihr habt ge s proc h en ihr seid ge ga ng en",
      "sie haben ge s proc h en sie sind ge ga ng en",
      "Übung 2",
      "Beispiel: Wann trinkst du den Tee? - Ich habe ihn schon getrunken .",
      "a) Wann triffst du Carmen? e) Wann hilfst du Paul?",
      "b) Wann wäschst du den Pullover? f) Wann schließt du das Fenster?",
      "c) Wann liest du die Zeitung? g) Wann schneidest du die Zwiebel?",
      "d) Wann isst du den Kuchen? h) Wann schreibst du Eva und Maria?",
      "Übung 3",
      "Beispiel: was - trinken Was hast du getrunken?",
      "a) was - nehmen g) was - lesen m) wann - kommen !",
      "b) was - finden h) wen - sehen n) wohin - fahren !",
      "c) wem - helfen i) was - essen o) wohin - fliegen !",
      "d) wie lange - schlafen j) wohin - gehen ! p) wo - sitzen !!",
      "e) was - tragen k) wie lange - bleiben ! q) wo - stehen !!",
      "f) wem - schreiben l) wohin - laufen ! r) wo - liegen !!",
      "Perfekt - gemischte Verben",
      "Präsens: Das weiß ich nicht.",
      "Perfekt: Das habe ich nicht gewusst.",
      "bring-en",
      "ge-brach-t",
      "bringen - gebracht brennen - gebrannt senden - gesandt",
      "denken - gedacht kennen - gekannt wenden - gewandt",
      "wissen - gewusst nennen - genannt",
      "rennen - gerannt (ist)",
      "Übung 4",
      "Beispiel: das Paket - bringen Hast du das Paket ge b r a ch t ?",
      "a) die Adresse - nennen c) Paul eine E-Mail - senden e) an die Verabredung - denken",
      "b) die Antwort - wissen d) die Journalistin - kennen f) auf die Straße - rennen !",
      "Perfekt - nicht trennbare und trennbare Verben",
      "schwach stark gemischt",
      "besuch-en verlier-en erkenn-en",
      "besuch-t verlor-en erkann-t",
      "nicht trennbare Verben > ohne ge",
      "Achtung: Bei nicht trennbaren starken Verben > Infinitiv und Partizip II z. T. gleich, z. B. erfahren > erfahren",
      "Übung 5",
      "Beispiel: bestellen Du hast etwas b est e ll t .",
      "a) erklären c) empfehlen e) bekommen g) erwarten",
      "b) genießen d) verlieren f) zerbrechen h) vergessen",
      "schwach stark gemischt",
      "auf-mach-en an-komm-en mit-bring-en",
      "auf-ge-mach-t an-ge-komm-en mit-ge-brach-t",
      "trennbare Verben > ge nach dem Präfix",
      "Übung 6",
      "Beispiel: einkaufen - etwas Du hast etwas e in ge kau f t .",
      "a) zuhören - mir c) mitbringen - etwas e) aufwecken - mich g) aufstehen - gerade",
      "b) anrufen - mich d) einladen - mich f) zurückgeben - etwas h) einsteigen - ins Taxi"
    ],
    "id": "8.1",
    "exerciseCount": 0
  },
  {
    "lesson": 8,
    "topic": 2,
    "title": "Konjunktionen",
    "pdfPage": 31,
    "lines": [
      "Sandra ist Studentin. Sie wohnt in Wien. und Aufzählung",
      "Sandra ist Studentin[,] und [sie] wohnt in Wien. 2. Satz mit Subjekt > (Komma möglich)",
      "Clara muss den Bus erreicht. Dann muss sie nicht zu Fuß gehen. oder Alternative",
      "Clara muss den Bus erreichen[,] oder [sie muss] zu Fuß gehen. 2. Satz mit Subjekt > (Komma möglich)",
      "Max hat heute viel Zeit. Früher hatte er immer Stress. aber Gegensatz",
      "Max hat heute viel Zeit, aber früher hatte er immer Stress. 2. Satz > Gegensatz zu 1. Satz",
      "Ich kann dich besuchen. Heute habe ich keine Zeit. aber Einschränkung",
      "Ich kann dich besuchen, aber heute habe ich keine Zeit. 2. Satz > Einschränkung von 1. Satz",
      "Paul wohnt nicht in Köln. Er wohnt nämlich in Bonn. sondern Korrektur",
      "Paul wohnt nicht in Köln, sondern [er wohnt] in Bonn. 2. Satz korrigiert negativen 1. Satz",
      "Eva läuft zur Bushaltestelle. Der Bus kommt in zwei Minuten. denn Begründung",
      "Eva läuft zur Bushaltestelle, denn der Bus kommt schon. 2. Satz begründet 1. Satz (warum?)",
      "I II 0 I II",
      "Monika spielt sehr gut Tennis, denn sie trainiert jeden Tag.",
      "Aussagesatz, denn Aussagesatz",
      "Übung 1",
      "Verbinden Sie die zwei Aussagesätze.",
      "a) Sie fliegen nicht nach Kreta. Ihre Mutter liegt im Krankenhaus.",
      "b) Paul fährt nicht zu Klaus. Er fährt zu Maria.",
      "c) Ich möchte dich einladen. Du hast keine Zeit.",
      "d) Lisa besucht mich vielleicht am Montag. Vielleicht besucht sie mich am Dienstag.",
      "e) Werner ist Journalist. Er arbeitet bei einer Tageszeitung.",
      "f) Maria bestellt keinen Wein. Sie bestellt Bier.",
      "g) Wir gehen nicht ins Kino. Wir gehen ins Theater.",
      "h) Er geht in den Keller. Er holt eine Flasche Wein.",
      "i) Wir wollen Lisa besuchen. Sie hat morgen Geburtstag.",
      "j) Er will die Wohnung nicht mieten. Sie ist viel zu dunkel.",
      "Übung 2",
      "Beispiel: Heute bleibe ich zu Hause, a be r morgen will ich ins Kino gehen.",
      "a) Jonas kann mich heute nicht besuchen, _______ er muss noch lange arbeiten.",
      "b) Du kannst wählen. Wir können ins Kino _______ ins Theater gehen.",
      "c) Paul ist ein sehr guter Koch _______ er kocht oft für seine Familie.",
      "d) Wir möchten nächsten Monat in Urlaub fahren, _______ wir haben leider kein Geld.",
      "e) Sie können die Rechnung bar _______ mit Karte bezahlen.",
      "f) Ich will nicht in dieses Restaurant gehen, _______ der Service ist sehr schlecht.",
      "g) Maria hat gestern Claudia besucht, _______ sie ist nicht sehr lange geblieben.",
      "h) Ich räume mein Zimmer auf, _______ Robert putzt die Küche.",
      "i) Ich schicke dir keine E-Mail, _______ (ich schicke dir) ein Foto.",
      "j) Bei dem Projekt helfen mir Paul _______ sein Bruder.",
      "k) Boris arbeitet viel und hart, _______ er verdient nur sehr wenig Geld."
    ],
    "id": "8.2",
    "exerciseCount": 0
  },
  {
    "lesson": 8,
    "topic": 3,
    "title": "Präpositionen mit Akkusativ",
    "pdfPage": 32,
    "lines": [
      "Präposition Bedeutung Beispiele",
      "Zeit bis morgen, bis nächste Woche",
      "bis",
      "Ort bis München",
      "Ort durch die Stadt",
      "durch",
      "Grund durch einen Unfall",
      "Ziel für die Tante",
      "für",
      "Zeit für zwei Wochen",
      "Ort gegen den Baum",
      "gegen",
      "Meinung gegen den Plan",
      "ohne Art und Weise ohne Schirm, ohne Grund",
      "Ort um den Tisch",
      "um",
      "Zeit um 18 Uhr",
      "Manchmal sind diese Präpositionen mit dem Artikel verbunden:",
      "durchs > durch das fürs > für das ums > um das",
      "Übung 1",
      "Ergänzen Sie die Endungen.",
      "a) Paul fährt ohne sein___ Kollegin zur Konferenz. i) Er will nicht ohne m____ nach Spanien fliegen.",
      "b) Der Hund läuft um d____ Baum. j) Die Reporter stehen um d___ Ministerin.",
      "c) Ich bin gegen d___ Stuhl gelaufen. Aua! k) Eva schreibt das Diktat ohne ein___ Fehler.",
      "d) Sie geht nie ohne ein___ Schirm spazieren. l) Gehen wir nicht durch d___ Bahnhofsstraße?",
      "e) Das Geschenk ist für dein___ Großvater. m) Wir spielen gegen d___ Mannschaft aus Köln.",
      "f) Peter geht durch d___ Fußgängerzone. n) Jonas ist ohne ein___ Erklärung weggegangen.",
      "g) Robert fährt für ein___ Woche nach Italien. o) Peter muss noch für d____ Prüfung lernen.",
      "h) Wo ist der Schlüssel für d____ Keller? p) Für w___ ist die Torte hier?",
      "Übung 2",
      "Ergänzen Sie eine Präposition mit Akkusativ.",
      "a) Die Gäste sitzen _______ den Tisch und trinken Wein.",
      "b) Der Mechaniker muss den Wagen _______ nächsten Freitag reparieren.",
      "c) Sie sieht _______ das Mikroskop.",
      "d) Es ist kalt. Geh nicht _______ Jacke raus!",
      "e) Er will Rosen _______ die Freundin kaufen.",
      "f) Geh nachts nicht _______ den Park! Das ist zu gefährlich.",
      "g) Das ist eine schlechte Idee. Ich bin ________ die Idee.",
      "h) Sie kommt immer _______ 18.00 Uhr nach Hause.",
      "i) Ich kann die Arbeit _______ Hilfe nicht machen.",
      "j) Der Zug fährt nur _______ Frankfurt. Dort müssen Sie umsteigen.",
      "k) Er sieht _______ das Fenster auf die Straße.",
      "l) Du kannst nicht _______ ein Geschenk zur Party gehen!",
      "m) _______ wen ist das Geschenk?",
      "n) Der Mann lacht _______ Grund."
    ],
    "id": "8.3",
    "exerciseCount": 0
  }
];
