/* Original A2 verb reference aligned with the topics in chapters 7-12. */
window.A2_VERBS = [
  {chapter:7,inf:"fahren",forms:["fahre","fährst","fährt","fahren","fahrt","fahren"],praet:"fuhr",aux:"sein",part:"gefahren",ar:"يذهب / يقود",example:"Ich bin mit der U-Bahn zur Arbeit gefahren."},
  {chapter:7,inf:"abfahren",forms:["fahre ab","fährst ab","fährt ab","fahren ab","fahrt ab","fahren ab"],praet:"fuhr ab",aux:"sein",part:"abgefahren",ar:"يغادر (وسيلة مواصلات)",example:"Der Zug ist pünktlich abgefahren."},
  {chapter:7,inf:"ankommen",forms:["komme an","kommst an","kommt an","kommen an","kommt an","kommen an"],praet:"kam an",aux:"sein",part:"angekommen",ar:"يصل",example:"Wir sind um neun Uhr angekommen."},
  {chapter:7,inf:"einsteigen",forms:["steige ein","steigst ein","steigt ein","steigen ein","steigt ein","steigen ein"],praet:"stieg ein",aux:"sein",part:"eingestiegen",ar:"يركب / يصعد",example:"Sie ist vorne in den Bus eingestiegen."},
  {chapter:7,inf:"aussteigen",forms:["steige aus","steigst aus","steigt aus","steigen aus","steigt aus","steigen aus"],praet:"stieg aus",aux:"sein",part:"ausgestiegen",ar:"ينزل من وسيلة مواصلات",example:"Wir sind am Rathaus ausgestiegen."},
  {chapter:7,inf:"umsteigen",forms:["steige um","steigst um","steigt um","steigen um","steigt um","steigen um"],praet:"stieg um",aux:"sein",part:"umgestiegen",ar:"يغيّر وسيلة المواصلات",example:"Ich bin am Hauptbahnhof umgestiegen."},
  {chapter:7,inf:"sich verfahren",forms:["verfahre mich","verfährst dich","verfährt sich","verfahren uns","verfahrt euch","verfahren sich"],praet:"verfuhr sich",aux:"haben",part:"verfahren",ar:"يضل الطريق بالسيارة",example:"Wir haben uns in der Altstadt verfahren."},
  {chapter:7,inf:"erreichen",forms:["erreiche","erreichst","erreicht","erreichen","erreicht","erreichen"],praet:"erreichte",aux:"haben",part:"erreicht",ar:"يصل إلى / يلحق",example:"Ich habe den Zug noch erreicht."},
  {chapter:7,inf:"verpassen",forms:["verpasse","verpasst","verpasst","verpassen","verpasst","verpassen"],praet:"verpasste",aux:"haben",part:"verpasst",ar:"تفوته مواصلة أو موعد",example:"Er hat den letzten Bus verpasst."},
  {chapter:7,inf:"ausleihen",forms:["leihe aus","leihst aus","leiht aus","leihen aus","leiht aus","leihen aus"],praet:"lieh aus",aux:"haben",part:"ausgeliehen",ar:"يستعير / يؤجّر",example:"Ich habe mir ein Fahrrad ausgeliehen."},
  {chapter:7,inf:"zurückgeben",forms:["gebe zurück","gibst zurück","gibt zurück","geben zurück","gebt zurück","geben zurück"],praet:"gab zurück",aux:"haben",part:"zurückgegeben",ar:"يعيد / يرجّع",example:"Sie hat das Rad an der Station zurückgegeben."},
  {chapter:7,inf:"herunterladen",forms:["lade herunter","lädst herunter","lädt herunter","laden herunter","ladet herunter","laden herunter"],praet:"lud herunter",aux:"haben",part:"heruntergeladen",ar:"يحمّل من الإنترنت",example:"Ich habe die App heruntergeladen."},

  {chapter:8,inf:"lernen",forms:["lerne","lernst","lernt","lernen","lernt","lernen"],praet:"lernte",aux:"haben",part:"gelernt",ar:"يتعلّم / يذاكر",example:"Wir haben jeden Abend zusammen gelernt."},
  {chapter:8,inf:"verstehen",forms:["verstehe","verstehst","versteht","verstehen","versteht","verstehen"],praet:"verstand",aux:"haben",part:"verstanden",ar:"يفهم",example:"Hast du die Erklärung verstanden?"},
  {chapter:8,inf:"wiederholen",forms:["wiederhole","wiederholst","wiederholt","wiederholen","wiederholt","wiederholen"],praet:"wiederholte",aux:"haben",part:"wiederholt",ar:"يكرر / يراجع",example:"Ich habe die neuen Wörter wiederholt."},
  {chapter:8,inf:"sich konzentrieren",forms:["konzentriere mich","konzentrierst dich","konzentriert sich","konzentrieren uns","konzentriert euch","konzentrieren sich"],praet:"konzentrierte sich",aux:"haben",part:"konzentriert",ar:"يركّز",example:"Sie hat sich gut auf die Aufgabe konzentriert."},
  {chapter:8,inf:"bestehen",forms:["bestehe","bestehst","besteht","bestehen","besteht","bestehen"],praet:"bestand",aux:"haben",part:"bestanden",ar:"ينجح في الامتحان",example:"Er hat die Prüfung bestanden."},
  {chapter:8,inf:"sich vorbereiten",forms:["bereite mich vor","bereitest dich vor","bereitet sich vor","bereiten uns vor","bereitet euch vor","bereiten sich vor"],praet:"bereitete sich vor",aux:"haben",part:"vorbereitet",ar:"يستعد",example:"Wir haben uns auf die Prüfung vorbereitet."},
  {chapter:8,inf:"nachschlagen",forms:["schlage nach","schlägst nach","schlägt nach","schlagen nach","schlagt nach","schlagen nach"],praet:"schlug nach",aux:"haben",part:"nachgeschlagen",ar:"يبحث في قاموس أو مرجع",example:"Ich habe das Wort im Wörterbuch nachgeschlagen."},
  {chapter:8,inf:"nachsprechen",forms:["spreche nach","sprichst nach","spricht nach","sprechen nach","sprecht nach","sprechen nach"],praet:"sprach nach",aux:"haben",part:"nachgesprochen",ar:"يردد خلف المتحدث",example:"Die Lernenden haben den Satz nachgesprochen."},
  {chapter:8,inf:"präsentieren",forms:["präsentiere","präsentierst","präsentiert","präsentieren","präsentiert","präsentieren"],praet:"präsentierte",aux:"haben",part:"präsentiert",ar:"يقدّم عرضًا",example:"Sie hat ihr Thema klar präsentiert."},
  {chapter:8,inf:"erklären",forms:["erkläre","erklärst","erklärt","erklären","erklärt","erklären"],praet:"erklärte",aux:"haben",part:"erklärt",ar:"يشرح",example:"Der Lehrer hat die Regel erklärt."},

  {chapter:9,inf:"trainieren",forms:["trainiere","trainierst","trainiert","trainieren","trainiert","trainieren"],praet:"trainierte",aux:"haben",part:"trainiert",ar:"يتدرّب",example:"Die Mannschaft hat zweimal trainiert."},
  {chapter:9,inf:"sich aufwärmen",forms:["wärme mich auf","wärmst dich auf","wärmt sich auf","wärmen uns auf","wärmt euch auf","wärmen sich auf"],praet:"wärmte sich auf",aux:"haben",part:"aufgewärmt",ar:"يقوم بالإحماء",example:"Wir haben uns vor dem Spiel aufgewärmt."},
  {chapter:9,inf:"sich verletzen",forms:["verletze mich","verletzt dich","verletzt sich","verletzen uns","verletzt euch","verletzen sich"],praet:"verletzte sich",aux:"haben",part:"verletzt",ar:"يُصاب",example:"Er hat sich am Knie verletzt."},
  {chapter:9,inf:"teilnehmen",forms:["nehme teil","nimmst teil","nimmt teil","nehmen teil","nehmt teil","nehmen teil"],praet:"nahm teil",aux:"haben",part:"teilgenommen",ar:"يشارك",example:"Sie hat am Wettkampf teilgenommen."},
  {chapter:9,inf:"gewinnen",forms:["gewinne","gewinnst","gewinnt","gewinnen","gewinnt","gewinnen"],praet:"gewann",aux:"haben",part:"gewonnen",ar:"يفوز",example:"Unsere Mannschaft hat das Spiel gewonnen."},
  {chapter:9,inf:"verlieren",forms:["verliere","verlierst","verliert","verlieren","verliert","verlieren"],praet:"verlor",aux:"haben",part:"verloren",ar:"يخسر / يفقد",example:"Wir haben leider knapp verloren."},
  {chapter:9,inf:"sich freuen",forms:["freue mich","freust dich","freut sich","freuen uns","freut euch","freuen sich"],praet:"freute sich",aux:"haben",part:"gefreut",ar:"يفرح / يتطلع إلى",example:"Ich habe mich über deinen Besuch gefreut."},

  {chapter:10,inf:"wohnen",forms:["wohne","wohnst","wohnt","wohnen","wohnt","wohnen"],praet:"wohnte",aux:"haben",part:"gewohnt",ar:"يسكن",example:"Wir haben drei Jahre in Köln gewohnt."},
  {chapter:10,inf:"umziehen",forms:["ziehe um","ziehst um","zieht um","ziehen um","zieht um","ziehen um"],praet:"zog um",aux:"sein",part:"umgezogen",ar:"ينتقل إلى سكن جديد",example:"Meine Nachbarn sind im Mai umgezogen."},
  {chapter:10,inf:"helfen",forms:["helfe","hilfst","hilft","helfen","helft","helfen"],praet:"half",aux:"haben",part:"geholfen",ar:"يساعد",example:"Die Nachbarin hat mir beim Umzug geholfen."},
  {chapter:10,inf:"sich beschweren",forms:["beschwere mich","beschwerst dich","beschwert sich","beschweren uns","beschwert euch","beschweren sich"],praet:"beschwerte sich",aux:"haben",part:"beschwert",ar:"يشتكي",example:"Er hat sich über den Lärm beschwert."},
  {chapter:10,inf:"vereinbaren",forms:["vereinbare","vereinbarst","vereinbart","vereinbaren","vereinbart","vereinbaren"],praet:"vereinbarte",aux:"haben",part:"vereinbart",ar:"يتفق على",example:"Wir haben einen Termin vereinbart."},
  {chapter:10,inf:"aufräumen",forms:["räume auf","räumst auf","räumt auf","räumen auf","räumt auf","räumen auf"],praet:"räumte auf",aux:"haben",part:"aufgeräumt",ar:"يرتّب",example:"Die Kinder haben ihr Zimmer aufgeräumt."},
  {chapter:10,inf:"sich kümmern",forms:["kümmere mich","kümmerst dich","kümmert sich","kümmern uns","kümmert euch","kümmern sich"],praet:"kümmerte sich",aux:"haben",part:"gekümmert",ar:"يهتم بـ / يتولى أمر",example:"Sie hat sich um die Pflanzen gekümmert."},

  {chapter:11,inf:"sich erinnern",forms:["erinnere mich","erinnerst dich","erinnert sich","erinnern uns","erinnert euch","erinnern sich"],praet:"erinnerte sich",aux:"haben",part:"erinnert",ar:"يتذكّر",example:"Ich habe mich an meine Schulzeit erinnert."},
  {chapter:11,inf:"vergessen",forms:["vergesse","vergisst","vergisst","vergessen","vergesst","vergessen"],praet:"vergaß",aux:"haben",part:"vergessen",ar:"ينسى",example:"Ich habe den Termin vergessen."},
  {chapter:11,inf:"sich vornehmen",forms:["nehme mir vor","nimmst dir vor","nimmt sich vor","nehmen uns vor","nehmt euch vor","nehmen sich vor"],praet:"nahm sich vor",aux:"haben",part:"vorgenommen",ar:"ينوي / يضع هدفًا",example:"Ich habe mir mehr Sport vorgenommen."},
  {chapter:11,inf:"verbringen",forms:["verbringe","verbringst","verbringt","verbringen","verbringt","verbringen"],praet:"verbrachte",aux:"haben",part:"verbracht",ar:"يقضي وقتًا",example:"Wir haben den Sommer am Meer verbracht."},
  {chapter:11,inf:"werden",forms:["werde","wirst","wird","werden","werdet","werden"],praet:"wurde",aux:"sein",part:"geworden",ar:"يصبح",example:"Er ist mit der Zeit ruhiger geworden."},
  {chapter:11,inf:"sich wünschen",forms:["wünsche mir","wünschst dir","wünscht sich","wünschen uns","wünscht euch","wünschen sich"],praet:"wünschte sich",aux:"haben",part:"gewünscht",ar:"يتمنى",example:"Sie hat sich mehr Freizeit gewünscht."},
  {chapter:11,inf:"verwirklichen",forms:["verwirkliche","verwirklichst","verwirklicht","verwirklichen","verwirklicht","verwirklichen"],praet:"verwirklichte",aux:"haben",part:"verwirklicht",ar:"يحقق حلمًا أو خطة",example:"Er hat seinen Traum verwirklicht."},

  {chapter:12,inf:"hören",forms:["höre","hörst","hört","hören","hört","hören"],praet:"hörte",aux:"haben",part:"gehört",ar:"يسمع / يستمع",example:"Wir haben das Lied oft gehört."},
  {chapter:12,inf:"trinken",forms:["trinke","trinkst","trinkt","trinken","trinkt","trinken"],praet:"trank",aux:"haben",part:"getrunken",ar:"يشرب",example:"Wir haben nach dem Konzert etwas getrunken."},
  {chapter:12,inf:"sehen",forms:["sehe","siehst","sieht","sehen","seht","sehen"],praet:"sah",aux:"haben",part:"gesehen",ar:"يرى / يشاهد",example:"Hast du den neuen Film gesehen?"},
  {chapter:12,inf:"empfehlen",forms:["empfehle","empfiehlst","empfiehlt","empfehlen","empfehlt","empfehlen"],praet:"empfahl",aux:"haben",part:"empfohlen",ar:"يرشّح / ينصح بـ",example:"Meine Freundin hat mir das Konzert empfohlen."},
  {chapter:12,inf:"gefallen",forms:["gefalle","gefällst","gefällt","gefallen","gefallt","gefallen"],praet:"gefiel",aux:"haben",part:"gefallen",ar:"يعجب",example:"Die Ausstellung hat mir sehr gefallen."},
  {chapter:12,inf:"darstellen",forms:["stelle dar","stellst dar","stellt dar","stellen dar","stellt dar","stellen dar"],praet:"stellte dar",aux:"haben",part:"dargestellt",ar:"يجسّد / يصوّر",example:"Das Bild hat eine ruhige Szene dargestellt."},
  {chapter:12,inf:"auftreten",forms:["trete auf","trittst auf","tritt auf","treten auf","tretet auf","treten auf"],praet:"trat auf",aux:"sein",part:"aufgetreten",ar:"يظهر أو يقدم عرضًا",example:"Die Band ist gestern live aufgetreten."}
];

(function () {
  const past = {
    fahren:["fuhr","fuhrst","fuhr","fuhren","fuhrt","fuhren"],
    abfahren:["fuhr ab","fuhrst ab","fuhr ab","fuhren ab","fuhrt ab","fuhren ab"],
    ankommen:["kam an","kamst an","kam an","kamen an","kamt an","kamen an"],
    einsteigen:["stieg ein","stiegst ein","stieg ein","stiegen ein","stiegt ein","stiegen ein"],
    aussteigen:["stieg aus","stiegst aus","stieg aus","stiegen aus","stiegt aus","stiegen aus"],
    umsteigen:["stieg um","stiegst um","stieg um","stiegen um","stiegt um","stiegen um"],
    "sich verfahren":["verfuhr mich","verfuhrst dich","verfuhr sich","verfuhren uns","verfuhrt euch","verfuhren sich"],
    erreichen:["erreichte","erreichtest","erreichte","erreichten","erreichtet","erreichten"],
    verpassen:["verpasste","verpasstest","verpasste","verpassten","verpasstet","verpassten"],
    ausleihen:["lieh aus","liehst aus","lieh aus","liehen aus","lieht aus","liehen aus"],
    zurückgeben:["gab zurück","gabst zurück","gab zurück","gaben zurück","gabt zurück","gaben zurück"],
    herunterladen:["lud herunter","ludst herunter","lud herunter","luden herunter","ludet herunter","luden herunter"],
    lernen:["lernte","lerntest","lernte","lernten","lerntet","lernten"],
    verstehen:["verstand","verstandest","verstand","verstanden","verstandet","verstanden"],
    wiederholen:["wiederholte","wiederholtest","wiederholte","wiederholten","wiederholtet","wiederholten"],
    "sich konzentrieren":["konzentrierte mich","konzentriertest dich","konzentrierte sich","konzentrierten uns","konzentriertet euch","konzentrierten sich"],
    bestehen:["bestand","bestandest","bestand","bestanden","bestandet","bestanden"],
    "sich vorbereiten":["bereitete mich vor","bereitetest dich vor","bereitete sich vor","bereiteten uns vor","bereitetet euch vor","bereiteten sich vor"],
    nachschlagen:["schlug nach","schlugst nach","schlug nach","schlugen nach","schlugt nach","schlugen nach"],
    nachsprechen:["sprach nach","sprachst nach","sprach nach","sprachen nach","spracht nach","sprachen nach"],
    präsentieren:["präsentierte","präsentiertest","präsentierte","präsentierten","präsentiertet","präsentierten"],
    erklären:["erklärte","erklärtest","erklärte","erklärten","erklärtet","erklärten"],
    trainieren:["trainierte","trainiertest","trainierte","trainierten","trainiertet","trainierten"],
    "sich aufwärmen":["wärmte mich auf","wärmtest dich auf","wärmte sich auf","wärmten uns auf","wärmtet euch auf","wärmten sich auf"],
    "sich verletzen":["verletzte mich","verletztest dich","verletzte sich","verletzten uns","verletztet euch","verletzten sich"],
    teilnehmen:["nahm teil","nahmst teil","nahm teil","nahmen teil","nahmt teil","nahmen teil"],
    gewinnen:["gewann","gewannst","gewann","gewannen","gewannt","gewannen"],
    verlieren:["verlor","verlorst","verlor","verloren","verlort","verloren"],
    "sich freuen":["freute mich","freutest dich","freute sich","freuten uns","freutet euch","freuten sich"],
    wohnen:["wohnte","wohntest","wohnte","wohnten","wohntet","wohnten"],
    umziehen:["zog um","zogst um","zog um","zogen um","zogt um","zogen um"],
    helfen:["half","halfst","half","halfen","halft","halfen"],
    "sich beschweren":["beschwerte mich","beschwertest dich","beschwerte sich","beschwerten uns","beschwertet euch","beschwerten sich"],
    vereinbaren:["vereinbarte","vereinbartest","vereinbarte","vereinbarten","vereinbartet","vereinbarten"],
    aufräumen:["räumte auf","räumtest auf","räumte auf","räumten auf","räumtet auf","räumten auf"],
    "sich kümmern":["kümmerte mich","kümmertest dich","kümmerte sich","kümmerten uns","kümmertet euch","kümmerten sich"],
    "sich erinnern":["erinnerte mich","erinnertest dich","erinnerte sich","erinnerten uns","erinnertet euch","erinnerten sich"],
    vergessen:["vergaß","vergaßest","vergaß","vergaßen","vergaßt","vergaßen"],
    "sich vornehmen":["nahm mir vor","nahmst dir vor","nahm sich vor","nahmen uns vor","nahmt euch vor","nahmen sich vor"],
    verbringen:["verbrachte","verbrachtest","verbrachte","verbrachten","verbrachtet","verbrachten"],
    werden:["wurde","wurdest","wurde","wurden","wurdet","wurden"],
    "sich wünschen":["wünschte mir","wünschtest dir","wünschte sich","wünschten uns","wünschtet euch","wünschten sich"],
    verwirklichen:["verwirklichte","verwirklichtest","verwirklichte","verwirklichten","verwirklichtet","verwirklichten"],
    hören:["hörte","hörtest","hörte","hörten","hörtet","hörten"],
    trinken:["trank","trankst","trank","tranken","trankt","tranken"],
    sehen:["sah","sahst","sah","sahen","saht","sahen"],
    empfehlen:["empfahl","empfahlst","empfahl","empfahlen","empfahlt","empfahlen"],
    gefallen:["gefiel","gefielst","gefiel","gefielen","gefielt","gefielen"],
    darstellen:["stellte dar","stelltest dar","stellte dar","stellten dar","stelltet dar","stellten dar"],
    auftreten:["trat auf","tratst auf","trat auf","traten auf","tratet auf","traten auf"]
  };
  window.A2_VERBS.forEach(verb => { verb.praetForms = past[verb.inf]; });
})();
