/* Satzbaukasten, Teil 1: feste Verblisten, Konnektoren, W-Fragen und Präpositionen.
   c = Kasus des Reflexivpronomens (A = mich/dich, D = mir/dir).
   p = Präpositionen mit Kasus [['auf','A']]. */
window.BAUSTEINE = window.BAUSTEINE || {};

window.BAUSTEINE.reflexive = [
  {v:'sich anmelden',c:'A',p:[['für','A'],['zu','D']],ar:'يسجّل نفسه',ex:'Ich melde mich für den Deutschkurs an.',lvl:'A1'},
  {v:'sich anziehen',c:'A',ar:'يلبس هدومه',ex:'Er zieht sich schnell an.',lvl:'A1'},
  {v:'sich ausziehen',c:'A',ar:'يقلع هدومه',ex:'Die Kinder ziehen sich aus und gehen ins Bett.',lvl:'A1'},
  {v:'sich umziehen',c:'A',ar:'يغيّر هدومه',ex:'Nach der Arbeit ziehe ich mich um.',lvl:'A2'},
  {v:'sich duschen',c:'A',ar:'ياخد دش',ex:'Ich dusche mich jeden Morgen.',lvl:'A1'},
  {v:'sich waschen',c:'A',ar:'يغتسل',ex:'Das Kind wäscht sich allein.',lvl:'A1'},
  {v:'sich rasieren',c:'A',ar:'يحلق دقنه',ex:'Mein Vater rasiert sich jeden Tag.',lvl:'A1'},
  {v:'sich kämmen',c:'A',ar:'يسرّح شعره',ex:'Sie kämmt sich vor dem Spiegel.',lvl:'A1'},
  {v:'sich schminken',c:'A',ar:'تحط مكياج',ex:'Sie schminkt sich nur am Wochenende.',lvl:'A1'},
  {v:'sich beeilen',c:'A',only:true,ar:'يستعجل',ex:'Beeil dich, der Bus kommt!',lvl:'A1'},
  {v:'sich verspäten',c:'A',only:true,ar:'يتأخر',ex:'Entschuldigung, ich habe mich verspätet.',lvl:'A2'},
  {v:'sich fühlen',c:'A',ar:'يحس / يشعر',ex:'Ich fühle mich heute nicht gut.',lvl:'A1'},
  {v:'sich wohlfühlen',c:'A',ar:'يرتاح / يحس إنه مبسوط في مكان',ex:'In meiner neuen Wohnung fühle ich mich wohl.',lvl:'A2'},
  {v:'sich ausruhen',c:'A',ar:'يرتاح',ex:'Am Sonntag ruhe ich mich aus.',lvl:'A2'},
  {v:'sich entspannen',c:'A',ar:'يسترخي',ex:'Beim Yoga kann ich mich gut entspannen.',lvl:'A2'},
  {v:'sich erholen',c:'A',p:[['von','D']],ar:'يرتاح / يتعافى من',ex:'Ich muss mich von dem Stress erholen.',lvl:'A2'},
  {v:'sich erkälten',c:'A',ar:'ياخد برد',ex:'Zieh eine Jacke an, sonst erkältest du dich.',lvl:'A2'},
  {v:'sich verletzen',c:'A',ar:'يتعوّر',ex:'Er hat sich beim Fußball verletzt.',lvl:'A2'},
  {v:'sich setzen',c:'A',ar:'يقعد',ex:'Bitte setzen Sie sich!',lvl:'A1'},
  {v:'sich hinlegen',c:'A',ar:'يستلقي / يتمدد',ex:'Ich bin müde, ich lege mich kurz hin.',lvl:'A2'},
  {v:'sich bewegen',c:'A',ar:'يتحرك',ex:'Du solltest dich mehr bewegen.',lvl:'A2'},
  {v:'sich freuen',c:'A',p:[['auf','A'],['über','A']],ar:'يتطلع لـ (مستقبل) / يفرح بـ (حاجة حصلت)',ex:'Ich freue mich auf den Urlaub. – Ich freue mich über dein Geschenk.',lvl:'A1'},
  {v:'sich ärgern',c:'A',p:[['über','A']],ar:'يتضايق من',ex:'Er ärgert sich über den Stau.',lvl:'A2'},
  {v:'sich aufregen',c:'A',p:[['über','A']],ar:'يتعصب من',ex:'Reg dich nicht so auf!',lvl:'B1'},
  {v:'sich wundern',c:'A',p:[['über','A']],ar:'يستغرب من',ex:'Ich wundere mich über seine Antwort.',lvl:'B1'},
  {v:'sich langweilen',c:'A',ar:'يزهق / يمل',ex:'Im Unterricht langweilt er sich nie.',lvl:'A2'},
  {v:'sich interessieren',c:'A',p:[['für','A']],ar:'يهتم بـ',ex:'Ich interessiere mich für Politik.',lvl:'A2'},
  {v:'sich kümmern',c:'A',p:[['um','A']],ar:'يهتم بـ / يرعى',ex:'Wer kümmert sich um den Hund?',lvl:'A2'},
  {v:'sich sorgen',c:'A',p:[['um','A']],ar:'يقلق على',ex:'Die Mutter sorgt sich um ihren Sohn.',lvl:'B1'},
  {v:'sich beschäftigen',c:'A',p:[['mit','D']],ar:'ينشغل بـ / يتعامل مع موضوع',ex:'In der Freizeit beschäftige ich mich mit Musik.',lvl:'B1'},
  {v:'sich konzentrieren',c:'A',p:[['auf','A']],ar:'يركز على',ex:'Ich kann mich nicht auf die Arbeit konzentrieren.',lvl:'A2'},
  {v:'sich vorbereiten',c:'A',p:[['auf','A']],ar:'يستعد لـ',ex:'Sie bereitet sich auf die Prüfung vor.',lvl:'A2'},
  {v:'sich gewöhnen',c:'A',p:[['an','A']],ar:'يتعوّد على',ex:'Ich habe mich an das Wetter gewöhnt.',lvl:'A2'},
  {v:'sich erinnern',c:'A',p:[['an','A']],ar:'يتذكر',ex:'Erinnerst du dich an unseren ersten Tag?',lvl:'A2'},
  {v:'sich entscheiden',c:'A',p:[['für','A']],ar:'يقرر / يختار',ex:'Ich habe mich für das blaue Auto entschieden.',lvl:'A2'},
  {v:'sich bedanken',c:'A',only:true,p:[['bei','D'],['für','A']],ar:'يشكر',ex:'Ich bedanke mich bei dir für die Hilfe.',lvl:'A2'},
  {v:'sich entschuldigen',c:'A',p:[['bei','D'],['für','A']],ar:'يعتذر',ex:'Er entschuldigt sich bei ihr für die Verspätung.',lvl:'A2'},
  {v:'sich beschweren',c:'A',p:[['bei','D'],['über','A']],ar:'يشتكي',ex:'Wir beschweren uns beim Vermieter über die Heizung.',lvl:'A2'},
  {v:'sich bewerben',c:'A',p:[['um','A'],['bei','D']],ar:'يقدّم على (وظيفة)',ex:'Ich bewerbe mich bei der Firma um eine Stelle.',lvl:'A2'},
  {v:'sich informieren',c:'A',p:[['über','A']],ar:'يستعلم عن',ex:'Informier dich vorher über die Öffnungszeiten.',lvl:'A2'},
  {v:'sich erkundigen',c:'A',only:true,p:[['nach','D']],ar:'يستفسر عن',ex:'Ich habe mich nach dem Preis erkundigt.',lvl:'B1'},
  {v:'sich verabreden',c:'A',p:[['mit','D']],ar:'يتواعد مع',ex:'Ich verabrede mich mit Lisa fürs Kino.',lvl:'A2'},
  {v:'sich treffen',c:'A',p:[['mit','D']],ar:'يتقابل مع',ex:'Wir treffen uns um acht vor dem Kino.',lvl:'A1'},
  {v:'sich verabschieden',c:'A',p:[['von','D']],ar:'يودّع',ex:'Sie verabschiedet sich von ihren Kollegen.',lvl:'A2'},
  {v:'sich unterhalten',c:'A',p:[['mit','D'],['über','A']],ar:'يدردش / يتكلم مع',ex:'Wir unterhalten uns über den Film.',lvl:'A2'},
  {v:'sich streiten',c:'A',p:[['mit','D'],['über','A']],ar:'يتخانق / يتجادل',ex:'Die Geschwister streiten sich über alles.',lvl:'B1'},
  {v:'sich verstehen',c:'A',p:[['mit','D']],ar:'يتفاهم مع',ex:'Ich verstehe mich gut mit meiner Chefin.',lvl:'A2'},
  {v:'sich verlieben',c:'A',only:true,p:[['in','A']],ar:'يقع في حب',ex:'Er hat sich in seine Nachbarin verliebt.',lvl:'A2'},
  {v:'sich trennen',c:'A',p:[['von','D']],ar:'ينفصل عن',ex:'Sie hat sich von ihrem Freund getrennt.',lvl:'B1'},
  {v:'sich fürchten',c:'A',p:[['vor','D']],ar:'يخاف من',ex:'Das Kind fürchtet sich vor dem Hund.',lvl:'B1'},
  {v:'sich schämen',c:'A',only:true,p:[['für','A']],ar:'يتكسف / يخجل',ex:'Du musst dich dafür nicht schämen.',lvl:'B1'},
  {v:'sich irren',c:'A',only:true,ar:'يغلط / يكون فاهم غلط',ex:'Ich glaube, Sie irren sich.',lvl:'B1'},
  {v:'sich verlaufen',c:'A',ar:'يتوه (ماشي)',ex:'In der Altstadt habe ich mich verlaufen.',lvl:'A2'},
  {v:'sich verfahren',c:'A',ar:'يتوه (بالعربية)',ex:'Ohne Navi verfahre ich mich immer.',lvl:'B1'},
  {v:'sich melden',c:'A',p:[['bei','D']],ar:'يتواصل مع / يرفع إيده',ex:'Melde dich bitte bei mir, wenn du angekommen bist.',lvl:'A2'},
  {v:'sich vorstellen',c:'A',ar:'يعرّف بنفسه',ex:'Darf ich mich vorstellen? Ich heiße Omar.',lvl:'A1'},
  {v:'sich verändern',c:'A',ar:'يتغيّر',ex:'Die Stadt hat sich sehr verändert.',lvl:'B1'},
  {v:'sich befinden',c:'A',ar:'يقع / يتواجد',ex:'Das Büro befindet sich im dritten Stock.',lvl:'B1'},
  {v:'sich lohnen',c:'A',ar:'يستاهل',ex:'Der Ausflug lohnt sich wirklich.',lvl:'B1'},
  {v:'sich handeln',c:'A',p:[['um','A']],ar:'الموضوع عن / الأمر يتعلق بـ',ex:'Es handelt sich um ein Missverständnis.',lvl:'B1'},
  {v:'sich verlassen',c:'A',p:[['auf','A']],ar:'يعتمد على',ex:'Auf meinen Bruder kann ich mich verlassen.',lvl:'B1'},
  {v:'sich beteiligen',c:'A',p:[['an','D']],ar:'يشارك في',ex:'Viele Eltern beteiligen sich an dem Fest.',lvl:'B1'},
  {v:'sich engagieren',c:'A',p:[['für','A']],ar:'ينشط / يتطوع لـ',ex:'Sie engagiert sich für den Umweltschutz.',lvl:'B1'},
  {v:'sich einigen',c:'A',p:[['auf','A']],ar:'يتفق على',ex:'Wir haben uns auf einen Termin geeinigt.',lvl:'B1'},
  {v:'sich bemühen',c:'A',p:[['um','A']],ar:'يجتهد / يسعى لـ',ex:'Er bemüht sich um eine Wohnung.',lvl:'B1'},
  {v:'sich eignen',c:'A',p:[['für','A']],ar:'يصلح لـ',ex:'Das Buch eignet sich gut für Anfänger.',lvl:'B1'},
  {v:'sich richten',c:'A',p:[['nach','D']],ar:'يمشي حسب / يلتزم بـ',ex:'Wir richten uns nach dem Wetter.',lvl:'B1'},
  {v:'sich wenden',c:'A',p:[['an','A']],ar:'يلجأ لـ / يتوجه لـ',ex:'Bei Fragen wenden Sie sich bitte an die Rezeption.',lvl:'B1'},
  {v:'sich ernähren',c:'A',ar:'يتغذى',ex:'Ich versuche, mich gesund zu ernähren.',lvl:'A2'},
  {v:'sich weiterbilden',c:'A',ar:'يطوّر نفسه / ياخد تدريب',ex:'Sie bildet sich am Abend weiter.',lvl:'B1'},
  {v:'sich wehren',c:'A',p:[['gegen','A']],ar:'يدافع عن نفسه ضد',ex:'Die Mieter wehren sich gegen die hohe Miete.',lvl:'B1'},
  {v:'sich (etwas) ansehen',c:'D',ar:'يتفرج على',ex:'Ich sehe mir heute einen Film an.',lvl:'A2'},
  {v:'sich (etwas) anschauen',c:'D',ar:'يتفرج على / يبص على',ex:'Schau dir mal dieses Foto an!',lvl:'A2'},
  {v:'sich (etwas) vorstellen',c:'D',ar:'يتخيل',ex:'Ich kann mir das gut vorstellen.',lvl:'A2'},
  {v:'sich (etwas) merken',c:'D',ar:'يحفظ / يفتكر',ex:'Ich kann mir keine Namen merken.',lvl:'A2'},
  {v:'sich (etwas) wünschen',c:'D',ar:'يتمنى',ex:'Was wünschst du dir zum Geburtstag?',lvl:'A1'},
  {v:'sich (etwas) leisten',c:'D',ar:'يقدر يتحمل تمنه',ex:'Ein neues Auto kann ich mir nicht leisten.',lvl:'B1'},
  {v:'sich (etwas) überlegen',c:'D',ar:'يفكر في / يدرس الموضوع',ex:'Ich überlege mir das noch.',lvl:'A2'},
  {v:'sich (etwas) kaufen',c:'D',ar:'يشتري لنفسه',ex:'Ich kaufe mir eine neue Jacke.',lvl:'A1'},
  {v:'sich (etwas) ausleihen',c:'D',ar:'يستلف',ex:'Ich leihe mir ein Buch in der Bibliothek aus.',lvl:'A2'},
  {v:'sich (etwas) denken',c:'D',ar:'يتوقع / يخمّن',ex:'Das habe ich mir schon gedacht.',lvl:'B1'},
  {v:'sich (etwas) gönnen',c:'D',ar:'يدلّع نفسه بـ',ex:'Heute gönne ich mir ein Stück Kuchen.',lvl:'B1'},
  {v:'sich die Zähne putzen',c:'D',ar:'يغسل سنانه',ex:'Ich putze mir zweimal am Tag die Zähne.',lvl:'A1'},
  {v:'sich die Hände waschen',c:'D',ar:'يغسل إيديه',ex:'Wasch dir bitte die Hände vor dem Essen!',lvl:'A1'},
  {v:'sich die Haare kämmen',c:'D',ar:'يسرّح شعره',ex:'Sie kämmt sich die Haare.',lvl:'A1'},
  {v:'sich (etwas) brechen',c:'D',ar:'يتكسر له (عضو)',ex:'Er hat sich das Bein gebrochen.',lvl:'A2'},
  {v:'sich Sorgen machen',c:'D',p:[['um','A']],ar:'يقلق على',ex:'Mach dir keine Sorgen um mich!',lvl:'A2'},
  {v:'sich Zeit nehmen',c:'D',p:[['für','A']],ar:'ياخد وقته / يفضّي وقت لـ',ex:'Nimm dir Zeit für deine Familie.',lvl:'A2'},
  {v:'sich Mühe geben',c:'D',ar:'يبذل مجهود',ex:'Der Schüler gibt sich viel Mühe.',lvl:'B1'}
];

window.BAUSTEINE.reflexivePronouns = [
  ['ich','mich','mir'],['du','dich','dir'],['er / sie / es','sich','sich'],
  ['wir','uns','uns'],['ihr','euch','euch'],['sie / Sie','sich','sich']
];

window.BAUSTEINE.prepVerbs = [
  {v:'abhängen',p:[['von','D']],ar:'يعتمد على / يتوقف على',ex:'Das hängt vom Wetter ab.',lvl:'B1'},
  {v:'achten',p:[['auf','A']],ar:'ياخد باله من',ex:'Achte bitte auf die Kinder!',lvl:'A2'},
  {v:'anfangen',p:[['mit','D']],ar:'يبدأ بـ',ex:'Wir fangen mit der ersten Übung an.',lvl:'A2'},
  {v:'ankommen',p:[['auf','A']],ar:'يتوقف على (es kommt darauf an)',ex:'Es kommt auf das Angebot an.',lvl:'B1'},
  {v:'antworten',p:[['auf','A']],ar:'يرد على',ex:'Bitte antworte auf meine E-Mail.',lvl:'A2'},
  {v:'arbeiten',p:[['an','D']],ar:'يشتغل على',ex:'Ich arbeite an einem neuen Projekt.',lvl:'A2'},
  {v:'aufhören',p:[['mit','D']],ar:'يبطّل / يوقف',ex:'Er hört mit dem Rauchen auf.',lvl:'A2'},
  {v:'aufpassen',p:[['auf','A']],ar:'ياخد باله من / يراعي',ex:'Kannst du auf meine Tasche aufpassen?',lvl:'A2'},
  {v:'beginnen',p:[['mit','D']],ar:'يبدأ بـ',ex:'Wir beginnen mit dem Unterricht um neun.',lvl:'A2'},
  {v:'beitragen',p:[['zu','D']],ar:'يساهم في',ex:'Jeder kann zum Umweltschutz beitragen.',lvl:'B1'},
  {v:'berichten',p:[['über','A'],['von','D']],ar:'يحكي / يبلّغ عن',ex:'Die Zeitung berichtet über den Unfall.',lvl:'B1'},
  {v:'bestehen',p:[['aus','D']],ar:'يتكوّن من',ex:'Die Wohnung besteht aus drei Zimmern.',lvl:'B1'},
  {v:'bitten',p:[['um','A']],ar:'يطلب',ex:'Darf ich Sie um Hilfe bitten?',lvl:'A2'},
  {v:'danken',p:[['für','A']],ar:'يشكر على',ex:'Ich danke dir für die Blumen.',lvl:'A2'},
  {v:'denken',p:[['an','A']],ar:'يفكر في',ex:'Ich denke oft an meine Familie.',lvl:'A2'},
  {v:'diskutieren',p:[['über','A']],ar:'يناقش',ex:'Wir diskutieren über das Thema Arbeit.',lvl:'A2'},
  {v:'einladen',p:[['zu','D']],ar:'يعزم على',ex:'Ich lade dich zu meiner Party ein.',lvl:'A1'},
  {v:'erfahren',p:[['von','D'],['über','A']],ar:'يعرف / يسمع عن',ex:'Von wem hast du das erfahren?',lvl:'B1'},
  {v:'erzählen',p:[['von','D'],['über','A']],ar:'يحكي عن',ex:'Erzähl mal von deinem Urlaub!',lvl:'A2'},
  {v:'fragen',p:[['nach','D']],ar:'يسأل عن',ex:'Der Tourist fragt nach dem Weg.',lvl:'A2'},
  {v:'führen',p:[['zu','D']],ar:'يؤدي إلى',ex:'Stress kann zu Krankheiten führen.',lvl:'B1'},
  {v:'gehen',p:[['um','A']],ar:'الموضوع عن (es geht um)',ex:'In dem Film geht es um eine Familie.',lvl:'A2'},
  {v:'gehören',p:[['zu','D']],ar:'ينتمي لـ / من ضمن',ex:'Das gehört zu meinen Aufgaben.',lvl:'A2'},
  {v:'glauben',p:[['an','A']],ar:'يؤمن بـ / يثق في',ex:'Ich glaube an dich.',lvl:'B1'},
  {v:'gratulieren',p:[['zu','D']],ar:'يهنّي بـ',ex:'Ich gratuliere dir zum Geburtstag.',lvl:'A2'},
  {v:'halten',p:[['von','D']],ar:'رأيه إيه في',ex:'Was hältst du von der Idee?',lvl:'B1'},
  {v:'handeln',p:[['von','D']],ar:'بيتكلم عن (كتاب / فيلم)',ex:'Das Buch handelt von einer Reise.',lvl:'B1'},
  {v:'helfen',p:[['bei','D']],ar:'يساعد في',ex:'Hilfst du mir bei den Hausaufgaben?',lvl:'A2'},
  {v:'hoffen',p:[['auf','A']],ar:'يأمل في',ex:'Wir hoffen auf gutes Wetter.',lvl:'B1'},
  {v:'hören',p:[['von','D']],ar:'يسمع عن / يوصله خبر من',ex:'Hast du etwas von Tom gehört?',lvl:'A2'},
  {v:'kämpfen',p:[['für','A'],['gegen','A']],ar:'يكافح من أجل / ضد',ex:'Sie kämpfen für bessere Löhne.',lvl:'B1'},
  {v:'lachen',p:[['über','A']],ar:'يضحك على',ex:'Alle lachen über den Witz.',lvl:'A2'},
  {v:'leiden',p:[['an','D'],['unter','D']],ar:'يعاني من',ex:'Viele Menschen leiden unter Stress.',lvl:'B1'},
  {v:'nachdenken',p:[['über','A']],ar:'يفكر بعمق في',ex:'Ich muss über dein Angebot nachdenken.',lvl:'B1'},
  {v:'passen',p:[['zu','D']],ar:'يليق على / يناسب',ex:'Die Schuhe passen gut zu dem Kleid.',lvl:'A2'},
  {v:'protestieren',p:[['gegen','A']],ar:'يعترض / يحتج على',ex:'Die Studenten protestieren gegen die Gebühren.',lvl:'B1'},
  {v:'reagieren',p:[['auf','A']],ar:'يتفاعل مع / يرد على',ex:'Wie hat er auf die Nachricht reagiert?',lvl:'B1'},
  {v:'rechnen',p:[['mit','D']],ar:'يتوقع / يحسب حساب',ex:'Mit so viel Regen habe ich nicht gerechnet.',lvl:'B1'},
  {v:'reden',p:[['mit','D'],['über','A']],ar:'يتكلم مع / عن',ex:'Wir müssen über das Problem reden.',lvl:'A2'},
  {v:'riechen',p:[['nach','D']],ar:'ريحته زي',ex:'Hier riecht es nach Kaffee.',lvl:'A2'},
  {v:'schicken',p:[['an','A']],ar:'يبعت لـ',ex:'Ich schicke die Datei an meinen Kollegen.',lvl:'A2'},
  {v:'schmecken',p:[['nach','D']],ar:'طعمه زي',ex:'Der Tee schmeckt nach Zitrone.',lvl:'A2'},
  {v:'schreiben',p:[['an','A'],['über','A']],ar:'يكتب لـ / عن',ex:'Ich schreibe einen Brief an meine Oma.',lvl:'A2'},
  {v:'sorgen',p:[['für','A']],ar:'يوفّر / يهتم بـ',ex:'Wer sorgt für die Getränke?',lvl:'B1'},
  {v:'sprechen',p:[['mit','D'],['über','A']],ar:'يتكلم مع / عن',ex:'Ich spreche mit dem Arzt über meine Schmerzen.',lvl:'A2'},
  {v:'sterben',p:[['an','D']],ar:'يموت بسبب',ex:'Er ist an einem Herzinfarkt gestorben.',lvl:'B1'},
  {v:'stimmen',p:[['für','A'],['gegen','A']],ar:'يصوّت لصالح / ضد',ex:'Die Mehrheit hat für den Vorschlag gestimmt.',lvl:'B1'},
  {v:'suchen',p:[['nach','D']],ar:'يدوّر على',ex:'Ich suche nach meinem Schlüssel.',lvl:'A2'},
  {v:'teilnehmen',p:[['an','D']],ar:'يشارك في',ex:'Ich nehme an einem Kurs teil.',lvl:'A2'},
  {v:'telefonieren',p:[['mit','D']],ar:'يكلّم في التليفون',ex:'Ich telefoniere jeden Tag mit meiner Mutter.',lvl:'A1'},
  {v:'träumen',p:[['von','D']],ar:'يحلم بـ',ex:'Sie träumt von einem Haus am Meer.',lvl:'A2'},
  {v:'überzeugen',p:[['von','D']],ar:'يقنع بـ',ex:'Er hat mich von seiner Idee überzeugt.',lvl:'B1'},
  {v:'umgehen',p:[['mit','D']],ar:'يتعامل مع',ex:'Sie kann gut mit Kindern umgehen.',lvl:'B1'},
  {v:'verzichten',p:[['auf','A']],ar:'يستغنى عن',ex:'Ich verzichte auf Zucker.',lvl:'B1'},
  {v:'warnen',p:[['vor','D']],ar:'يحذّر من',ex:'Die Polizei warnt vor dem Glatteis.',lvl:'B1'},
  {v:'warten',p:[['auf','A']],ar:'ينتظر',ex:'Ich warte auf den Bus.',lvl:'A1'},
  {v:'zählen',p:[['zu','D']],ar:'يُعتبر من',ex:'Berlin zählt zu den größten Städten Europas.',lvl:'B1'},
  {v:'zweifeln',p:[['an','D']],ar:'يشك في',ex:'Ich zweifle an seiner Ehrlichkeit.',lvl:'B1'},
  {v:'Angst haben',p:[['vor','D']],ar:'يخاف من',ex:'Ich habe Angst vor Spinnen.',lvl:'A2'},
  {v:'Lust haben',p:[['auf','A']],ar:'نفسه في / مزاجه لـ',ex:'Hast du Lust auf Pizza?',lvl:'A1'},
  {v:'Zeit haben',p:[['für','A']],ar:'فاضي لـ',ex:'Ich habe heute keine Zeit für dich.',lvl:'A1'},
  {v:'Interesse haben',p:[['an','D']],ar:'مهتم بـ',ex:'Wir haben großes Interesse an Ihrem Angebot.',lvl:'B1'},
  {v:'stolz sein',p:[['auf','A']],ar:'فخور بـ',ex:'Ich bin stolz auf meine Tochter.',lvl:'A2'},
  {v:'zufrieden sein',p:[['mit','D']],ar:'راضي عن',ex:'Bist du mit dem Ergebnis zufrieden?',lvl:'A2'},
  {v:'verheiratet sein',p:[['mit','D']],ar:'متجوز من',ex:'Sie ist mit einem Arzt verheiratet.',lvl:'A2'},
  {v:'fertig sein',p:[['mit','D']],ar:'خلص من',ex:'Bist du schon mit dem Essen fertig?',lvl:'A2'},
  {v:'böse sein',p:[['auf','A']],ar:'زعلان من',ex:'Bist du noch böse auf mich?',lvl:'A2'},
  {v:'verantwortlich sein',p:[['für','A']],ar:'مسؤول عن',ex:'Wer ist für die Planung verantwortlich?',lvl:'B1'},
  {v:'gespannt sein',p:[['auf','A']],ar:'مستني بفضول',ex:'Ich bin gespannt auf das Ergebnis.',lvl:'B1'}
];

window.BAUSTEINE.dativeVerbs = [
  {v:'helfen',ar:'يساعد',ex:'Kannst du mir helfen?',lvl:'A1'},
  {v:'danken',ar:'يشكر',ex:'Ich danke Ihnen für alles.',lvl:'A1'},
  {v:'gefallen',ar:'يعجب',ex:'Die Wohnung gefällt mir sehr.',lvl:'A1'},
  {v:'gehören',ar:'ملك لـ',ex:'Wem gehört das Fahrrad? – Es gehört meinem Bruder.',lvl:'A1'},
  {v:'schmecken',ar:'يعجبه طعمه',ex:'Schmeckt dir die Suppe?',lvl:'A1'},
  {v:'passen',ar:'يناسب (مقاس / ميعاد)',ex:'Passt dir Montag um zehn?',lvl:'A1'},
  {v:'gehen (es geht)',ar:'حاله (إزيك)',ex:'Wie geht es dir? – Mir geht es gut.',lvl:'A1'},
  {v:'antworten',ar:'يرد على شخص',ex:'Warum antwortest du mir nicht?',lvl:'A1'},
  {v:'gratulieren',ar:'يهنّي',ex:'Wir gratulieren dir zur Hochzeit!',lvl:'A2'},
  {v:'fehlen',ar:'ناقص / واحشه',ex:'Du fehlst mir sehr.',lvl:'A2'},
  {v:'wehtun',ar:'يوجع',ex:'Mir tut der Kopf weh.',lvl:'A1'},
  {v:'leidtun',ar:'يأسف (أنا آسف)',ex:'Es tut mir leid.',lvl:'A1'},
  {v:'stehen',ar:'لايق على',ex:'Das Kleid steht dir gut.',lvl:'A2'},
  {v:'glauben',ar:'يصدّق شخص',ex:'Glaub mir, das ist wahr!',lvl:'A2'},
  {v:'vertrauen',ar:'يثق في',ex:'Ich vertraue meinen Freunden.',lvl:'B1'},
  {v:'folgen',ar:'يتبع / يمشي ورا',ex:'Bitte folgen Sie mir!',lvl:'A2'},
  {v:'begegnen',ar:'يقابل صدفة',ex:'Gestern bin ich meinem Lehrer begegnet.',lvl:'B1'},
  {v:'passieren',ar:'يحصل لـ',ex:'Was ist dir passiert?',lvl:'A2'},
  {v:'gelingen',ar:'ينجح في',ex:'Der Kuchen ist mir gut gelungen.',lvl:'B1'},
  {v:'zuhören',ar:'يسمع لـ / ينصت',ex:'Hör mir bitte zu!',lvl:'A2'},
  {v:'zustimmen',ar:'يوافق شخص',ex:'Da stimme ich dir zu.',lvl:'A2'},
  {v:'widersprechen',ar:'يعارض',ex:'Ich muss Ihnen widersprechen.',lvl:'B1'},
  {v:'zuschauen / zusehen',ar:'يتفرج على',ex:'Ich schaue den Kindern beim Spielen zu.',lvl:'A2'},
  {v:'raten',ar:'ينصح',ex:'Ich rate dir, früher ins Bett zu gehen.',lvl:'B1'},
  {v:'schaden',ar:'يضر',ex:'Rauchen schadet der Gesundheit.',lvl:'B1'},
  {v:'nützen',ar:'يفيد',ex:'Das nützt mir nichts.',lvl:'B1'},
  {v:'guttun',ar:'يفيد / يريّح',ex:'Der Urlaub hat mir gutgetan.',lvl:'B1'},
  {v:'verzeihen',ar:'يسامح',ex:'Verzeih mir bitte!',lvl:'B1'},
  {v:'einfallen',ar:'ييجي على باله',ex:'Mir fällt sein Name nicht ein.',lvl:'B1'},
  {v:'auffallen',ar:'يلفت نظره',ex:'Ist dir etwas aufgefallen?',lvl:'B1'},
  {v:'vorkommen',ar:'يبان له',ex:'Das kommt mir komisch vor.',lvl:'B1'},
  {v:'reichen',ar:'يكفي',ex:'Das reicht mir.',lvl:'A2'},
  {v:'genügen',ar:'يكفي',ex:'Eine Stunde genügt mir.',lvl:'B1'},
  {v:'gleichen',ar:'يشبه',ex:'Er gleicht seinem Vater.',lvl:'B1'},
  {v:'drohen',ar:'يهدد',ex:'Der Chef droht ihm mit der Kündigung.',lvl:'B1'},
  {v:'kündigen',ar:'يفصل من الشغل',ex:'Die Firma hat ihm gekündigt.',lvl:'B1'},
  {v:'absagen',ar:'يعتذر عن / يلغي لشخص',ex:'Ich muss dir leider absagen.',lvl:'A2'},
  {v:'zusagen',ar:'يوافق على دعوة',ex:'Sie hat mir sofort zugesagt.',lvl:'B1'},
  {v:'winken',ar:'يشاور لـ',ex:'Das Kind winkt seiner Mutter.',lvl:'A2'},
  {v:'sein (+ Gefühl)',ar:'حاسس بـ (مِي بارد)',ex:'Mir ist kalt. – Ist dir schlecht?',lvl:'A1'},
  {v:'egal sein',ar:'ميفرقش معاه',ex:'Das ist mir egal.',lvl:'A2'},
  {v:'wichtig sein',ar:'مهم بالنسبة له',ex:'Die Familie ist mir wichtig.',lvl:'A2'},
  {v:'recht sein',ar:'مناسب له',ex:'Ist es Ihnen recht, wenn ich später komme?',lvl:'B1'}
];

window.BAUSTEINE.dativeAccusativeVerbs = [
  {v:'geben',ar:'يدي',ex:'Ich gebe dem Kind einen Apfel.',lvl:'A1'},
  {v:'schenken',ar:'يهادي',ex:'Wir schenken unserer Mutter Blumen.',lvl:'A1'},
  {v:'schicken',ar:'يبعت',ex:'Kannst du mir die Adresse schicken?',lvl:'A1'},
  {v:'bringen',ar:'يجيب',ex:'Der Kellner bringt dem Gast die Rechnung.',lvl:'A1'},
  {v:'zeigen',ar:'يوري',ex:'Ich zeige dir meine Fotos.',lvl:'A1'},
  {v:'erklären',ar:'يشرح',ex:'Der Lehrer erklärt den Schülern die Regel.',lvl:'A2'},
  {v:'empfehlen',ar:'يرشّح / ينصح بـ',ex:'Können Sie mir ein Restaurant empfehlen?',lvl:'A2'},
  {v:'erzählen',ar:'يحكي',ex:'Oma erzählt den Kindern eine Geschichte.',lvl:'A2'},
  {v:'sagen',ar:'يقول',ex:'Sag mir bitte die Wahrheit!',lvl:'A1'},
  {v:'schreiben',ar:'يكتب',ex:'Ich schreibe meinem Freund eine Nachricht.',lvl:'A1'},
  {v:'kaufen',ar:'يشتري لـ',ex:'Er kauft seiner Frau einen Ring.',lvl:'A1'},
  {v:'leihen',ar:'يسلّف',ex:'Kannst du mir dein Fahrrad leihen?',lvl:'A2'},
  {v:'anbieten',ar:'يعرض على',ex:'Darf ich Ihnen einen Kaffee anbieten?',lvl:'A2'},
  {v:'beschreiben',ar:'يوصف',ex:'Beschreib mir bitte den Weg.',lvl:'A2'},
  {v:'bestellen',ar:'يطلب لـ',ex:'Ich bestelle dir eine Pizza.',lvl:'A2'},
  {v:'besorgen',ar:'يجيب / يوفّر',ex:'Kannst du mir ein Ticket besorgen?',lvl:'B1'},
  {v:'holen',ar:'يجيب',ex:'Ich hole dir ein Glas Wasser.',lvl:'A2'},
  {v:'mitbringen',ar:'يجيب معاه',ex:'Bring mir bitte Brot mit!',lvl:'A1'},
  {v:'verkaufen',ar:'يبيع',ex:'Er verkauft seinem Nachbarn das alte Auto.',lvl:'A2'},
  {v:'versprechen',ar:'يوعد',ex:'Ich verspreche dir, dass ich komme.',lvl:'A2'},
  {v:'wünschen',ar:'يتمنى لـ',ex:'Ich wünsche dir viel Glück!',lvl:'A1'},
  {v:'zurückgeben',ar:'يرجّع',ex:'Gib mir bitte mein Buch zurück.',lvl:'A2'},
  {v:'erlauben',ar:'يسمح',ex:'Die Eltern erlauben dem Sohn die Party.',lvl:'A2'},
  {v:'verbieten',ar:'يمنع',ex:'Der Arzt verbietet ihm das Rauchen.',lvl:'A2'},
  {v:'beibringen',ar:'يعلّم',ex:'Mein Vater hat mir das Schwimmen beigebracht.',lvl:'B1'},
  {v:'vorlesen',ar:'يقرأ بصوت لـ',ex:'Ich lese meiner Tochter ein Buch vor.',lvl:'A2'},
  {v:'vorstellen',ar:'يعرّف (شخص على شخص)',ex:'Ich stelle dir meine Freundin vor.',lvl:'A2'},
  {v:'mitteilen',ar:'يبلّغ',ex:'Bitte teilen Sie uns Ihre neue Adresse mit.',lvl:'B1'},
  {v:'wegnehmen',ar:'ياخد من',ex:'Nimm dem Hund den Ball nicht weg!',lvl:'B1'},
  {v:'schulden',ar:'مديون لـ',ex:'Ich schulde dir noch zehn Euro.',lvl:'B1'},
  {v:'reichen',ar:'يناول',ex:'Reichst du mir bitte das Salz?',lvl:'B1'},
  {v:'stehlen',ar:'يسرق من',ex:'Jemand hat mir das Handy gestohlen.',lvl:'B1'}
];

window.BAUSTEINE.dativeAccusativeOrder = [
  {rule:'Zwei Nomen: Dativ vor Akkusativ',ar:'اسمين: الداتيف (الشخص) قبل الأكوزاتيف (الحاجة)',ex:'Ich gebe dem Kind den Ball.'},
  {rule:'Zwei Pronomen: Akkusativ vor Dativ',ar:'ضميرين: الأكوزاتيف الأول',ex:'Ich gebe ihn ihm.'},
  {rule:'Pronomen vor Nomen',ar:'الضمير دايمًا قبل الاسم',ex:'Ich gebe ihm den Ball. – Ich gebe ihn dem Kind.'}
];

window.BAUSTEINE.connectors = [
  {id:'pos0',title:'Position 0 – Hauptsatz bleibt normal',titleAr:'أدوات مكانها صفر: الجملة بعدها عادية',
    rule:'Konnektor + Subjekt + Verb …',ruleAr:'الأداة مش بتاخد مكان، فالفعل يفضل في المكان التاني بعد الفاعل. احفظها بكلمة ADUSO: aber, denn, und, sondern, oder.',
    items:[
      {w:'und',ar:'و',ex:'Ich koche, und du deckst den Tisch.'},
      {w:'aber',ar:'لكن',ex:'Ich möchte kommen, aber ich habe keine Zeit.'},
      {w:'oder',ar:'أو',ex:'Trinkst du Tee, oder möchtest du Kaffee?'},
      {w:'denn',ar:'لأن (سبب – الفعل مش بيروح آخر الجملة)',ex:'Ich bleibe zu Hause, denn ich bin krank.'},
      {w:'sondern',ar:'بل (بعد النفي)',ex:'Er kommt nicht heute, sondern er kommt morgen.'},
      {w:'doch',ar:'لكن / ومع ذلك',ex:'Ich habe ihn angerufen, doch er war nicht da.'}
    ]},
  {id:'nebensatz',title:'Nebensatz – Verb am Ende',titleAr:'أدوات الجملة الفرعية: الفعل المصرّف في الآخر',
    rule:'…, Konnektor + Subjekt + … + Verb.',ruleAr:'بعد الأداة: الفاعل بدري والفعل المصرّف آخر حاجة. لو الجملة الفرعية جت الأول، الجملة الرئيسية تبدأ بالفعل: Weil ich krank bin, bleibe ich zu Hause.',
    items:[
      {w:'weil',ar:'لأن',ex:'Ich bleibe zu Hause, weil ich krank bin.'},
      {w:'da',ar:'بما إن',ex:'Da es regnet, nehmen wir den Bus.'},
      {w:'dass',ar:'إن / أن',ex:'Ich finde, dass Deutsch interessant ist.'},
      {w:'ob',ar:'إذا كان / هل (سؤال غير مباشر)',ex:'Weißt du, ob der Laden heute offen ist?'},
      {w:'wenn',ar:'لو / لما (كل مرة أو مستقبل)',ex:'Wenn ich Zeit habe, rufe ich dich an.'},
      {w:'als',ar:'لما (مرة واحدة في الماضي)',ex:'Als ich zehn war, sind wir umgezogen.'},
      {w:'obwohl',ar:'رغم إن',ex:'Er geht spazieren, obwohl es regnet.'},
      {w:'damit',ar:'عشان (هدف – فاعلين مختلفين)',ex:'Ich erkläre es langsam, damit du es verstehst.'},
      {w:'bevor',ar:'قبل ما',ex:'Bevor ich schlafe, lese ich ein bisschen.'},
      {w:'nachdem',ar:'بعد ما (+ Perfekt / Plusquamperfekt)',ex:'Nachdem ich gegessen hatte, bin ich gegangen.'},
      {w:'während',ar:'في حين / أثناء ما',ex:'Während ich koche, hört er Musik.'},
      {w:'seit / seitdem',ar:'من ساعة ما',ex:'Seitdem ich in Berlin wohne, fahre ich Fahrrad.'},
      {w:'bis',ar:'لحد ما',ex:'Warte hier, bis ich zurückkomme.'},
      {w:'sobald',ar:'أول ما',ex:'Sobald ich ankomme, schreibe ich dir.'},
      {w:'falls',ar:'في حالة إن',ex:'Falls du Hilfe brauchst, ruf mich an.'},
      {w:'sodass / so … dass',ar:'لدرجة إن / بحيث',ex:'Es war so laut, dass ich nicht schlafen konnte.'},
      {w:'indem',ar:'عن طريق إن',ex:'Man lernt Wörter, indem man sie oft wiederholt.'},
      {w:'ohne dass',ar:'من غير ما',ex:'Er ist gegangen, ohne dass er sich verabschiedet hat.'},
      {w:'statt dass',ar:'بدل ما',ex:'Statt dass er hilft, sieht er fern.'},
      {w:'W-Wort (indirekte Frage)',ar:'سؤال غير مباشر',ex:'Kannst du mir sagen, wo der Bahnhof ist?'},
      {w:'der / die / das (Relativsatz)',ar:'اللي (جملة صلة)',ex:'Das ist der Mann, der neben mir wohnt.'}
    ]},
  {id:'pos1',title:'Position 1 – danach kommt sofort das Verb',titleAr:'أدوات مكانها الأول: بعدها الفعل على طول ثم الفاعل',
    rule:'Konnektor + Verb + Subjekt …',ruleAr:'الأداة بتاخد المكان الأول، فالفعل ييجي بعدها مباشرة والفاعل بعد الفعل (Inversion).',
    items:[
      {w:'deshalb / deswegen / darum',ar:'علشان كده',ex:'Ich bin krank, deshalb bleibe ich zu Hause.'},
      {w:'daher',ar:'لذلك',ex:'Der Zug hatte Verspätung, daher kam ich zu spät.'},
      {w:'trotzdem',ar:'ومع ذلك / برضه',ex:'Es regnet, trotzdem gehen wir spazieren.'},
      {w:'dann',ar:'بعدين / ساعتها',ex:'Zuerst lerne ich, dann gehe ich ins Kino.'},
      {w:'danach',ar:'بعد كده',ex:'Wir essen, danach machen wir einen Spaziergang.'},
      {w:'zuerst',ar:'في الأول',ex:'Zuerst trinke ich einen Kaffee.'},
      {w:'außerdem',ar:'بالإضافة لكده',ex:'Die Wohnung ist groß, außerdem ist sie billig.'},
      {w:'also',ar:'يعني / إذن',ex:'Es ist schon spät, also gehe ich jetzt.'},
      {w:'sonst',ar:'وإلا',ex:'Beeil dich, sonst verpasst du den Bus.'},
      {w:'stattdessen',ar:'بدل كده',ex:'Ich hatte keine Zeit, stattdessen hat mein Bruder eingekauft.'},
      {w:'dagegen',ar:'في المقابل',ex:'Ich mag Kaffee, meine Frau trinkt dagegen lieber Tee.'},
      {w:'inzwischen',ar:'في الأثناء دي / لحد دلوقتي',ex:'Ich koche, inzwischen kannst du den Tisch decken.'},
      {w:'vorher',ar:'قبلها',ex:'Wir gehen ins Kino, vorher essen wir etwas.'},
      {w:'schließlich / zum Schluss',ar:'في الآخر',ex:'Schließlich haben wir eine Wohnung gefunden.'},
      {w:'trotzdem vs. obwohl',ar:'نفس المعنى – بس obwohl الفعل آخر الجملة',ex:'Es regnet, trotzdem gehe ich. = Ich gehe, obwohl es regnet.'}
    ]},
  {id:'zweiteilig',title:'Zweiteilige Konnektoren',titleAr:'أدوات من جزئين',
    rule:'Teil 1 … Teil 2 …',ruleAr:'الأداة جزئين بيربطوا حاجتين ببعض.',
    items:[
      {w:'entweder … oder',ar:'يا … يا',ex:'Entweder wir fahren mit dem Bus oder wir laufen.'},
      {w:'sowohl … als auch',ar:'… وكمان …',ex:'Sie spricht sowohl Deutsch als auch Englisch.'},
      {w:'weder … noch',ar:'لا … ولا',ex:'Ich trinke weder Kaffee noch Tee.'},
      {w:'nicht nur … sondern auch',ar:'مش بس … لكن كمان',ex:'Er ist nicht nur nett, sondern auch klug.'},
      {w:'zwar … aber',ar:'صحيح إن … لكن',ex:'Die Wohnung ist zwar klein, aber sehr gemütlich.'},
      {w:'je … desto',ar:'كل ما … كل ما',ex:'Je mehr ich lerne, desto besser spreche ich.'},
      {w:'einerseits … andererseits',ar:'من ناحية … ومن ناحية تانية',ex:'Einerseits ist die Stadt schön, andererseits ist sie teuer.'}
    ]},
  {id:'infinitiv',title:'Infinitivsätze mit zu',titleAr:'جمل المصدر مع zu',
    rule:'…, um / ohne / statt … zu + Infinitiv.',ruleAr:'نفس الفاعل في الجملتين، والفعل بصيغة المصدر مع zu في الآخر.',
    items:[
      {w:'um … zu',ar:'عشان (هدف – نفس الفاعل)',ex:'Ich lerne Deutsch, um in Deutschland zu arbeiten.'},
      {w:'ohne … zu',ar:'من غير ما',ex:'Er ist gegangen, ohne etwas zu sagen.'},
      {w:'statt … zu',ar:'بدل ما',ex:'Statt zu lernen, spielt er am Handy.'},
      {w:'Es ist … zu',ar:'(من ال…) إنك …',ex:'Es ist schwer, früh aufzustehen.'},
      {w:'Ich habe Lust / Zeit, … zu',ar:'عندي مزاج / وقت إني …',ex:'Hast du Lust, heute Abend zu kochen?'}
    ]}
];

window.BAUSTEINE.questions = [
  {w:'Wer?',use:'Person – Nominativ',ar:'مين؟ (فاعل)',ex:'Wer kommt heute?',ans:'Meine Schwester kommt.'},
  {w:'Wen?',use:'Person – Akkusativ',ar:'مين؟ (مفعول به)',ex:'Wen besuchst du?',ans:'Ich besuche meinen Onkel.'},
  {w:'Wem?',use:'Person – Dativ',ar:'لمين؟ / مع مين؟',ex:'Wem hilfst du?',ans:'Ich helfe meiner Nachbarin.'},
  {w:'Wessen?',use:'Besitz – Genitiv',ar:'بتاع مين؟',ex:'Wessen Tasche ist das?',ans:'Das ist die Tasche von Anna.'},
  {w:'Was?',use:'Sache',ar:'إيه؟',ex:'Was machst du am Wochenende?',ans:'Ich besuche Freunde.'},
  {w:'Wo?',use:'Ort (Position) – Dativ',ar:'فين؟',ex:'Wo wohnst du?',ans:'Ich wohne in Köln.'},
  {w:'Wohin?',use:'Richtung – Akkusativ',ar:'على فين؟',ex:'Wohin fährst du im Sommer?',ans:'Ich fahre ans Meer.'},
  {w:'Woher?',use:'Herkunft',ar:'منين؟',ex:'Woher kommst du?',ans:'Ich komme aus Ägypten.'},
  {w:'Wann?',use:'Zeitpunkt',ar:'إمتى؟',ex:'Wann beginnt der Kurs?',ans:'Am Montag.'},
  {w:'Um wie viel Uhr?',use:'Uhrzeit',ar:'الساعة كام؟ (ميعاد)',ex:'Um wie viel Uhr treffen wir uns?',ans:'Um halb acht.'},
  {w:'Wie spät ist es?',use:'aktuelle Uhrzeit',ar:'الساعة كام دلوقتي؟',ex:'Wie spät ist es?',ans:'Es ist Viertel nach drei.'},
  {w:'Seit wann?',use:'Beginn bis jetzt',ar:'من إمتى؟',ex:'Seit wann lernst du Deutsch?',ans:'Seit einem Jahr.'},
  {w:'Bis wann?',use:'Ende',ar:'لحد إمتى؟',ex:'Bis wann ist die Bibliothek offen?',ans:'Bis 20 Uhr.'},
  {w:'Ab wann?',use:'Beginn in der Zukunft',ar:'من إمتى؟ (قدام)',ex:'Ab wann ist die Wohnung frei?',ans:'Ab dem ersten Mai.'},
  {w:'Wie lange?',use:'Dauer',ar:'قد إيه؟ (مدة)',ex:'Wie lange dauert die Fahrt?',ans:'Etwa zwei Stunden.'},
  {w:'Wie oft?',use:'Häufigkeit',ar:'كام مرة؟',ex:'Wie oft gehst du ins Fitnessstudio?',ans:'Dreimal pro Woche.'},
  {w:'Warum? / Wieso? / Weshalb?',use:'Grund',ar:'ليه؟',ex:'Warum kommst du so spät?',ans:'Weil der Bus Verspätung hatte.'},
  {w:'Wozu?',use:'Zweck',ar:'لإيه؟ / الهدف إيه؟',ex:'Wozu brauchst du das Geld?',ans:'Um ein Fahrrad zu kaufen.'},
  {w:'Wie?',use:'Art und Weise',ar:'إزاي؟',ex:'Wie kommst du zur Arbeit?',ans:'Mit der U-Bahn.'},
  {w:'Wie viel?',use:'Menge (nicht zählbar) / Preis',ar:'كام؟ / قد إيه؟',ex:'Wie viel kostet das?',ans:'Zwölf Euro.'},
  {w:'Wie viele?',use:'Anzahl (zählbar, Plural)',ar:'كام (عدد)؟',ex:'Wie viele Geschwister hast du?',ans:'Zwei Brüder.'},
  {w:'Wie alt?',use:'Alter',ar:'عندك كام سنة؟',ex:'Wie alt bist du?',ans:'Ich bin 25.'},
  {w:'Wie weit?',use:'Entfernung',ar:'قد إيه بعيد؟',ex:'Wie weit ist es bis zum Bahnhof?',ans:'Ungefähr einen Kilometer.'},
  {w:'Welcher / Welche / Welches?',use:'Auswahl (wie der/die/das)',ar:'أنهي؟',ex:'Welches Kleid gefällt dir?',ans:'Das rote.'},
  {w:'Was für ein / eine?',use:'Art / Sorte',ar:'نوعه إيه؟',ex:'Was für ein Auto hast du?',ans:'Einen kleinen Elektrowagen.'},
  {w:'Wo(r) + Präposition',use:'Sache bei Präpositionalverben',ar:'للحاجات: wo + حرف الجر',ex:'Worauf wartest du? – Womit fährst du?',ans:'Auf den Bus. – Mit dem Zug.'},
  {w:'Präposition + wen / wem',use:'Person bei Präpositionalverben',ar:'للأشخاص: حرف الجر + wen/wem',ex:'Auf wen wartest du? – Mit wem sprichst du?',ans:'Auf meinen Freund. – Mit meiner Chefin.'}
];

window.BAUSTEINE.prepositions = [
  {id:'akk',title:'Immer Akkusativ',titleAr:'دايمًا أكوزاتيف',mnemonic:'DOGFU + bis, entlang',items:[
    {p:'durch',ar:'من خلال / عبر',ex:'Wir gehen durch den Park.'},
    {p:'für',ar:'لـ / علشان',ex:'Das Geschenk ist für meinen Vater.'},
    {p:'gegen',ar:'ضد / حوالي (وقت)',ex:'Ich bin gegen den Plan. – Ich komme gegen acht.'},
    {p:'ohne',ar:'من غير',ex:'Ich trinke Kaffee ohne Zucker.'},
    {p:'um',ar:'حوالين / الساعة',ex:'Wir sitzen um den Tisch. – Um 9 Uhr.'},
    {p:'bis',ar:'لحد',ex:'Der Zug fährt bis München.'},
    {p:'entlang',ar:'على طول (بعد الاسم)',ex:'Gehen Sie die Straße entlang.'}
  ]},
  {id:'dat',title:'Immer Dativ',titleAr:'دايمًا داتيف',mnemonic:'aus, bei, mit, nach, seit, von, zu (+ gegenüber, ab, außer)',items:[
    {p:'aus',ar:'من (أصل / من جوه)',ex:'Ich komme aus der Türkei. – Er kommt aus dem Haus.'},
    {p:'bei',ar:'عند',ex:'Ich wohne bei meinen Eltern. – Er arbeitet bei Siemens.'},
    {p:'mit',ar:'مع / بـ (وسيلة)',ex:'Ich fahre mit dem Bus.'},
    {p:'nach',ar:'بعد / إلى (مدن وبلاد من غير أداة)',ex:'Nach dem Essen fahre ich nach Hause.'},
    {p:'seit',ar:'من (مدة لسه مستمرة)',ex:'Ich lerne seit einem Jahr Deutsch.'},
    {p:'von',ar:'من / عن',ex:'Das ist ein Geschenk von meiner Freundin.'},
    {p:'zu',ar:'إلى (أشخاص وأماكن)',ex:'Ich gehe zum Arzt. – Ich fahre zu meiner Oma.'},
    {p:'gegenüber',ar:'قصاد',ex:'Die Bank ist gegenüber dem Bahnhof.'},
    {p:'ab',ar:'ابتداءً من',ex:'Ab nächster Woche arbeite ich Vollzeit.'},
    {p:'außer',ar:'ما عدا',ex:'Außer meinem Bruder kommen alle.'}
  ]},
  {id:'wechsel',title:'Wechselpräpositionen: Wo? → Dativ · Wohin? → Akkusativ',titleAr:'حروف الجر المتغيرة: فين؟ داتيف – على فين؟ أكوزاتيف',mnemonic:'an, auf, hinter, in, neben, über, unter, vor, zwischen',items:[
    {p:'an',ar:'على (سطح رأسي / حافة)',wo:'Das Bild hängt an der Wand.',wohin:'Ich hänge das Bild an die Wand.'},
    {p:'auf',ar:'على (سطح أفقي)',wo:'Das Buch liegt auf dem Tisch.',wohin:'Ich lege das Buch auf den Tisch.'},
    {p:'hinter',ar:'ورا',wo:'Der Garten ist hinter dem Haus.',wohin:'Die Katze läuft hinter das Haus.'},
    {p:'in',ar:'في / جوه',wo:'Ich bin im Kino.',wohin:'Ich gehe ins Kino.'},
    {p:'neben',ar:'جنب',wo:'Die Lampe steht neben dem Sofa.',wohin:'Ich stelle die Lampe neben das Sofa.'},
    {p:'über',ar:'فوق (من غير لمس)',wo:'Die Lampe hängt über dem Tisch.',wohin:'Ich hänge die Lampe über den Tisch.'},
    {p:'unter',ar:'تحت',wo:'Der Hund schläft unter dem Tisch.',wohin:'Der Hund legt sich unter den Tisch.'},
    {p:'vor',ar:'قدام / قبل',wo:'Das Auto steht vor der Tür.',wohin:'Ich stelle das Auto vor die Tür.'},
    {p:'zwischen',ar:'بين',wo:'Das Café liegt zwischen der Bank und der Post.',wohin:'Ich setze mich zwischen dich und Anna.'}
  ]},
  {id:'gen',title:'Genitiv (B1)',titleAr:'جينيتيف (مستوى B1)',mnemonic:'wegen, trotz, während, statt, innerhalb, außerhalb',items:[
    {p:'wegen',ar:'بسبب',ex:'Wegen des Regens bleiben wir zu Hause.'},
    {p:'trotz',ar:'رغم',ex:'Trotz des Regens gehen wir spazieren.'},
    {p:'während',ar:'أثناء',ex:'Während des Essens spricht er nicht.'},
    {p:'(an)statt',ar:'بدلًا من',ex:'Statt eines Autos kauft er ein Fahrrad.'},
    {p:'innerhalb',ar:'خلال / جوه',ex:'Innerhalb einer Woche bekommen Sie Antwort.'},
    {p:'außerhalb',ar:'برا',ex:'Wir wohnen außerhalb der Stadt.'},
    {p:'aufgrund',ar:'بسبب / بناءً على',ex:'Aufgrund der Verspätung fällt der Anschluss aus.'}
  ]}
];

window.BAUSTEINE.positionVerbs = [
  {wo:'stehen (stand, hat gestanden)',wohin:'stellen (stellte, hat gestellt)',ar:'واقف / يوقّف حاجة'},
  {wo:'liegen (lag, hat gelegen)',wohin:'legen (legte, hat gelegt)',ar:'نايم / يحط حاجة نايمة'},
  {wo:'sitzen (saß, hat gesessen)',wohin:'(sich) setzen (setzte, hat gesetzt)',ar:'قاعد / يقعّد'},
  {wo:'hängen (hing, hat gehangen)',wohin:'hängen (hängte, hat gehängt)',ar:'متعلّق / يعلّق'},
  {wo:'stecken (steckte, hat gesteckt)',wohin:'stecken (steckte, hat gesteckt)',ar:'محطوط جوه / يدخّل'}
];

window.BAUSTEINE.contractions = [
  ['an + dem','am'],['an + das','ans'],['in + dem','im'],['in + das','ins'],
  ['bei + dem','beim'],['von + dem','vom'],['zu + dem','zum'],['zu + der','zur'],['auf + das','aufs']
];
