/* Original A1.2 learning content aligned with the six Netzwerk neu A1.2 themes (Kapitel 7-12).
   Vocabulary follows the thematische Wortgruppen of the course book. */
(() => {
const V=(w,d,ex,ar)=>({w,d,ex,ar});
const RM=(cat,catAr,items)=>({cat,catAr,items:items.map(([de,ar])=>({de,ar}))});
const READ=(kind,title,text,ar,glossary,questions)=>({kind,title,text,ar,glossary,questions});
const GR=(t,tAr,body)=>({t,tAr,body});
const S=(de,ar)=>({de,ar});
const Q=(q,o,a,fb,fbAr)=>({q,o,a,fb,fbAr});

const A1_2_CHAPTERS = [
{
num:7, route:"a1/k7", title:"Arbeitsalltag", titleAr:"يوم العمل والروتين المهني",
subtitle:"Arbeitsplatz · Ortsangaben · Bank · Medien · Dativ",
intro:"Du verstehst einen Blogeintrag über den Arbeitsalltag und schreibst selbst darüber. Du verstehst Gespräche am Arbeitsplatz, machst Ortsangaben, beschreibst Abläufe, beantwortest kurze Briefe und führst Small Talk.",
introAr:"هتتعلم تتكلم وتكتب عن يوم العمل، تفهم كلام في الشغل، تقول مكان الأشياء، توصف خطوات، ترد على إيميل قصير، وتعمل سمول توك.",
badges:["Arbeitsplatz","Dativ","Präposition mit","Ortsangaben","und/oder/aber","Small Talk"],
goals:[S("über den Arbeitsalltag sprechen und schreiben","تتكلم وتكتب عن روتين الشغل"),S("Gespräche am Arbeitsplatz verstehen","تفهم محادثات في مكان العمل"),S("Ortsangaben mit Präpositionen machen","تقول مكان الأشياء بحروف الجر"),S("Sätze mit und, oder, aber verbinden","تربط الجمل بـ und و oder و aber"),S("den Artikel im Dativ benutzen","تستخدم أداة التعريف في الـ Dativ")],
vocab:[
 V("der Arbeitsplatz, -e","Der Ort, wo man arbeitet.","Mein Arbeitsplatz ist im Büro.","مكان الشغل"),
 V("der Arbeitsalltag","Der normale Arbeitstag.","Mein Arbeitsalltag ist voll.","روتين الشغل"),
 V("das Büro, -s","Ein Raum zum Arbeiten.","Ich arbeite im Büro.","مكتب (مكان)"),
 V("der Kollege, -n","Ein Mann bei der Arbeit.","Mein Kollege hilft mir.","زميل"),
 V("die Kollegin, -nen","Eine Frau bei der Arbeit.","Meine Kollegin ist nett.","زميلة"),
 V("der Chef, -s","Der Leiter der Firma.","Mein Chef ist heute da.","المدير"),
 V("die Chefin, -nen","Die Leiterin der Firma.","Die Chefin ist freundlich.","المديرة"),
 V("die Besprechung, -en","Ein Treffen über die Arbeit.","Um zehn ist die Besprechung.","اجتماع"),
 V("die Pause, -n","Eine kurze Zeit ohne Arbeit.","In der Pause trinke ich Kaffee.","استراحة / بريك"),
 V("drucken","Etwas auf Papier machen.","Kannst du das drucken?","يطبع"),
 V("kopieren","Eine Kopie machen.","Ich kopiere den Vertrag.","يصوّر ورق"),
 V("der Drucker, -","Ein Gerät, das druckt.","Der Drucker ist kaputt.","طابعة"),
 V("die Aufgabe, -n","Etwas, das man machen muss.","Ich habe viele Aufgaben.","مهمة / تكليف"),
 V("erledigen","Eine Aufgabe fertig machen.","Ich erledige die E-Mails.","يخلّص مهمة"),
 V("schicken","Etwas zu jemandem senden.","Ich schicke dir die Datei.","يبعت"),
 V("die Datei, -en","Ein Dokument im Computer.","Öffne bitte die Datei.","ملف"),
 V("der Computer, -","Gerät zum Arbeiten und Surfen.","Der Computer steht auf dem Tisch.","كمبيوتر"),
 V("unterschreiben","Den Namen mit der Hand schreiben.","Bitte hier unterschreiben.","يوقّع"),
 V("der Stress","Viel Arbeit und wenig Zeit.","Heute habe ich viel Stress.","ضغط / توتر"),
 V("an","Präposition: direkt bei oder seitlich.","Das Bild hängt an der Wand.","على"),
 V("auf","Präposition: oben auf einer Fläche.","Das Buch liegt auf dem Tisch.","فوق / على"),
 V("unter","Präposition: unterhalb.","Die Tasche ist unter dem Stuhl.","تحت"),
 V("über","Präposition: oberhalb.","Die Lampe hängt über dem Tisch.","فوق (معلق)"),
 V("neben","Direkt an der Seite.","Der Drucker steht neben dem Computer.","جنب"),
 V("vor","An der Vorderseite.","Das Auto steht vor dem Haus.","قدام"),
 V("hinter","An der Rückseite.","Der Garten ist hinter dem Haus.","ورا"),
 V("zwischen","In der Mitte von zwei Dingen.","Die Post ist zwischen Bank und Café.","بين"),
 V("die Ortsangabe, -n","Information, wo etwas ist.","Mach bitte eine genaue Ortsangabe.","تحديد المكان"),
 V("die Bank, -en","Ort für Geld.","Ich gehe zur Bank.","بنك"),
 V("das Konto, Konten","Dein Geldplatz bei der Bank.","Ich habe ein Konto.","حساب بنكي"),
 V("das Geld","Damit bezahlt man.","Ich habe wenig Geld.","فلوس"),
 V("überweisen","Geld elektronisch schicken.","Ich überweise die Miete.","يحوّل فلوس"),
 V("abheben","Geld von der Bank holen.","Ich hebe Geld ab.","يسحب فلوس"),
 V("die EC-Karte, -n","Karte zum Bezahlen.","Ich zahle mit der EC-Karte.","كارت الدفع"),
 V("die Medien","Internet, Zeitung, Radio, TV.","Ich informiere mich über Medien.","وسائل الإعلام"),
 V("das Internet","Das weltweite Netz.","Ich suche im Internet.","الإنترنت"),
 V("die Webseite, -n","Eine Seite im Internet.","Die Webseite ist neu.","موقع إلكتروني"),
 V("das Handy, -s","Das Mobiltelefon.","Mein Handy ist neu.","موبايل"),
 V("die Nachricht, -en","Eine kurze Information.","Ich schicke dir eine Nachricht.","رسالة"),
 V("online","Im Internet verbunden.","Ich bin gerade online.","أونلاين"),
 V("die App, -s","Ein Programm auf dem Handy.","Ich habe eine neue App.","تطبيق"),
 V("der Small Talk","Ein kurzes, lockeres Gespräch.","Im Büro machen wir Small Talk.","دردشة خفيفة"),
 V("das Gespräch, -e","Wenn Menschen miteinander reden.","Wir führen ein Gespräch.","محادثة"),
 V("der Brief, -e","Ein Text auf Papier in einem Umschlag.","Ich schreibe einen Brief.","خطاب / جواب"),
 V("die E-Mail, -s","Eine elektronische Nachricht.","Ich schreibe eine E-Mail.","إيميل"),
 V("beantworten","Eine Antwort geben.","Ich beantworte die E-Mail.","يرد على")
],
redemittel:[
 RM("Am Arbeitsplatz","في مكان العمل",[["Kannst du das bitte drucken?","ممكن تطبع ده من فضلك؟"],["Ich schicke dir die E-Mail.","هبعتلك الإيميل."],["Wann ist die Besprechung?","الاجتماع إمتى؟"],["Der Drucker funktioniert nicht.","الطابعة مش شغالة."]]),
 RM("Ortsangaben","تحديد المكان",[["Die Tasche ist unter dem Tisch.","الشنطة تحت الترابيزة."],["Der Drucker steht neben dem Computer.","الطابعة جنب الكمبيوتر."],["Die Papiere sind in der Schublade.","الأوراق في الدرج."]]),
 RM("Small Talk","الحديث القصير",[["Wie war dein Wochenende?","كان عامل إيه الويك إند؟"],["Schönes Wetter heute, oder?","الجو حلو النهارده، مش كده؟"],["Viel zu tun heute?","شغل كتير النهارده؟"]])
],
readings:[READ("Blog","Ein Tag im Büro",
 "Tarek arbeitet in einer kleinen Firma. Er schreibt in seinem Blog: Mein Arbeitstag beginnt um acht Uhr. Zuerst lese ich die E-Mails und drucke wichtige Dokumente. Um zehn Uhr haben wir eine Besprechung mit dem Chef. In der Pause trinke ich Kaffee mit meiner Kollegin und wir machen ein bisschen Small Talk. Am Nachmittag erledige ich die Telefonate. Der Tag ist oft voll, aber die Arbeit macht mir Spaß.",
 "طارق يعمل في شركة صغيرة. يكتب في مدونته: يومي يبدأ الساعة 8. أول حاجة يقرأ الإيميلات ويطبع المستندات المهمة. الساعة 10 فيه اجتماع مع المدير. في الاستراحة يشرب قهوة مع زميلته ويعملوا سمول توك. بعد الظهر يخلّص المكالمات. اليوم غالبًا مزحوم، بس الشغل بيبسطه.",
 [["zuerst","أولًا"],["wichtig","مهم"],["voll","مزحوم / مليان"]],
 [["Wann beginnt Tareks Arbeitstag?","Um acht Uhr."],["Was macht er zuerst?","Er liest die E-Mails."],["Mit wem trinkt er Kaffee?","Mit seiner Kollegin."]])],
grammar:[
 GR("Artikel im Dativ","أداة التعريف في الـ Dativ",`<p>Nach Präpositionen des Ortes (an, auf, in, neben, unter, über, vor, hinter, zwischen) steht oft der <b>Dativ</b>.</p><div class="gt-wrap"><table class="gt"><tr><th>Nominativ</th><th>Dativ</th></tr><tr><td>der Tisch</td><td>auf dem Tisch</td></tr><tr><td>das Büro</td><td>in dem (im) Büro</td></tr><tr><td>die Schublade</td><td>in der Schublade</td></tr><tr><td>die Papiere (Pl.)</td><td>bei den Papieren</td></tr></table></div>`),
 GR("Sätze verbinden: und, oder, aber","ربط الجمل: und و oder و aber",`<p>Diese Wörter verbinden zwei Sätze. Das Verb bleibt auf Position 2.</p><div class="exbox"><b>und</b> = و: Ich drucke den Brief <b>und</b> ich schicke die E-Mail.<br><b>oder</b> = أو: Trinkst du Kaffee <b>oder</b> möchtest du Tee?<br><b>aber</b> = لكن: Die Arbeit ist viel, <b>aber</b> sie macht Spaß.</p>`),
 GR("Aussprache: s und sch","النطق: s و sch",`<p><b>s</b> vor einem Vokal klingt weich (wie ز): <b>S</b>onne, <b>s</b>agen, le<b>s</b>en.</p><p><b>sch</b> = „”: <b>sch</b>ön, <b>Sch</b>ule, Ti<b>sch</b>. Am Wortanfang spricht man <b>sp</b> und <b>st</b> wie „”: <b>sp</b>rechen, <b>St</b>ress.</p>`)
],
speaking:{questions:[S("Beschreibe deinen Arbeitstag oder Schultag.","اوصف يوم شغلك أو يوم دراستك."),S("Wo sind die Dinge auf deinem Schreibtisch?","فين الحاجات على مكتبك؟"),S("Mach Small Talk über das Wetter und das Wochenende.","اعمل سمول توك عن الجو والويك إند.")],
model:"Mein Arbeitstag beginnt um neun Uhr. Zuerst lese ich die E-Mails und dann drucke ich die Dokumente. Der Computer steht auf dem Tisch und die Papiere sind in der Schublade. Um eins mache ich eine Pause und trinke Kaffee mit meinen Kollegen. Die Arbeit ist viel, aber sie macht mir Spaß.",
modelAr:"يومي يبدأ الساعة 9. أول حاجة أقرأ الإيميلات وبعدها أطبع المستندات. الكمبيوتر على الترابيزة والأوراق في الدرج. الساعة 1 آخد استراحة وأشرب قهوة مع زمايلي. الشغل كتير بس بيبسطني."},
quiz:[Q("Das Buch liegt auf ___ Tisch.",["dem","der","den"],0,"der Tisch -> Dativ: dem.","المذكر في Dativ يبقى dem."),Q("Ich trinke Kaffee ___ Tee?",["oder","und","aber"],0,"Alternative: oder.","البديل بـ oder."),Q("Die Arbeit ist viel, ___ sie macht Spaß.",["aber","oder","und"],0,"Gegensatz: aber.","التناقض بـ aber."),Q("Die Papiere sind in ___ Schublade.",["der","dem","das"],0,"die Schublade -> Dativ: der.","المؤنث في Dativ يبقى der."),Q("Kannst du das bitte ___?",["drucken","trinken","schlafen"],0,"Im Büro: drucken.","في المكتب نقول drucken."),Q("„” spricht man wie ...",["ش","س","ز"],0,"sch = ش.","sch تتنطق ش.")]}
,

{
num:8, route:"a1/k8", title:"Fit und gesund", titleAr:"اللياقة والصحة",
subtitle:"Körperteile · Krankheiten · Medikamente · Imperativ · Modalverben",
intro:"Du sprichst über Körper und Gesundheit, nennst Körperteile, beschreibst Krankheiten und gibst Gesundheitstipps. Du verstehst Gespräche beim Arzt, gibst Anweisungen und benutzt die Modalverben sollen, müssen und dürfen.",
introAr:"هتتكلم عن الجسم والصحة، تسمي أعضاء الجسم، توصف الأمراض، تدّي نصايح صحية، تفهم الكلام عند الدكتور، وتستخدم الأفعال الناقصة sollen و müssen و dürfen.",
badges:["Körperteile","Krankheiten","Imperativ du/Sie","sollen","müssen","dürfen"],
goals:[S("Körperteile nennen","تسمي أعضاء الجسم"),S("über Krankheiten sprechen","تتكلم عن الأمراض"),S("ein Gespräch beim Arzt führen","تعمل حوار عند الدكتور"),S("Aufforderungen mit dem Imperativ geben","تدّي أوامر ونصايح بالـ Imperativ"),S("Modalverben sollen, müssen, dürfen benutzen","تستخدم الأفعال الناقصة")],
vocab:[
 V("der Körper, -","Der ganze Mensch von Kopf bis Fuß.","Sport ist gut für den Körper.","الجسم"),
 V("der Kopf, -e","Oben am Körper.","Mein Kopf tut weh.","الراس"),
 V("das Haar, -e","Wächst auf dem Kopf.","Sie hat lange Haare.","شعر"),
 V("das Gesicht, -er","Die Vorderseite des Kopfes.","Wasch dein Gesicht.","الوش / الوجه"),
 V("das Auge, -n","Damit sieht man.","Meine Augen sind müde.","العين"),
 V("das Ohr, -en","Damit hört man.","Das Ohr tut weh.","الودن / الأذن"),
 V("die Nase, -n","Damit riecht man.","Meine Nase ist verstopft.","المناخير / الأنف"),
 V("der Mund, -er","Damit isst und spricht man.","Mach den Mund auf.","البق / الفم"),
 V("der Zahn, -e","Damit kaut man.","Ich gehe zum Zahnarzt.","السنة / الضرس"),
 V("der Hals, -e","Verbindet Kopf und Körper.","Ich habe Halsschmerzen.","الرقبة / الزور"),
 V("die Schulter, -n","Oben am Arm.","Meine Schulter tut weh.","الكتف"),
 V("der Arm, -e","Von der Schulter zur Hand.","Mein Arm ist gebrochen.","الدراع / الذراع"),
 V("die Hand, -e","Am Ende des Arms.","Wasch dir die Hände.","الإيد / اليد"),
 V("der Finger, -","An der Hand sind fünf.","Mein Finger blutet.","صباع / إصبع"),
 V("der Bauch, -e","Der Teil unter der Brust.","Mein Bauch tut weh.","البطن"),
 V("der Rücken, -","Die Rückseite des Körpers.","Mein Rücken ist müde.","الضهر / الظهر"),
 V("das Bein, -e","Zum Stehen und Gehen.","Das Bein tut weh.","الرجل / الساق"),
 V("das Knie, -","Die Mitte des Beins.","Mein Knie tut beim Laufen weh.","الركبة"),
 V("der Fuß, -e","Am Ende des Beins.","Meine Füße sind kalt.","القدم"),
 V("das Herz, -en","Es schlägt in der Brust.","Sport ist gut für das Herz.","القلب"),
 V("krank","Nicht gesund.","Heute bin ich krank.","عيان / مريض"),
 V("gesund","Nicht krank.","Obst ist gesund.","صحي"),
 V("die Krankheit, -en","Wenn man nicht gesund ist.","Grippe ist eine Krankheit.","مرض"),
 V("die Erkältung, -en","Leichte Krankheit mit Husten.","Ich habe eine Erkältung.","برد"),
 V("die Grippe","Eine stärkere Krankheit mit Fieber.","Bei Grippe bleibt man im Bett.","انفلونزا"),
 V("das Fieber","Hohe Temperatur im Körper.","Das Kind hat Fieber.","سخونية / حُمّى"),
 V("der Husten","Krankheit der Atemwege.","Ich habe Husten.","كحة"),
 V("der Schnupfen","Wenn die Nase läuft.","Bei Erkältung hat man Schnupfen.","رشح / زكام"),
 V("die Schmerzen","Wenn etwas weh tut.","Ich habe starke Schmerzen.","ألم / وجع"),
 V("weh tun","Schmerzen machen.","Mein Bein tut weh.","يوجع"),
 V("sich fühlen","In einem Zustand sein.","Ich fühle mich schlecht.","يحس / يشعر"),
 V("die Apotheke, -n","Geschäft für Medikamente.","Die Tabletten gibt es in der Apotheke.","صيدلية"),
 V("das Medikament, -e","Etwas gegen eine Krankheit.","Nimm dieses Medikament.","دوا"),
 V("die Tablette, -n","Kleines Medikament zum Schlucken.","Nimm zwei Tabletten am Tag.","قرص / حبة"),
 V("der Hustensaft","Flüssiges Medikament gegen Husten.","Der Hustensaft schmeckt süß.","شراب الكحة"),
 V("das Pflaster, -","Klebt auf einer kleinen Wunde.","Ich brauche ein Pflaster.","بلاستر"),
 V("die Salbe, -n","Creme als Medikament.","Die Salbe hilft gegen Schmerzen.","مرهم"),
 V("das Rezept, -e","Papier vom Arzt für Medikamente.","Der Arzt gibt mir ein Rezept.","روشتة"),
 V("der Arzt, -e","Mann, der Kranke behandelt.","Ich gehe zum Arzt.","دكتور"),
 V("die Ärztin, -nen","Frau, die Kranke behandelt.","Die Ärztin ist nett.","دكتورة"),
 V("die Praxis, Praxen","Der Arbeitsort des Arztes.","Die Praxis ist heute geschlossen.","العيادة"),
 V("das Krankenhaus, -er","Großes Gebäude für Kranke.","Er liegt im Krankenhaus.","مستشفى"),
 V("die Krankenschwester, -n","Frau, die im Krankenhaus pflegt.","Die Krankenschwester hilft.","ممرضة"),
 V("sich ausruhen","Pause machen und ruhen.","Ruh dich aus!","يرتاح"),
 V("Gute Besserung!","Wunsch für einen Kranken.","Gute Besserung, Sara!","ألف سلامة"),
 V("untersuchen","Der Arzt schaut den Körper an.","Der Arzt untersucht das Kind.","يكشف / يفحص")
],
redemittel:[
 RM("Beim Arzt","عند الدكتور",[["Was fehlt Ihnen?","إيه اللي تعبان منه؟"],["Ich habe Kopfschmerzen.","عندي صداع."],["Mein Hals tut weh.","حلقي بيوجعني."],["Seit wann haben Sie Fieber?","من إمتى عندك سخونية؟"]]),
 RM("Tipps und Anweisungen","نصايح وأوامر",[["Trink viel Wasser!","اشرب مية كتير!"],["Bleib im Bett und schlaf!","اقعد في السرير ونام!"],["Du sollst zum Arzt gehen.","لازم تروح للدكتور."],["Nimm die Tablette nach dem Essen.","خد الحبة بعد الأكل."]]),
 RM("über Gesundheit","عن الصحة",[["Wie geht es dir heute?","عامل إيه النهارده؟"],["Mir geht es nicht gut.","أنا مش كويس."],["Gute Besserung!","سلامتك / ألف سلامة!"]])
],
readings:[READ("Dialog","Beim Arzt",
 "Frau Klein geht zum Arzt. Der Arzt fragt: Guten Tag, was fehlt Ihnen? Frau Klein sagt: Ich habe Kopfschmerzen und Fieber. Mein Hals tut auch weh. Der Arzt sagt: Sie haben eine Erkältung. Sie müssen viel trinken und im Bett bleiben. Nehmen Sie diese Tabletten zweimal am Tag. Sie dürfen jetzt nicht arbeiten. In drei Tagen sind Sie wieder gesund. Frau Klein sagt: Danke, Herr Doktor.",
 "السيدة كلاين تروح للدكتور. الدكتور يسأل: عندك إيه؟ تقول: عندي صداع وسخونية وحلقي بيوجعني. الدكتور يقول: عندك نزلة برد. لازم تشربي مية كتير وتفضلي في السرير. خدي الأقراص دي مرتين في اليوم. ممنوع تشتغلي دلوقتي. بعد 3 أيام هتبقي كويسة.",
 [["was fehlt Ihnen?","إيه اللي تعبانة منه؟"],["zweimal am Tag","مرتين في اليوم"],["Gute Besserung","سلامتك"]],
 [["Was hat Frau Klein?","Eine Erkältung."],["Was muss sie tun?","Viel trinken und im Bett bleiben."],["Wie oft nimmt sie die Tabletten?","Zweimal am Tag."]])],
grammar:[
 GR("Imperativ mit du und Sie","الأمر مع du و Sie",`<p>Mit dem Imperativ gibst du Tipps und Anweisungen.</p><div class="gt-wrap"><table class="gt"><tr><th>Verb</th><th>du-Form</th><th>Sie-Form</th></tr><tr><td>trinken</td><td>Trink viel!</td><td>Trinken Sie viel!</td></tr><tr><td>bleiben</td><td>Bleib im Bett!</td><td>Bleiben Sie im Bett!</td></tr><tr><td>nehmen</td><td>Nimm die Tablette!</td><td>Nehmen Sie die Tablette!</td></tr></table></div><p>Bei <b>du</b> fällt das „” und das „” weg: du trinkst → Trink!</p>`),
 GR("Modalverben: sollen, müssen, dürfen","الأفعال الناقصة: sollen و müssen و dürfen",`<p><b>müssen</b> = لازم (ضروري) · <b>sollen</b> = المفروض (نصيحة) · <b>dürfen</b> = مسموح. Das zweite Verb steht am Ende (Satzklammer).</p><div class="exbox">Du <b>musst</b> viel trinken.<br>Du <b>sollst</b> zum Arzt gehen.<br>Du <b>darfst</b> nicht rauchen.</div><div class="gt-wrap"><table class="gt"><tr><th></th><th>müssen</th><th>sollen</th><th>dürfen</th></tr><tr><td>ich</td><td>muss</td><td>soll</td><td>darf</td></tr><tr><td>du</td><td>musst</td><td>sollst</td><td>darfst</td></tr><tr><td>er/sie</td><td>muss</td><td>soll</td><td>darf</td></tr></table></div>`),
 GR("Aussprache: p/b, t/d, k/g","النطق: p/b و t/d و k/g",`<p>Diese Paare sind ähnlich. <b>p, t, k</b> sind hart und ohne Stimme; <b>b, d, g</b> sind weich und mit Stimme.</p><div class="exbox"><b>p</b> wie in „” ↔ <b>b</b> wie in „”<br><b>t</b> wie in „” ↔ <b>d</b> wie in „”<br><b>k</b> wie in „” ↔ <b>g</b> wie in „”</div><p>Am Wortende klingt <b>b, d, g</b> oft hart: „” → „”.</p>`)
],
speaking:{questions:[S("Was tust du, wenn du krank bist?","بتعمل إيه لما تتعب؟"),S("Spiel ein Gespräch beim Arzt.","مثّل حوار عند الدكتور."),S("Gib einem Freund drei Gesundheitstipps.","أدِّي صاحبك 3 نصايح صحية.")],
model:"Wenn ich krank bin, bleibe ich im Bett und trinke viel Tee. Ich habe oft Kopfschmerzen und Halsschmerzen. Dann nehme ich eine Tablette aus der Apotheke. Mein Tipp: Trink viel Wasser, schlaf gut und iss gesund. Du sollst auch zum Arzt gehen, wenn du Fieber hast.",
modelAr:"لما أتعب بفضل في السرير وأشرب شاي كتير. غالبًا بيجيلي صداع ووجع في الحلق. ساعتها بآخد حبة من الصيدلية. نصيحتي: اشرب مية كتير، نام كويس، وكُل صحي. ولازم تروح للدكتور لو عندك سخونية."},
quiz:[Q("Mein Kopf ___ weh.",["tut","macht","ist"],0,"weh tun: tut weh.","نقول tut weh."),Q("Du ___ viel trinken. (ضروري)",["musst","darfst","kannst"],0,"Notwendigkeit: müssen.","الضرورة بـ müssen."),Q("Du ___ hier nicht rauchen. (ممنوع)",["darfst","musst","sollst"],0,"Verbot: nicht dürfen.","المنع بـ nicht dürfen."),Q("___ die Tablette! (du, nehmen)",["Nimm","Nehmst","Nehmen"],0,"Imperativ du: Nimm!","أمر du هو Nimm."),Q("Tabletten bekommt man in der ...",["Apotheke","Bäckerei","Bank"],0,"Apotheke.","صيدلية."),Q("Gegenteil von „” ist ...",["gesund","müde","kalt"],0,"gesund.","عكس مريض = صحي.")]}
,

{
num:9, route:"a1/k9", title:"Meine Wohnung", titleAr:"بيتي / شقتي",
subtitle:"Zimmer · Möbel · Farben · Wohnformen · Wechselpräpositionen",
intro:"Du verstehst Wohnungsanzeigen und beschreibst eine Wohnung. Du planst die Einrichtung, nennst Möbel und Farben, drückst Gefallen und Missfallen aus und machst Ortsangaben mit Wechselpräpositionen.",
introAr:"هتفهم إعلانات السكن وتوصف الشقة، تخطط للفرش، تسمي الأثاث والألوان، تقول إيه اللي عاجبك وإيه اللي مش عاجبك، وتحدد المكان بحروف الجر المتغيرة.",
badges:["Zimmer","Möbel","Farben","sein + Adjektiv","in + Akkusativ","Wechselpräpositionen"],
goals:[S("Zimmer und Möbel nennen","تسمي الغرف والأثاث"),S("eine Wohnung beschreiben","توصف شقة"),S("Farben nennen","تسمي الألوان"),S("Gefallen und Missfallen ausdrücken","تعبّر عن الإعجاب وعدمه"),S("Ortsangaben mit Wechselpräpositionen machen","تحدد المكان بحروف الجر المتغيرة")],
vocab:[
 V("die Wohnung, -en","Ein Zuhause mit Zimmern.","Meine Wohnung hat drei Zimmer.","شقة"),
 V("das Haus, -er","Ein Gebäude zum Wohnen.","Wir wohnen in einem Haus.","بيت"),
 V("das Zimmer, -","Ein Raum in der Wohnung.","Die Wohnung hat vier Zimmer.","أوضة / غرفة"),
 V("das Wohnzimmer, -","Zimmer zum Sitzen.","Im Wohnzimmer steht ein Sofa.","غرفة المعيشة"),
 V("das Schlafzimmer, -","Zimmer zum Schlafen.","Mein Schlafzimmer ist klein.","أوضة النوم"),
 V("die Küche, -n","Zimmer zum Kochen.","In der Küche koche ich.","المطبخ"),
 V("das Bad, -er","Zimmer mit Dusche und Toilette.","Das Bad ist neben dem Schlafzimmer.","الحمام"),
 V("der Balkon, -e","Kleiner Platz draußen an der Wohnung.","Auf dem Balkon sitze ich gern.","بلكونة"),
 V("der Flur, -e","Der Gang in der Wohnung.","Die Schuhe stehen im Flur.","الممر / الصالة"),
 V("der Garten, -","Grüner Platz am Haus.","Im Garten gibt es Blumen.","جنينة"),
 V("die Möbel","Tisch, Stuhl, Schrank usw.","Die Möbel sind neu.","أثاث / موبيليا"),
 V("das Bett, -en","Möbel zum Schlafen.","Das Bett ist bequem.","سرير"),
 V("der Tisch, -e","Möbel mit Beinen.","Der Tisch steht in der Mitte.","ترابيزة"),
 V("der Stuhl, -e","Möbel zum Sitzen.","Am Tisch stehen vier Stühle.","كرسي"),
 V("der Sessel, -","Ein bequemer, weicher Stuhl.","Ich lese im Sessel.","فوتيه"),
 V("das Sofa, -s","Langes Möbel zum Sitzen.","Das Sofa ist grau.","كنبة"),
 V("der Schrank, -e","Möbel für Kleidung.","Die Kleidung ist im Schrank.","دولاب"),
 V("das Regal, -e","Möbel für Bücher.","Die Bücher stehen im Regal.","رف"),
 V("der Schreibtisch, -e","Tisch zum Arbeiten.","Der Laptop steht auf dem Schreibtisch.","مكتب"),
 V("die Lampe, -n","Sie macht Licht.","Die Lampe ist schön.","لمبة / أباجورة"),
 V("der Teppich, -e","Stoff auf dem Boden.","Der Teppich ist weich.","سجادة"),
 V("das Bild, -er","Ein Foto oder Gemälde an der Wand.","Das Bild hängt über dem Sofa.","صورة / لوحة"),
 V("das Gerät, -e","Maschine wie Kühlschrank oder TV.","Das Gerät ist neu.","جهاز"),
 V("der Kühlschrank, -e","Gerät, das Essen kalt hält.","Die Milch ist im Kühlschrank.","تلاجة"),
 V("der Herd, -e","Gerät zum Kochen.","Der Herd ist heiß.","بوتاجاز"),
 V("die Waschmaschine, -n","Gerät, das Kleidung wäscht.","Die Waschmaschine ist kaputt.","غسالة"),
 V("der Fernseher, -","Gerät zum Filme sehen.","Der Fernseher ist groß.","تلفزيون"),
 V("die Wand, -e","Die Seite eines Zimmers.","An der Wand hängt ein Bild.","حيطة"),
 V("die Tür, -en","Damit geht man ins Zimmer.","Mach bitte die Tür zu.","باب"),
 V("das Fenster, -","Damit kommt Licht ins Zimmer.","Das Fenster ist offen.","شباك"),
 V("die Farbe, -n","Blau, rot, grün usw.","Welche Farbe magst du?","لون"),
 V("blau","Farbe wie der Himmel.","Das Sofa ist blau.","أزرق"),
 V("rot","Farbe wie Blut.","Die Lampe ist rot.","أحمر"),
 V("grün","Farbe wie Gras.","Die Pflanze ist grün.","أخضر"),
 V("gelb","Farbe wie die Sonne.","Die Wand ist gelb.","أصفر"),
 V("schwarz","Sehr dunkle Farbe.","Der Tisch ist schwarz.","أسود"),
 V("weiß","Sehr helle Farbe.","Die Tür ist weiß.","أبيض"),
 V("braun","Farbe wie Holz.","Der Schrank ist braun.","بني"),
 V("grau","Farbe zwischen schwarz und weiß.","Das Sofa ist grau.","رمادي"),
 V("die Miete, -n","Geld für die Wohnung pro Monat.","Die Miete ist nicht hoch.","الإيجار"),
 V("mieten","Eine Wohnung gegen Geld nehmen.","Wir mieten eine Wohnung.","يستأجر"),
 V("hell","Mit viel Licht.","Die Wohnung ist hell.","منوّر"),
 V("dunkel","Mit wenig Licht.","Das Zimmer ist dunkel.","ضلمة / معتم"),
 V("gemütlich","Warm und angenehm.","Das Wohnzimmer ist gemütlich.","مريح / دافي"),
 V("die Pflanze, -n","Eine grüne Zimmerpflanze.","Auf dem Balkon steht eine Pflanze.","نبتة")
],
redemittel:[
 RM("Wohnung beschreiben","وصف الشقة",[["Die Wohnung hat drei Zimmer.","الشقة فيها 3 أوض."],["Das Bad ist klein, aber hell.","الحمام صغير بس منوّر."],["Im Wohnzimmer steht ein Sofa.","في غرفة المعيشة فيه كنبة."],["Die Küche ist neu.","المطبخ جديد."]]),
 RM("Gefallen und Missfallen","الإعجاب وعدمه",[["Die Wohnung gefällt mir.","الشقة عجباني."],["Das Sofa finde ich schön.","الكنبة شكلها حلو."],["Die Farbe gefällt mir nicht.","اللون مش عاجبني."],["Das ist zu teuer.","ده غالي أوي."]]),
 RM("Möbel stellen","ترتيب الأثاث",[["Wir stellen das Sofa an die Wand.","نحط الكنبة على الحيطة."],["Die Lampe kommt über den Tisch.","اللمبة فوق الترابيزة."],["Der Schrank steht im Schlafzimmer.","الدولاب في غرفة النوم."]])
],
readings:[READ("Anzeige","Eine neue Wohnung",
 "Lena sucht eine Wohnung in Köln. Sie liest eine Anzeige: Schöne, helle Wohnung mit drei Zimmern, Küche und Balkon. Die Miete ist nicht zu teuer. Lena ruft an und besucht die Wohnung. Das Wohnzimmer ist groß und gemütlich. In der Küche gibt es einen neuen Kühlschrank. Das Schlafzimmer ist klein, aber hell. Die Wohnung gefällt Lena sehr und sie sagt: Ich nehme die Wohnung!",
 "لينا بتدوّر على شقة في كولونيا. بتقرأ إعلان: شقة حلوة منوّرة، 3 أوض ومطبخ وبلكونة، والإيجار مش غالي. بتتصل وبتزور الشقة. غرفة المعيشة كبيرة ومريحة، والمطبخ فيه تلاجة جديدة. غرفة النوم صغيرة بس منوّرة. الشقة عجباها أوي وقالت: هاخد الشقة!",
 [["suchen","يدوّر على"],["die Miete","الإيجار"],["der Kühlschrank","التلاجة"]],
 [["Wo sucht Lena eine Wohnung?","In Köln."],["Wie viele Zimmer hat die Wohnung?","Drei Zimmer."],["Wie ist das Schlafzimmer?","Klein, aber hell."]])],
grammar:[
 GR("Wechselpräpositionen: wo? und wohin?","حروف الجر المتغيرة: فين؟ وعلى فين؟",`<p>Diese Präpositionen (in, an, auf, über, unter, neben, vor, hinter, zwischen) haben zwei Fälle:</p><div class="gt-wrap"><table class="gt"><tr><th>Frage</th><th>Fall</th><th>Beispiel</th></tr><tr><td>Wo? (Ort, ثابت)</td><td>Dativ</td><td>Das Sofa steht <b>in dem (im)</b> Wohnzimmer.</td></tr><tr><td>Wohin? (حركة)</td><td>Akkusativ</td><td>Ich stelle das Sofa <b>in das (ins)</b> Wohnzimmer.</td></tr></table></div><p>Bewegung → Akkusativ, Position → Dativ.</p>`),
 GR("sein + Adjektiv","الفعل sein + صفة",`<p>Mit <b>sein</b> beschreibst du Dinge. Das Adjektiv bleibt gleich.</p><div class="exbox">Die Wohnung <b>ist</b> hell.<br>Das Zimmer <b>ist</b> klein, aber gemütlich.<br>Die Möbel <b>sind</b> neu.</div>`),
 GR("Aussprache: langes und kurzes e","النطق: e الطويلة والقصيرة",`<p>Das <b>e</b> kann lang oder kurz sein:</p><div class="gt-wrap"><table class="gt"><tr><th>langes e (إيه طويلة)</th><th>kurzes e (إيه قصيرة)</th></tr><tr><td>der See, gehen</td><td>das Bett, hell</td></tr><tr><td>der Tee, lesen</td><td>der Schrank? nein → das Fenster</td></tr></table></div><p>Vor zwei Konsonanten ist das e meist kurz: B<b>e</b>tt, h<b>e</b>ll.</p>`)
],
speaking:{questions:[S("Beschreibe deine Wohnung oder dein Zimmer.","اوصف شقتك أو أوضتك."),S("Welche Möbel hast du und welche Farben magst du?","عندك أنهي أثاث وبتحب أنهي ألوان؟"),S("Was gefällt dir an deiner Wohnung, was nicht?","إيه اللي عاجبك في بيتك وإيه اللي لأ؟")],
model:"Meine Wohnung hat zwei Zimmer, eine Küche und ein Bad. Das Wohnzimmer ist groß und hell. In der Mitte steht ein graues Sofa und über dem Tisch hängt eine Lampe. Mein Schlafzimmer ist klein, aber gemütlich. Die Wohnung gefällt mir sehr, nur die Küche ist ein bisschen alt.",
modelAr:"شقتي فيها أوضتين ومطبخ وحمام. غرفة المعيشة كبيرة ومنوّرة. في النص فيه كنبة رمادي وفوق الترابيزة لمبة. أوضة نومي صغيرة بس مريحة. الشقة عجباني أوي، بس المطبخ قديم شوية."},
quiz:[Q("Das Sofa steht ___ Wohnzimmer. (فين؟)",["im","ins","in"],0,"Wo? Dativ: im.","سؤال فين؟ يبقى Dativ = im."),Q("Ich stelle die Lampe ___ den Tisch. (على فين؟)",["über","auf dem","unter dem"],0,"Wohin? Akkusativ: über den Tisch.","حركة → Akkusativ."),Q("Die Wohnung ___ hell.",["ist","sind","bin"],0,"sein: ist.","مع المفرد نقول ist."),Q("Kleidung ist im ...",["Schrank","Balkon","Bad"],0,"Schrank.","الدولاب للهدوم."),Q("„” bedeutet ...",["عجباني","غالية","صغيرة"],0,"gefallen = أعجب.","gefällt mir يعني عجباني."),Q("Vor zwei Konsonanten ist das e meist ...",["kurz","lang","stumm"],0,"kurz: Bett, hell.","قصيرة قبل حرفين ساكنين.")]}
,

{
num:10, route:"a1/k10", title:"Studium und Beruf", titleAr:"الدراسة والمهنة",
subtitle:"Berufe · Jobsuche · Bewerbung · Perfekt",
intro:"Du beschreibst einen Tagesablauf, sprichst über die Jobsuche und über Bewerbungen, berichtest von einem Tag in der Vergangenheit, telefonierst und fragst nach. Du lernst das Perfekt mit haben und sein.",
introAr:"هتوصف يومك، تتكلم عن البحث عن شغل والتقديم للوظايف، تحكي عن يوم في الماضي، تتكلم في التليفون وتسأل. وهتتعلم زمن الماضي (Perfekt) بـ haben و sein.",
badges:["Berufe","Jobsuche","Bewerbung","Perfekt","Partizip II","haben/sein"],
goals:[S("über Berufe und Jobs sprechen","تتكلم عن المهن والوظايف"),S("über die Jobsuche und Bewerbung sprechen","تتكلم عن البحث والتقديم للشغل"),S("von einem Tag in der Vergangenheit berichten","تحكي عن يوم فات"),S("am Telefon nachfragen","تسأل في التليفون"),S("das Perfekt mit haben und sein bilden","تكوّن الماضي بـ haben و sein")],
vocab:[
 V("der Job, -s","Eine Arbeit, oft für Geld.","Ich habe einen Job im Café.","شغلانة"),
 V("die Stelle, -n","Ein freier Arbeitsplatz.","Die Firma hat eine freie Stelle.","وظيفة شاغرة"),
 V("die Firma, Firmen","Ein Betrieb, ein Unternehmen.","Ich arbeite in einer Firma.","شركة"),
 V("die Jobsuche","Das Suchen nach Arbeit.","Die Jobsuche ist nicht leicht.","البحث عن شغل"),
 V("suchen","Versuchen, etwas zu finden.","Ich suche eine Stelle.","يدوّر على"),
 V("finden","Etwas bekommen, das man gesucht hat.","Ich habe einen Job gefunden.","يلاقي"),
 V("die Bewerbung, -en","Brief und Lebenslauf für eine Stelle.","Ich schreibe eine Bewerbung.","طلب توظيف"),
 V("sich bewerben","Um eine Stelle bitten.","Ich bewerbe mich bei einer Bank.","يقدّم على وظيفة"),
 V("der Lebenslauf, -e","Papier mit deinen Daten.","Der Lebenslauf ist eine Seite.","السيرة الذاتية"),
 V("das Vorstellungsgespräch, -e","Das Gespräch vor dem Job.","Morgen habe ich ein Vorstellungsgespräch.","مقابلة عمل"),
 V("das Praktikum, Praktika","Kurze Zeit zum Lernen in einer Firma.","Ich mache ein Praktikum.","تدريب عملي"),
 V("anfangen","Mit etwas beginnen.","Ich fange am Montag an.","يبدأ (شغل)"),
 V("verdienen","Geld durch Arbeit bekommen.","Wie viel verdienst du?","يكسب"),
 V("das Gehalt, -er","Das Geld für die Arbeit pro Monat.","Das Gehalt ist gut.","المرتب"),
 V("studieren","An der Universität lernen.","Ich studiere Informatik.","يدرس في الجامعة"),
 V("das Studium","Das Lernen an der Uni.","Mein Studium dauert vier Jahre.","الدراسة الجامعية"),
 V("der Student, -en","Mann, der an der Uni lernt.","Der Student lernt viel.","طالب جامعي"),
 V("die Studentin, -nen","Frau, die an der Uni lernt.","Sie ist Studentin in Berlin.","طالبة جامعية"),
 V("die Universität, -en","Ort zum Studieren.","Ich studiere an der Universität Wien.","جامعة"),
 V("die Vorlesung, -en","Eine Stunde an der Uni.","Die Vorlesung beginnt um neun.","محاضرة"),
 V("die Prüfung, -en","Ein Test am Ende.","Die Prüfung war schwer.","امتحان"),
 V("das Semester, -","Ein halbes Jahr an der Uni.","Im ersten Semester lernt man viel.","ترم / فصل دراسي"),
 V("das Fach, -er","Mathematik, Deutsch, Biologie usw.","Mein Lieblingsfach ist Mathe.","مادة دراسية"),
 V("die Arbeitszeit, -en","Die Zeit, in der man arbeitet.","Meine Arbeitszeit ist flexibel.","مواعيد الشغل"),
 V("Vollzeit","Vierzig Stunden pro Woche.","Ich arbeite Vollzeit.","دوام كامل"),
 V("Teilzeit","Weniger Stunden.","Sie arbeitet Teilzeit.","دوام جزئي"),
 V("die Schicht, -en","Eine Arbeitsperiode, früh oder spät.","Ich habe heute Frühschicht.","وردية / شيفت"),
 V("der Feierabend","Das Ende des Arbeitstags.","Um fünf habe ich Feierabend.","نهاية الدوام"),
 V("die Erfahrung, -en","Was man schon gelernt und gemacht hat.","Ich habe Erfahrung im Büro.","خبرة"),
 V("erzählen","Über etwas berichten.","Erzähl mir von deinem Tag!","يحكي"),
 V("berichten","Sachlich über etwas erzählen.","Er berichtet von der Reise.","يقدّم تقرير"),
 V("nachfragen","Noch einmal fragen.","Ich frage im Büro nach.","يستفسر"),
 V("das Perfekt","Die Vergangenheitsform mit haben und sein.","Im Perfekt erzählt man von gestern.","زمن الماضي"),
 V("das Partizip, -ien","Die dritte Verbform (gemacht, gekommen).","gemacht ist ein Partizip.","التصريف الثالث"),
 V("gemacht","Partizip von machen.","Ich habe das gemacht.","عمل (تصريف ثالث)"),
 V("gelesen","Partizip von lesen.","Ich habe ein Buch gelesen.","قرأ (تصريف ثالث)"),
 V("gegangen","Partizip von gehen.","Ich bin nach Hause gegangen.","راح (تصريف ثالث)"),
 V("gefahren","Partizip von fahren.","Ich bin mit dem Bus gefahren.","ركب (تصريف ثالث)"),
 V("gekommen","Partizip von kommen.","Ich bin spät gekommen.","جه (تصريف ثالث)"),
 V("die Vergangenheit","Die Zeit, die vorbei ist.","Wir sprechen über die Vergangenheit.","الماضي"),
 V("fleißig","Arbeitet viel und gern.","Sie ist sehr fleißig.","مجتهد"),
 V("kündigen","Den Job beenden.","Er hat den Job gekündigt.","يسيب الشغل / يستقيل"),
 V("die Karriere, -n","Der berufliche Weg nach oben.","Sie macht Karriere.","مسار مهني"),
 V("selbstständig","Man hat eine eigene Firma.","Mein Onkel ist selbstständig.","يشتغل لحسابه")
],
redemittel:[
 RM("über den Job sprechen","عن الشغل",[["Was machst du beruflich?","بتشتغل إيه؟"],["Ich arbeite als Ingenieur.","أنا بشتغل مهندس."],["Ich suche eine neue Stelle.","بدوّر على وظيفة جديدة."],["Wie ist dein neuer Job?","عامل إيه شغلك الجديد؟"]]),
 RM("Bewerbung und Gespräch","التقديم والمقابلة",[["Ich möchte mich um die Stelle bewerben.","عايز أقدّم على الوظيفة."],["Ich schicke Ihnen meinen Lebenslauf.","هبعتلك السيرة الذاتية."],["Wann kann ich anfangen?","إمتى أقدر أبدأ؟"]]),
 RM("am Telefon nachfragen","الاستفسار في التليفون",[["Ich rufe wegen der Stelle an.","بكلمك بخصوص الوظيفة."],["Können Sie das bitte wiederholen?","ممكن تعيد من فضلك؟"],["Vielen Dank für die Information.","شكرًا على المعلومة."]])
],
readings:[READ("Bericht","Mein erster Arbeitstag",
 "Sami hat eine neue Stelle in einer Firma gefunden. Er erzählt: Gestern war mein erster Arbeitstag. Ich bin um sieben Uhr aufgestanden und habe schnell gefrühstückt. Dann bin ich mit dem Bus zur Arbeit gefahren. Im Büro habe ich meine Kollegen kennengelernt und viele E-Mails gelesen. Am Mittag haben wir zusammen gegessen. Der Tag hat mir gut gefallen und ich bin glücklich nach Hause gekommen.",
 "سامي لقى وظيفة جديدة في شركة. بيحكي: إمبارح كان أول يوم شغل. صحيت الساعة 7 وفطرت بسرعة. بعدها ركبت الأتوبيس للشغل. في المكتب اتعرّفت على زمايلي وقريت إيميلات كتير. الظهر أكلنا مع بعض. اليوم عجبني وروّحت البيت مبسوط.",
 [["finden / gefunden","يلاقي / لقى"],["aufstehen / aufgestanden","يصحى / صحى"],["kennenlernen","يتعرّف على"]],
 [["Was hat Sami gefunden?","Eine neue Stelle."],["Wie ist er zur Arbeit gefahren?","Mit dem Bus."],["Wie war der Tag?","Der Tag hat ihm gut gefallen."]])],
grammar:[
 GR("Perfekt: haben/sein + Partizip II","الماضي: haben/sein + التصريف الثالث",`<p>Das Perfekt benutzt man zum Erzählen von der Vergangenheit. Du brauchst <b>haben</b> oder <b>sein</b> + Partizip II. Das Partizip steht am <b>Ende</b> (Satzklammer).</p><div class="exbox">Ich <b>habe</b> E-Mails <b>gelesen</b>.<br>Ich <b>bin</b> nach Hause <b>gekommen</b>.</div><p>Verben der <b>Bewegung</b> (gehen, kommen, fahren) und der <b>Veränderung</b> nehmen <b>sein</b>. Die meisten anderen nehmen <b>haben</b>.</p>`),
 GR("Partizip II bilden","تكوين التصريف الثالث (Partizip II)",`<div class="gt-wrap"><table class="gt"><tr><th>Typ</th><th>Infinitiv</th><th>Partizip II</th></tr><tr><td>regelmäßig</td><td>machen</td><td>ge<b>macht</b></td></tr><tr><td>regelmäßig</td><td>arbeiten</td><td>ge<b>arbeitet</b></td></tr><tr><td>unregelmäßig</td><td>lesen</td><td>ge<b>lesen</b></td></tr><tr><td>unregelmäßig</td><td>kommen</td><td>ge<b>kommen</b></td></tr><tr><td>auf -ieren</td><td>studieren</td><td>studier<b>t</b> (ohne ge-)</td></tr></table></div>`),
 GR("Aussprache: das h","النطق: حرف h",`<p>Am Wortanfang spricht man <b>h</b> mit Luft (مهموس): <b>H</b>aus, <b>h</b>aben, <b>h</b>eute.</p><p>Nach einem Vokal ist das <b>h</b> oft stumm und macht den Vokal lang: ge<b>h</b>en, se<b>h</b>en, Ja<b>h</b>r → الـ h مبتتنطقش بس بتطوّل الحرف.</p>`)
],
speaking:{questions:[S("Was bist du von Beruf oder was studierst du?","بتشتغل إيه أو بتدرس إيه؟"),S("Erzähl von gestern im Perfekt.","احكي عن إمبارح بالـ Perfekt."),S("Wie suchst du einen Job?","بتدوّر على شغل إزاي؟")],
model:"Ich studiere Informatik und arbeite als Praktikant in einer Firma. Gestern bin ich um acht Uhr aufgestanden und habe an einem Projekt gearbeitet. Am Mittag habe ich mit Kollegen gegessen. Ich suche jetzt eine feste Stelle und habe schon zwei Bewerbungen geschrieben.",
modelAr:"أنا بدرس حاسبات وبشتغل متدرّب في شركة. إمبارح صحيت الساعة 8 واشتغلت على مشروع. الظهر أكلت مع الزمايل. دلوقتي بدوّر على وظيفة ثابتة وكتبت طلبين توظيف."},
quiz:[Q("Ich ___ einen Brief geschrieben.",["habe","bin","ist"],0,"schreiben → haben.","معظم الأفعال بـ haben."),Q("Ich ___ nach Hause gekommen.",["bin","habe","hat"],0,"kommen (حركة) → sein.","أفعال الحركة بـ sein."),Q("Partizip II von „” ist ...",["gemacht","gemachen","macht"],0,"gemacht.","ge + mach + t."),Q("Partizip II von „” ist ...",["studiert","gestudiert","studieren"],0,"-ieren: ohne ge-.","أفعال -ieren من غير ge."),Q("Brief + Lebenslauf für eine Stelle = die ...",["Bewerbung","Prüfung","Pause"],0,"Bewerbung.","طلب التوظيف."),Q("Das „” in „” ist ...",["stumm","laut","ش"],0,"stumm, macht den Vokal lang.","الـ h ساكتة وبتطوّل الحرف.")]}
,

{
num:11, route:"a1/k11", title:"Die Jacke gefällt mir!", titleAr:"الجاكيت عجبني! (الملابس والتسوق)",
subtitle:"Kleidung · Kaufhaus · Dativ-Pronomen · welcher/dieser",
intro:"Du sprichst über Kleidung, verstehst Komplimente und berichtest über Vergangenes. Du führst Gespräche beim Kleiderkauf, orientierst dich im Kaufhaus und fragst nach Auskunft. Du benutzt welcher/dieser und die Personalpronomen im Dativ.",
introAr:"هتتكلم عن الهدوم، تفهم المجاملات، تحكي عن حاجة فاتت، تعمل حوار وأنت بتشتري هدوم، تلاقي طريقك في المول، وتسأل عن معلومة. وهتستخدم welcher/dieser وضمائر الـ Dativ.",
badges:["Kleidung","Kaufhaus","mir/dir/ihm","welcher?","dieser","Komplimente"],
goals:[S("über Kleidung sprechen","تتكلم عن الملابس"),S("Komplimente verstehen und machen","تفهم وتعمل مجاملات"),S("ein Verkaufsgespräch führen","تعمل حوار شراء"),S("nach welcher/dieser fragen","تسأل بـ welcher وتجاوب بـ dieser"),S("Personalpronomen im Dativ benutzen (mir, dir, ihm)","تستخدم ضمائر الـ Dativ")],
vocab:[
 V("die Kleidung","Alles, was man anzieht.","Im Winter brauche ich warme Kleidung.","هدوم / ملابس"),
 V("anziehen","Kleidung an den Körper tun.","Zieh die Jacke an!","يلبس"),
 V("ausziehen","Kleidung vom Körper nehmen.","Zieh die nassen Schuhe aus!","يخلع"),
 V("tragen","Kleidung anhaben.","Er trägt ein weißes Hemd.","يلبس / يرتدي"),
 V("die Hose, -n","Kleidung für die Beine.","Die Hose ist zu lang.","بنطلون"),
 V("die Jeans","Eine Hose aus festem Stoff.","Ich trage am liebsten Jeans.","جينز"),
 V("das Hemd, -en","Oberteil, oft mit Knöpfen.","Er trägt ein blaues Hemd.","قميص"),
 V("das T-Shirt, -s","Leichtes Oberteil für den Sommer.","Ich kaufe ein T-Shirt.","تي شيرت"),
 V("die Bluse, -n","Leichtes Oberteil für Frauen.","Die Bluse ist schön.","بلوزة"),
 V("der Pullover, -","Warmes Oberteil für den Winter.","Der Pullover ist aus Wolle.","بلوفر"),
 V("die Jacke, -n","Kleidung für draußen.","Die Jacke gefällt mir!","جاكيت"),
 V("der Mantel, -","Lange, warme Jacke.","Im Winter trage ich einen Mantel.","بالطو"),
 V("das Kleid, -er","Ein Teil für Frauen.","Sie trägt ein schönes Kleid.","فستان"),
 V("der Rock, -e","Für Frauen, von der Taille abwärts.","Der Rock ist kurz.","جيبة"),
 V("der Anzug, -e","Formelle Kleidung für Männer.","Zur Arbeit trägt er einen Anzug.","بدلة"),
 V("der Schuh, -e","Für die Füße.","Die Schuhe sind bequem.","جزمة / حذاء"),
 V("der Stiefel, -","Hoher Schuh für den Winter.","Im Schnee trage ich Stiefel.","بوت"),
 V("die Mütze, -n","Etwas Warmes für den Kopf.","Im Winter trage ich eine Mütze.","طاقية"),
 V("der Schal, -s","Etwas Warmes für den Hals.","Der Schal ist aus Wolle.","كوفية / إيشارب"),
 V("die Socke, -n","Für den Fuß, unter dem Schuh.","Ich kaufe rote Socken.","شراب (جوارب)"),
 V("die Tasche, -n","Darin trägt man Sachen.","Die Tasche ist schwer.","شنطة"),
 V("die Brille, -n","Hilft beim Sehen.","Ich brauche eine neue Brille.","نضارة"),
 V("die Größe, -n","Wie groß die Kleidung ist (S, M, L).","Welche Größe haben Sie?","المقاس"),
 V("anprobieren","Kleidung zum Test anziehen.","Kann ich die Hose anprobieren?","يقيس"),
 V("passen","Die richtige Größe haben.","Die Jacke passt mir gut.","يبقى مظبوط"),
 V("stehen","Gut aussehen an einer Person.","Das Kleid steht dir gut.","يبقى حلو عليك"),
 V("gefallen","Schön finden.","Die Schuhe gefallen mir.","يعجب"),
 V("das Kaufhaus, -er","Großes Geschäft mit vielen Sachen.","Im Kaufhaus gibt es alles.","محل كبير"),
 V("der Laden, -","Ein kleines Geschäft.","Der Laden ist um die Ecke.","محل صغير"),
 V("die Kasse, -n","Wo man bezahlt.","Bitte zahlen Sie an der Kasse.","الكاشير"),
 V("die Umkleidekabine, -n","Kleiner Raum zum Anprobieren.","Die Umkleidekabine ist hinten.","غرفة القياس"),
 V("reduziert","Im Preis billiger als vorher.","Die Jacke ist reduziert.","مخفّض"),
 V("das Sonderangebot, -e","Etwas billiger für kurze Zeit.","Heute gibt es ein Sonderangebot.","عرض / أوكازيون"),
 V("umtauschen","Eine Ware zurückgeben und tauschen.","Ich möchte das Hemd umtauschen.","يستبدل"),
 V("bequem","Angenehm zu tragen.","Die Schuhe sind sehr bequem.","مريح"),
 V("modisch","Modern und schön.","Die Jacke ist sehr modisch.","موضة / شيك"),
 V("eng","Nicht weit; klein in der Größe.","Die Hose ist zu eng.","ضيّق"),
 V("kurz","Nicht lang.","Der Rock ist zu kurz.","قصير"),
 V("lang","Nicht kurz.","Die Hose ist zu lang.","طويل"),
 V("das Kompliment, -e","Etwas Nettes, das man sagt.","Danke für das Kompliment!","مجاملة"),
 V("der Knopf, -e","Damit schließt man ein Hemd.","Ein Knopf fehlt.","زرار"),
 V("die Wolle","Material für warme Kleidung.","Der Pullover ist aus Wolle.","صوف"),
 V("der Stoff, -e","Das Material der Kleidung.","Der Stoff ist weich.","قماش")
],
redemittel:[
 RM("beim Kleiderkauf","وأنت بتشتري هدوم",[["Kann ich Ihnen helfen?","أقدر أساعدك؟"],["Ich suche eine Jacke in Größe M.","بدوّر على جاكيت مقاس M."],["Kann ich das anprobieren?","ممكن أقيسها؟"],["Wo ist die Kasse?","فين الكاشير؟"]]),
 RM("Komplimente","المجاملات",[["Die Jacke steht dir gut!","الجاكيت بيجيلك حلو!"],["Das gefällt mir sehr.","ده عاجبني أوي."],["Schöne Farbe!","لون حلو!"]]),
 RM("Auswahl","الاختيار",[["Welche Hose möchten Sie?","عايز أنهي بنطلون؟"],["Diese hier in Blau, bitte.","ده اللي هنا الأزرق، لو سمحت."],["Haben Sie das auch eine Nummer größer?","عندك ده مقاس أكبر؟"]])
],
readings:[READ("Dialog","Im Kaufhaus",
 "Nadia ist im Kaufhaus. Eine Verkäuferin fragt: Kann ich Ihnen helfen? Nadia sagt: Ja, ich suche eine Jacke. Die Verkäuferin fragt: Welche Farbe gefällt Ihnen? Nadia antwortet: Diese blaue Jacke finde ich schön. Welche Größe haben Sie? Größe M, bitte. Nadia probiert die Jacke an. Sie passt gut und steht ihr sehr gut. Die Verkäuferin sagt: Die Jacke steht Ihnen wirklich gut! Nadia ist glücklich und bezahlt an der Kasse.",
 "نادية في المول. البائعة بتسأل: أقدر أساعدك؟ نادية: أيوه، بدوّر على جاكيت. البائعة: أنهي لون عاجبك؟ نادية: الجاكيت الأزرق ده شكله حلو. أنهي مقاس؟ M لو سمحتي. نادية بتقيس الجاكيت، بيجيلها مظبوط وحلو عليها. البائعة: الجاكيت بيجيلك حلو فعلًا! نادية مبسوطة وبتدفع عند الكاشير.",
 [["die Verkäuferin","البائعة"],["welche Farbe?","أنهي لون؟"],["es steht ihr gut","بيجيلها حلو"]],
 [["Was sucht Nadia?","Eine Jacke."],["Welche Farbe gefällt ihr?","Blau."],["Wo bezahlt sie?","An der Kasse."]])],
grammar:[
 GR("Personalpronomen im Dativ","ضمائر الـ Dativ",`<p>Verben wie <b>gefallen, passen, stehen, helfen</b> brauchen den Dativ.</p><div class="gt-wrap"><table class="gt"><tr><th>Nominativ</th><th>Dativ</th></tr><tr><td>ich</td><td>mir</td></tr><tr><td>du</td><td>dir</td></tr><tr><td>er</td><td>ihm</td></tr><tr><td>sie</td><td>ihr</td></tr><tr><td>wir</td><td>uns</td></tr></table></div><div class="exbox">Die Jacke gefällt <b>mir</b>. · Das steht <b>dir</b> gut. · Ich helfe <b>ihm</b>.</div>`),
 GR("welcher? – dieser","welcher؟ والإجابة بـ dieser",`<p>Mit <b>welch-</b> fragst du nach einer Auswahl, mit <b>dies-</b> zeigst du auf etwas.</p><div class="gt-wrap"><table class="gt"><tr><th>Genus</th><th>Frage</th><th>Antwort</th></tr><tr><td>der (Rock)</td><td>Welcher Rock?</td><td>Dieser Rock.</td></tr><tr><td>das (Hemd)</td><td>Welches Hemd?</td><td>Dieses Hemd.</td></tr><tr><td>die (Jacke)</td><td>Welche Jacke?</td><td>Diese Jacke.</td></tr></table></div>`),
 GR("Aussprache: Betonung bei Verben mit Präfix","النطق: نبر الأفعال اللي ليها بادئة",`<p>Bei <b>trennbaren</b> Verben liegt die Betonung auf dem Präfix: <b>án</b>probieren, <b>éin</b>kaufen, <b>án</b>ziehen.</p><p>Bei <b>untrennbaren</b> Verben liegt die Betonung auf dem Stamm: ver<b>káu</b>fen, be<b>záh</b>len, ge<b>fá</b>llen.</p>`)
],
speaking:{questions:[S("Was trägst du gern? Beschreibe deine Kleidung.","بتحب تلبس إيه؟ اوصف هدومك."),S("Spiel ein Verkaufsgespräch im Kaufhaus.","مثّل حوار شراء في المول."),S("Mach deinem Freund ein Kompliment.","اعمل مجاملة لصاحبك.")],
model:"Ich trage gern eine Jeans mit einem T-Shirt. Im Winter brauche ich eine warme Jacke und einen Pullover. Im Kaufhaus suche ich oft Schuhe. Letzte Woche habe ich eine blaue Jacke gekauft. Sie passt mir gut und gefällt mir sehr. Meine Freundin sagt: Die Jacke steht dir gut!",
modelAr:"بحب ألبس جينز مع تي شيرت. في الشتا بحتاج جاكيت دافي وبلوفر. في المول بدوّر كتير على جزم. الأسبوع اللي فات اشتريت جاكيت أزرق. بيجيلي مظبوط وعاجبني أوي. صاحبتي بتقول: الجاكيت بيجيلك حلو!"},
quiz:[Q("Die Jacke gefällt ___. (أنا)",["mir","mich","ich"],0,"gefallen + Dativ: mir.","gefallen بياخد Dativ = mir."),Q("Das Hemd steht ___ gut. (أنت)",["dir","dich","du"],0,"Dativ: dir.","Dativ لـ du هو dir."),Q("___ Jacke möchten Sie?",["Welche","Welcher","Welches"],0,"die Jacke → Welche.","الجاكيت مؤنث → Welche."),Q("Antwort: ___ Jacke hier.",["Diese","Dieser","Dieses"],0,"die → Diese.","المؤنث → Diese."),Q("Kleidung zum Test anziehen = ...",["anprobieren","bezahlen","kochen"],0,"anprobieren.","يقيس الهدوم."),Q("Betonung bei „” liegt auf ...",["an","pro","bieren"],0,"trennbar → Präfix „”.","الأفعال المنفصلة النبر على البادئة.")]}
,

{
num:12, route:"a1/k12", title:"Ab in den Urlaub!", titleAr:"يلا على الأجازة! (السفر والسياحة)",
subtitle:"Reise · Sehenswürdigkeiten · Wetter · Himmelsrichtungen",
intro:"Du machst Vorschläge für eine Stadttour, verstehst und gibst eine Wegbeschreibung, schreibst eine Postkarte und einen Reisebericht. Du sprichst über Reiseziele und Wetter und benutzt das Pronomen man und die Konjunktion denn.",
introAr:"هتقترح جولة في المدينة، تفهم وتدّي وصف للطريق، تكتب كارت بوستال وتقرير رحلة، تتكلم عن أماكن السفر والجو، وتستخدم الضمير man وأداة الربط denn.",
badges:["Reise","Wetter","Himmelsrichtungen","Pronomen man","denn","Sehenswürdigkeiten"],
goals:[S("über Reiseziele sprechen","تتكلم عن أماكن السفر"),S("eine Postkarte und einen Reisebericht schreiben","تكتب كارت بوستال وتقرير رحلة"),S("das Wetter beschreiben","توصف الجو"),S("Himmelsrichtungen nennen","تقول الاتجاهات الأصلية"),S("das Pronomen man und denn benutzen","تستخدم man و denn")],
vocab:[
 V("der Urlaub","Freie Zeit zum Reisen.","Im Sommer mache ich Urlaub.","أجازة"),
 V("die Reise, -n","Eine Fahrt an einen anderen Ort.","Die Reise nach Berlin war schön.","رحلة"),
 V("reisen","An einen anderen Ort fahren.","Wir reisen nach Italien.","يسافر"),
 V("das Reiseziel, -e","Der Ort, wohin man reist.","Mein Reiseziel ist das Meer.","وجهة السفر"),
 V("verreisen","In den Urlaub fahren.","Wir verreisen im August.","يسافر برّه"),
 V("der Tourist, -en","Eine Person im Urlaub.","Viele Touristen besuchen Berlin.","سائح"),
 V("das Hotel, -s","Haus mit Zimmern für Gäste.","Wir schlafen in einem Hotel.","فندق"),
 V("buchen","Vorher reservieren (Hotel, Flug).","Wir buchen ein Hotel.","يحجز رحلة"),
 V("der Koffer, -","Tasche für die Reise.","Mein Koffer ist schon fertig.","شنطة سفر"),
 V("packen","Sachen in den Koffer tun.","Ich packe den Koffer.","يحزم الشنطة"),
 V("das Flugzeug, -e","Es fliegt in der Luft.","Das Flugzeug startet um zehn.","طيارة"),
 V("fliegen","Mit dem Flugzeug reisen.","Wir fliegen nach Berlin.","يطير بالطيارة"),
 V("der Zug, -e","Fährt auf Schienen zwischen Städten.","Der Zug nach Köln ist pünktlich.","قطر"),
 V("das Schiff, -e","Fährt auf dem Wasser.","Wir fahren mit dem Schiff.","مركب / سفينة"),
 V("das Meer, -e","Sehr viel Wasser.","Am Meer schwimme ich gern.","البحر"),
 V("der Strand, -e","Sand am Meer.","Wir liegen am Strand.","الشاطئ"),
 V("der See, -n","Wasser im Land, kein Meer.","Wir baden im See.","بحيرة"),
 V("die Berge","Sehr hohe Orte aus Stein.","Im Winter fahren wir in die Berge.","الجبال"),
 V("die Insel, -n","Land mit Wasser ringsherum.","Wir machen Urlaub auf einer Insel.","جزيرة"),
 V("die Sehenswürdigkeit, -en","Ein wichtiger Ort für Touristen.","Berlin hat viele Sehenswürdigkeiten.","معلم سياحي"),
 V("besichtigen","Eine Sehenswürdigkeit ansehen.","Wir besichtigen das Schloss.","يزور معلم"),
 V("das Schloss, -er","Großes, altes, schönes Gebäude.","Wir besuchen das Schloss.","قصر"),
 V("der Dom, -e","Eine sehr große Kirche.","Der Kölner Dom ist berühmt.","كاتدرائية"),
 V("die Altstadt, -e","Der alte Teil der Stadt.","Die Altstadt ist schön.","البلد القديمة"),
 V("die Postkarte, -n","Karte mit Bild aus dem Urlaub.","Ich schreibe dir eine Postkarte.","كارت بوستال"),
 V("der Reisebericht, -e","Ein Text über eine Reise.","Ich schreibe einen Reisebericht.","تقرير رحلة"),
 V("besuchen","Zu jemandem oder an einen Ort gehen.","Wir besuchen meine Tante.","يزور"),
 V("das Wetter","Sonne, Regen, Wind usw.","Wie ist das Wetter?","الجو / الطقس"),
 V("die Sonne","Sie scheint am Himmel.","Die Sonne scheint.","الشمس"),
 V("scheinen","Licht geben (Sonne).","Die Sonne scheint heute.","تشرق / تنوّر"),
 V("der Regen","Wasser, das vom Himmel fällt.","Heute gibt es Regen.","مطر"),
 V("regnen","Wenn Regen fällt.","Es regnet seit heute Morgen.","تمطر"),
 V("der Schnee","Weißes, kaltes Wasser im Winter.","Im Winter gibt es viel Schnee.","تلج"),
 V("schneien","Wenn Schnee fällt.","In den Bergen schneit es.","تتلج"),
 V("der Wind","Bewegte Luft.","Am Meer gibt es viel Wind.","هوا / رياح"),
 V("die Wolke, -n","Weiß oder grau am Himmel.","Am Himmel sind viele Wolken.","سحابة"),
 V("der Himmel","Oben über uns.","Der Himmel ist blau.","السما"),
 V("warm","Nicht kalt und nicht heiß.","Im Süden ist es warm.","دافي"),
 V("heiß","Sehr warm.","Im Sommer ist es heiß.","حر / سخن"),
 V("kalt","Niedrige Temperatur.","Im Norden ist es kalt.","بارد"),
 V("sonnig","Mit viel Sonne.","Heute ist es sonnig.","مشمس"),
 V("bewölkt","Mit vielen Wolken.","Der Himmel ist bewölkt.","غايم"),
 V("der Grad, -e","Einheit für die Temperatur.","Es sind zwanzig Grad.","درجة حرارة"),
 V("der Norden","Die Richtung oben auf der Karte.","Hamburg liegt im Norden.","الشمال"),
 V("der Süden","Die Richtung unten auf der Karte.","Im Süden ist es warm.","الجنوب"),
 V("der Osten","Wo die Sonne aufgeht.","Im Osten liegt Dresden.","الشرق"),
 V("der Westen","Wo die Sonne untergeht.","Köln liegt im Westen.","الغرب")
],
redemittel:[
 RM("Reise planen","تخطيط الرحلة",[["Wohin fährst du in den Urlaub?","رايح فين في الأجازة؟"],["Ich fahre ans Meer.","أنا رايح على البحر."],["Wollen wir eine Stadttour machen?","نعمل جولة في المدينة؟"],["Man kann das Schloss besichtigen.","ممكن نزور القصر."]]),
 RM("über das Wetter","عن الجو",[["Wie ist das Wetter?","الجو عامل إيه؟"],["Die Sonne scheint und es ist warm.","الشمس طالعة والجو دافي."],["Es regnet und es ist kalt.","بتمطر والجو بارد."],["Im Norden ist es windig.","في الشمال فيه هوا."]]),
 RM("Postkarte schreiben","كتابة كارت بوستال",[["Liebe Grüße aus Hamburg!","تحياتي من هامبورغ!"],["Hier ist es sehr schön.","هنا حلو أوي."],["Bis bald!","أشوفك قريب!"]])
],
readings:[READ("Postkarte","Grüße aus München",
 "Hallo Yara, viele Grüße aus München! Wir sind seit drei Tagen hier und es gefällt uns sehr. Das Wetter ist schön: Die Sonne scheint und es ist warm. Gestern haben wir die Altstadt besichtigt und sind durch viele Straßen gelaufen. Man kann hier sehr gut essen, denn die Restaurants sind toll. Morgen fahren wir in den Süden zu den Bergen. Liebe Grüße, Lara und Tom.",
 "أهلًا يارا، تحياتي من ميونخ! بقالنا 3 أيام هنا والمكان عاجبنا أوي. الجو حلو: الشمس طالعة والجو دافي. إمبارح زرنا البلد القديمة ومشينا في شوارع كتير. ممكن تاكل كويس جدًا هنا، لأن المطاعم رائعة. بكرة هنروح للجنوب عند الجبال. تحياتي، لارا وتوم.",
 [["seit drei Tagen","من 3 أيام"],["die Altstadt","البلد القديمة"],["denn","لأن"]],
 [["Woher kommt die Postkarte?","Aus München."],["Wie ist das Wetter?","Die Sonne scheint, es ist warm."],["Wohin fahren sie morgen?","In den Süden zu den Bergen."]])],
grammar:[
 GR("Das Pronomen man","الضمير man",`<p><b>man</b> bedeutet „” (الناس بشكل عام) und steht mit der er/sie-Form des Verbs.</p><div class="exbox">In München <b>kann man</b> gut essen.<br>Hier <b>spricht man</b> Deutsch.<br>So <b>schreibt man</b> das Wort.</div>`),
 GR("Sätze verbinden: denn","ربط الجمل: denn (لأن)",`<p><b>denn</b> = „” (لأن). Nach <b>denn</b> bleibt die normale Wortstellung: Subjekt + Verb.</p><div class="exbox">Ich fahre ans Meer, <b>denn</b> <u>ich</u> <u>schwimme</u> gern.<br>Wir essen hier, <b>denn</b> die Restaurants sind toll.</div>`),
 GR("Aussprache: f, v, w","النطق: f و v و w",`<p><b>f</b> und <b>v</b> klingen meist gleich wie „”: <b>F</b>erien, <b>v</b>ier, <b>V</b>ater.</p><p><b>w</b> klingt wie das englische v (ڤ، الشفايف على بعض مع اهتزاز): <b>W</b>etter, <b>w</b>arm, <b>W</b>ind.</p>`)
],
speaking:{questions:[S("Wohin reist du gern? Beschreibe ein Reiseziel.","بتحب تسافر فين؟ اوصف وجهة سفر."),S("Wie ist das Wetter in deiner Stadt?","الجو عامل إيه في مدينتك؟"),S("Erzähl von einer Reise im Perfekt.","احكي عن رحلة بالـ Perfekt.")],
model:"Ich reise gern ans Meer, denn ich schwimme sehr gern. Letzten Sommer war ich in Alexandria. Das Wetter war warm und die Sonne hat geschienen. Wir haben die Altstadt besichtigt und sind am Strand spazieren gegangen. Man kann dort sehr gut essen. Ich habe meiner Familie eine Postkarte geschrieben.",
modelAr:"بحب أسافر على البحر، لأني بحب السباحة جدًا. الصيف اللي فات كنت في إسكندرية. الجو كان دافي والشمس كانت طالعة. زرنا البلد القديمة ومشينا على الشاطئ. ممكن تاكل كويس جدًا هناك. وبعتت لعيلتي كارت بوستال."},
quiz:[Q("In Ägypten ___ man Arabisch.",["spricht","sprechen","sprichst"],0,"man + er-Form: spricht.","man بياخد صيغة er."),Q("Ich fahre ans Meer, ___ ich schwimme gern.",["denn","aber","oder"],0,"Grund: denn.","السبب بـ denn."),Q("Wasser vom Himmel ist der ...",["Regen","Strand","Urlaub"],0,"Regen.","المطر."),Q("Norden, Süden, Osten und ...",["Westen","Sommer","Wetter"],0,"Westen.","الغرب."),Q("Ein wichtiger Ort für Touristen ist eine ...",["Sehenswürdigkeit","Postkarte","Größe"],0,"Sehenswürdigkeit.","معلم سياحي."),Q("„” spricht man wie ...",["englisches v","ف","ب"],0,"wie englisches v (ڤ).","w زي v الإنجليزية.")]}
];


const A1_2_AI_IMAGE_CHAPTERS = new Set([7, 8, 9, 10, 11, 12]);
const A1_2_TOPIC_TITLES = {
  7:["Arbeitsplatz","Ortsangaben","Bank und Geld","Medien und Small Talk"],
  8:["Körperteile","Krankheiten","Apotheke und Medikamente","Beim Arzt"],
  9:["Zimmer und Wohnung","Möbel und Geräte","Farben und Beschreiben","Miete und Präpositionen"],
  10:["Berufe und Jobs","Bewerbung","Studium","Perfekt und Vergangenheit"],
  11:["Kleidung","Kaufhaus und Anprobieren","Komplimente","Material und Passform"],
  12:["Reise und Hotel","Sehenswürdigkeiten","Wetter","Himmelsrichtungen"]
};
A1_2_CHAPTERS.forEach(chapter => {
  chapter.visual = {
    src:`assets/a1/chapters_ai/chapter-${chapter.num}.webp`,
    alt:`A1 Kapitel ${chapter.num}: ${chapter.title}`,
    caption:`A1 Kapitel ${chapter.num}: ${chapter.title}`,
    captionAr:chapter.titleAr
  };
  chapter.vocab.forEach((card, index) => {
    card.img = A1_2_AI_IMAGE_CHAPTERS.has(chapter.num)
      ? `assets/a1/vocab_ai/k${chapter.num}/${String(index + 1).padStart(2, "0")}.webp`
      : "";
  });
  chapter.topicVisuals = (A1_2_TOPIC_TITLES[chapter.num] || []).map((title, index) => ({
    title,
    src:`assets/a1/topics/k${chapter.num}/${String(index + 1).padStart(2, "0")}.webp`,
    alt:`A1 Kapitel ${chapter.num}: ${title}`
  }));
});

(window.A1_BOOK = window.A1_BOOK || []).push(...A1_2_CHAPTERS);
})();
