/* Generated by scripts/a1_images/slice_sheets.py - do not edit by hand.
   Pictures for A1.1 words that had none, keyed by "chapter|headword".
   Loaded after data_a11_vocab.js; it only fills cards that still have no picture. */
window.A1_VOCAB_11_IMAGES = {
 "1|grüßen": "assets/a1/vocab_ai/new/k1-gruessen.webp",
 "1|sich verabschieden": "assets/a1/vocab_ai/new/k1-sich-verabschieden.webp",
 "1|der Herr, -en": "assets/a1/vocab_ai/new/k1-der-herr-en.webp",
 "1|der Reiseführer, -": "assets/a1/vocab_ai/new/k1-der-reisefuehrer.webp",
 "1|die Reiseführerin, -nen": "assets/a1/vocab_ai/new/k1-die-reisefuehrerin-nen.webp",
 "1|der Kranke, -n": "assets/a1/vocab_ai/new/k1-der-kranke-n.webp",
 "1|das Telefon, -e": "assets/a1/vocab_ai/new/k1-das-telefon-e.webp",
 "1|die Handynummer, -n": "assets/a1/vocab_ai/new/k1-die-handynummer-n.webp",
 "1|Algerien": "assets/a1/vocab_ai/new/k1-algerien.webp",
 "1|Brasilien": "assets/a1/vocab_ai/new/k1-brasilien.webp",
 "1|Frankreich": "assets/a1/vocab_ai/new/k1-frankreich.webp",
 "1|Griechenland": "assets/a1/vocab_ai/new/k1-griechenland.webp",
 "1|Italien": "assets/a1/vocab_ai/new/k1-italien.webp",
 "1|Japan": "assets/a1/vocab_ai/new/k1-japan.webp",
 "1|Mexiko": "assets/a1/vocab_ai/new/k1-mexiko.webp",
 "1|Polen": "assets/a1/vocab_ai/new/k1-polen.webp",
 "1|Portugal": "assets/a1/vocab_ai/new/k1-portugal.webp",
 "1|Russland": "assets/a1/vocab_ai/new/k1-russland.webp",
 "1|Spanien": "assets/a1/vocab_ai/new/k1-spanien.webp",
 "1|Thailand": "assets/a1/vocab_ai/new/k1-thailand.webp",
 "1|die Türkei": "assets/a1/vocab_ai/new/k1-die-tuerkei.webp",
 "1|die USA (Pl.)": "assets/a1/vocab_ai/new/k1-die-usa-pl.webp",
 "1|die Ukraine": "assets/a1/vocab_ai/new/k1-die-ukraine.webp",
 "1|China": "assets/a1/vocab_ai/new/k1-china.webp",
 "1|Dänemark": "assets/a1/vocab_ai/new/k1-daenemark.webp",
 "1|der Irak": "assets/a1/vocab_ai/new/k1-der-irak.webp",
 "1|der Iran": "assets/a1/vocab_ai/new/k1-der-iran.webp",
 "1|der Jemen": "assets/a1/vocab_ai/new/k1-der-jemen.webp",
 "1|Kanada": "assets/a1/vocab_ai/new/k1-kanada.webp",
 "1|der Libanon": "assets/a1/vocab_ai/new/k1-der-libanon.webp",
 "1|Neuseeland": "assets/a1/vocab_ai/new/k1-neuseeland.webp",
 "1|die Niederlande (Pl.)": "assets/a1/vocab_ai/new/k1-die-niederlande-pl.webp",
 "1|die Slowakei": "assets/a1/vocab_ai/new/k1-die-slowakei.webp",
 "1|Syrien": "assets/a1/vocab_ai/new/k1-syrien.webp",
 "1|Tunesien": "assets/a1/vocab_ai/new/k1-tunesien.webp",
 "1|Ungarn": "assets/a1/vocab_ai/new/k1-ungarn.webp",
 "1|der Kindergarten, ¨-": "assets/a1/vocab_ai/new/k1-der-kindergarten.webp",
 "1|der Koffer, -": "assets/a1/vocab_ai/new/k1-der-koffer.webp",
 "1|das Handtuch, ¨-er": "assets/a1/vocab_ai/new/k1-das-handtuch-er.webp",
 "1|das Butterbrot, -e": "assets/a1/vocab_ai/new/k1-das-butterbrot-e.webp",
 "1|das Würstchen, -": "assets/a1/vocab_ai/new/k1-das-wuerstchen.webp",
 "1|die Nudel, -n": "assets/a1/vocab_ai/new/k1-die-nudel-n.webp",
 "1|die Autobahn, -en": "assets/a1/vocab_ai/new/k1-die-autobahn-en.webp",
 "1|das Gespräch, -e": "assets/a1/vocab_ai/new/k1-das-gespraech-e.webp",
 "1|das Interview, -s": "assets/a1/vocab_ai/new/k1-das-interview-s.webp",
 "1|hören": "assets/a1/vocab_ai/new/k1-hoeren.webp",
 "1|schreiben": "assets/a1/vocab_ai/new/k1-schreiben.webp",
 "1|fragen": "assets/a1/vocab_ai/new/k1-fragen.webp",
 "1|unterstreichen": "assets/a1/vocab_ai/new/k1-unterstreichen.webp",
 "1|sammeln": "assets/a1/vocab_ai/new/k1-sammeln.webp",
 "2|der Fußball": "assets/a1/vocab_ai/new/k2-der-fussball.webp",
 "2|der Basketball": "assets/a1/vocab_ai/new/k2-der-basketball.webp",
 "2|das Tennis": "assets/a1/vocab_ai/new/k2-das-tennis.webp",
 "2|Karate": "assets/a1/vocab_ai/new/k2-karate.webp",
 "2|Yoga": "assets/a1/vocab_ai/new/k2-yoga.webp",
 "2|Zumba": "assets/a1/vocab_ai/new/k2-zumba.webp",
 "2|reisen": "assets/a1/vocab_ai/new/k2-reisen.webp",
 "2|die Musik": "assets/a1/vocab_ai/new/k2-die-musik.webp",
 "2|das Theater, -": "assets/a1/vocab_ai/new/k2-das-theater.webp",
 "2|der Club, -s": "assets/a1/vocab_ai/new/k2-der-club-s.webp",
 "2|der Sportclub, -s": "assets/a1/vocab_ai/new/k2-der-sportclub-s.webp",
 "2|das Stadion, Stadien": "assets/a1/vocab_ai/new/k2-das-stadion-stadien.webp",
 "2|das Schwimmbad, ¨-er": "assets/a1/vocab_ai/new/k2-das-schwimmbad-er.webp",
 "2|die Spaghetti (Pl.)": "assets/a1/vocab_ai/new/k2-die-spaghetti-pl.webp"
};

(function applyA11Images(){
  if(!Array.isArray(window.A1_BOOK)) return;
  window.A1_BOOK.forEach(chapter=>{
    (chapter.vocab||[]).forEach(card=>{
      const src=window.A1_VOCAB_11_IMAGES[chapter.num+'|'+card.w];
      if(src&&!card.img) card.img=src;
    });
  });
})();
