#!/usr/bin/env python3
"""Cut the AI-generated 4x4 sheets into single A1.1 flashcard pictures.

Input : scripts/a1_images/incoming/sheet-NN.(png|jpg|jpeg|webp), NN = sheet number from PROMPTS.md
Output: app/assets/a1/vocab_ai/new/<id>.webp  (420x420, same size as the existing pictures)
        app/data_a11_images.js                (word -> picture map, applied on top of data_a11_vocab.js)

Run from the repo root:  python3 scripts/a1_images/slice_sheets.py [--sheet 3] [--debug]
Needs: pip install pillow numpy
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
DIR = Path(__file__).resolve().parent
INCOMING = DIR / "incoming"
OUT_DIR = ROOT / "app" / "assets" / "a1" / "vocab_ai" / "new"
DATA_JS = ROOT / "app" / "data_a11_images.js"
SIZE = 420
WHITE = 232        # a gutter pixel is at least this bright in grey scale
INSET = 0.012      # trim this share of every cell so no gutter bleeds into the picture


def runs(mask):
    """(start, end) of every run of True in a 1-D boolean array, end exclusive."""
    found, start = [], None
    for i, flag in enumerate(mask):
        if flag and start is None:
            start = i
        elif not flag and start is not None:
            found.append((start, i))
            start = None
    if start is not None:
        found.append((start, len(mask)))
    return found


def cell_edges(gray, axis, count):
    """Edges [(lo, hi), ...] of `count` cells along an axis, found from the white gutters.

    axis 0 -> columns (x), axis 1 -> rows (y). Falls back to equal parts when a gutter is not found."""
    size = gray.shape[1] if axis == 0 else gray.shape[0]
    # a gutter line is white over (nearly) the whole length of the sheet
    line = np.percentile(gray, 8, axis=axis)
    white = runs(line >= WHITE)
    notes = []

    def nearest(expected):
        near = [r for r in white if r[0] > 0 and r[1] < size and abs((r[0] + r[1]) / 2 - expected) < size * 0.07]
        return min(near, key=lambda r: abs((r[0] + r[1]) / 2 - expected)) if near else None

    outer_lo = white[0][1] if white and white[0][0] == 0 else 0
    outer_hi = white[-1][0] if white and white[-1][1] == size else size
    span = outer_hi - outer_lo
    gutters = []
    for i in range(1, count):
        gutter = nearest(outer_lo + span * i / count)
        if gutter is None:
            notes.append(f"gutter {i} not found, equal split used")
            mid = outer_lo + span * i / count
            gutter = (int(mid), int(mid))
        gutters.append(gutter)
    bounds = [outer_lo] + [x for g in gutters for x in g] + [outer_hi]
    return [(bounds[2 * i], bounds[2 * i + 1]) for i in range(count)], notes


def find_sheet(number):
    for ext in ("png", "jpg", "jpeg", "webp"):
        path = INCOMING / f"sheet-{number:02d}.{ext}"
        if path.exists():
            return path
    return None


def slice_sheet(sheet, grid, debug):
    path = find_sheet(sheet["sheet"])
    if path is None:
        return None
    image = Image.open(path).convert("RGB")
    gray = np.asarray(image.convert("L"), dtype=np.uint8)
    cols, col_notes = cell_edges(gray, 0, grid)
    rows, row_notes = cell_edges(gray, 1, grid)
    notes = [f"x: {n}" for n in col_notes] + [f"y: {n}" for n in row_notes]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for index, cell in enumerate(sheet["cells"]):
        row, col = divmod(index, grid)
        x0, x1 = cols[col]
        y0, y1 = rows[row]
        w, h = x1 - x0, y1 - y0
        if min(w, h) < 40:
            notes.append(f"cell {index + 1} too small ({w}x{h}), skipped")
            continue
        if abs(w - h) > 0.18 * max(w, h) and not any("centre-cropped" in n for n in notes):
            notes.append(f"cells are {w}x{h} (sheet is not square), centre-cropped to squares")
        inset = int(min(w, h) * INSET)
        x0, y0, x1, y1 = x0 + inset, y0 + inset, x1 - inset, y1 - inset
        side = min(x1 - x0, y1 - y0)
        left = x0 + (x1 - x0 - side) // 2
        top = y0 + (y1 - y0 - side) // 2
        picture = image.crop((left, top, left + side, top + side)).resize((SIZE, SIZE), Image.LANCZOS)
        picture.save(OUT_DIR / f"{cell['id']}.webp", "WEBP", quality=82, method=6)
        written += 1
    if debug:
        print(f"  cols {cols}\n  rows {rows}")
    return written, notes, image.size


def write_data_js(manifest):
    mapping = {}
    for sheet in manifest["sheets"]:
        for cell in sheet["cells"]:
            if (OUT_DIR / f"{cell['id']}.webp").exists():
                mapping[f"{cell['chapter']}|{cell['word']}"] = f"assets/a1/vocab_ai/new/{cell['id']}.webp"
    body = json.dumps(mapping, ensure_ascii=False, indent=1)
    DATA_JS.write_text(
        "/* Generated by scripts/a1_images/slice_sheets.py - do not edit by hand.\n"
        "   Pictures for A1.1 words that had none, keyed by \"chapter|headword\".\n"
        "   Loaded after data_a11_vocab.js; it only fills cards that still have no picture. */\n"
        f"window.A1_VOCAB_11_IMAGES = {body};\n\n"
        "(function applyA11Images(){\n"
        "  if(!Array.isArray(window.A1_BOOK)) return;\n"
        "  window.A1_BOOK.forEach(chapter=>{\n"
        "    (chapter.vocab||[]).forEach(card=>{\n"
        "      const src=window.A1_VOCAB_11_IMAGES[chapter.num+'|'+card.w];\n"
        "      if(src&&!card.img) card.img=src;\n"
        "    });\n"
        "  });\n"
        "})();\n",
        encoding="utf-8",
    )
    return len(mapping)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sheet", type=int, help="only this sheet number")
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()
    manifest = json.loads((DIR / "manifest.json").read_text(encoding="utf-8"))
    grid = manifest["grid"]
    total, missing = 0, []
    for sheet in manifest["sheets"]:
        if args.sheet and sheet["sheet"] != args.sheet:
            continue
        result = slice_sheet(sheet, sheet.get("grid", grid), args.debug)
        if result is None:
            missing.append(sheet["sheet"])
            continue
        written, notes, size = result
        total += written
        print(f"sheet {sheet['sheet']:02d}: {written}/{len(sheet['cells'])} pictures from {size[0]}x{size[1]}")
        for note in notes:
            print(f"   ! {note}")
    mapped = write_data_js(manifest)
    print(f"\n{total} pictures written, {mapped} words mapped in app/data_a11_images.js")
    if missing:
        print("sheets not delivered yet: " + ", ".join(f"{n:02d}" for n in missing))


if __name__ == "__main__":
    sys.exit(main())
