module.exports = {
  1: [
    [0,"Am Samstag ruft Mia noch einmal an, denn der Plan hat sich geändert.","يوم السبت تتصل ميا مرة أخرى لأن الخطة تغيرت."],
    [1,"Hallo Mia, bleibt es bei vier Uhr oder müssen wir das Treffen verschieben?","مرحبًا ميا، هل ما زال الموعد الساعة الرابعة أم سنؤجله؟"],
    [0,"Vier Uhr passt. Aber Karim hat abgesagt, weil sein Sohn krank geworden ist.","الساعة الرابعة مناسبة، لكن كريم اعتذر لأن ابنه مرض."],
    [1,"Schade. Soll ich trotzdem den Salat und etwas zu trinken mitbringen?","مؤسف. هل أحضر السلطة وشيئًا للشرب رغم ذلك؟"],
    [0,"Ja, bitte. Ich habe schon Brot gekauft und bereite eine Suppe vor.","نعم من فضلك. اشتريت الخبز وسأجهز الحساء."],
    [1,"Dann kochen wir also doch zu Hause und gehen nicht ins Restaurant?","إذن سنطبخ في المنزل ولن نذهب إلى المطعم؟"],
    [0,"Genau. Zu Hause können wir länger sitzen und uns in Ruhe unterhalten.","بالضبط. في المنزل يمكننا الجلوس مدة أطول والتحدث بهدوء."],
    [1,"Gute Idee. Soll ich auch meine neue Kollegin Jana fragen?","فكرة جيدة. هل أدعو زميلتي الجديدة يانا أيضًا؟"],
    [0,"Gern. Was macht sie beruflich und woher kommt sie?","بكل سرور. ما مهنتها ومن أين تأتي؟"],
    [1,"Sie arbeitet als Fotografin und kommt ursprünglich aus Leipzig.","تعمل مصورة وهي في الأصل من لايبزيغ."],
    [0,"Das ist interessant. In meiner Freizeit fotografiere ich nämlich auch gern.","هذا ممتع، فأنا أيضًا أحب التصوير في وقت فراغي."],
    [1,"Perfekt, dann habt ihr sofort ein gemeinsames Thema.","ممتاز، إذن لديكما موضوع مشترك فورًا."],
    [0,"Später können wir noch das neue Café an der Ecke ausprobieren.","بعد ذلك يمكننا تجربة المقهى الجديد عند الزاوية."],
    [1,"Ich habe gehört, dass es dort sehr gemütlich sein soll.","سمعت أن المكان هناك مريح جدًا."],
    [0,"Dann machen wir es so: erst gemeinsam essen und danach ins Café.","إذن نفعل ذلك: نأكل معًا أولًا ثم نذهب إلى المقهى."],
    [1,"Abgemacht. Ich bin um vier da und melde mich, falls ich mich verspäte.","اتفقنا. سأكون هناك الساعة الرابعة وسأتصل إذا تأخرت."]
  ],
  2: [
    [0,"Am nächsten Tag üben Nora und Jonas gemeinsam für Noras Präsentation.","في اليوم التالي تتدرب نورا ويوناس معًا على العرض."],
    [1,"Wie möchtest du anfangen? Der erste Satz ist besonders wichtig.","كيف تريدين البدء؟ الجملة الأولى مهمة جدًا."],
    [0,"Ich erzähle zuerst von meiner Schulzeit und meinem Lieblingsfach Biologie.","سأتحدث أولًا عن فترة المدرسة ومادتي المفضلة الأحياء."],
    [1,"Und danach kannst du erklären, warum du eine Ausbildung machen möchtest.","وبعد ذلك يمكنك شرح سبب رغبتك في التدريب المهني."],
    [0,"Bei meinem Praktikum im Labor habe ich gute Erfahrungen gemacht.","اكتسبت خبرات جيدة خلال تدريبي في المختبر."],
    [1,"Gab es dort auch eine Aufgabe, die dir schwergefallen ist?","هل كانت هناك مهمة صعبة عليك؟"],
    [0,"Ja, am Anfang musste ich viele Geräte kennenlernen und genau dokumentieren.","نعم، في البداية كان عليّ تعلم أجهزة كثيرة وتوثيق كل شيء بدقة."],
    [1,"Das zeigt, dass du sorgfältig arbeitest und schnell lernen kannst.","هذا يوضح أنك تعملين بعناية وتتعلمين بسرعة."],
    [0,"Meinst du, ich soll auch mein Zeugnis und meine Noten erwähnen?","هل أذكر شهادتي ودرجاتي أيضًا؟"],
    [1,"Nur kurz. Deine praktische Erfahrung ist für die Zuhörer interessanter.","باختصار فقط. خبرتك العملية أكثر إثارة للمستمعين."],
    [0,"Ich bin trotzdem nervös, wenn ich vor der ganzen Klasse stehe.","أنا متوترة رغم ذلك عندما أقف أمام الفصل كله."],
    [1,"Schau nicht ständig auf deine Karten und mach nach jedem Abschnitt eine Pause.","لا تنظري باستمرار إلى البطاقات وخذي وقفة بعد كل جزء."],
    [0,"Kannst du am Ende eine Frage stellen, als wärst du im Publikum?","هل يمكنك طرح سؤال في النهاية كأنك من الجمهور؟"],
    [1,"Natürlich: Welche Voraussetzung braucht man für diese Ausbildung?","بالطبع: ما الشرط المطلوب لهذا التدريب المهني؟"],
    [0,"Man braucht einen guten Schulabschluss und Interesse an Naturwissenschaften.","يحتاج المرء إلى شهادة مدرسية جيدة واهتمام بالعلوم الطبيعية."],
    [1,"Sehr gut. Jetzt klingt deine Antwort klar, ruhig und überzeugend.","جيد جدًا. إجابتك الآن واضحة وهادئة ومقنعة."]
  ],
  3: [
    [0,"Am Freitag treffen sich Lea und Samir tatsächlich zu einem Abend ohne Handy.","يوم الجمعة يلتقي ليا وسمير فعلًا لقضاء أمسية بلا هاتف."],
    [1,"Ich lege mein Handy in die Schublade. Machst du wirklich mit?","سأضع هاتفي في الدرج. هل ستشارك حقًا؟"],
    [0,"Ja, aber vorher muss ich meiner Familie noch eine Nachricht schicken.","نعم، لكن يجب أن أرسل رسالة لعائلتي أولًا."],
    [1,"In Ordnung. Danach vergleichen wir zwei Filme und wählen gemeinsam einen aus.","حسنًا. بعدها نقارن فيلمين ونختار واحدًا معًا."],
    [0,"Diese Komödie hat eine bessere Bewertung als der andere Film.","هذا الفيلم الكوميدي تقييمه أفضل من الفيلم الآخر."],
    [1,"Die Quelle ist aber nicht sehr zuverlässig. Es gibt nur fünf Bewertungen.","لكن المصدر غير موثوق جدًا، فهناك خمسة تقييمات فقط."],
    [0,"Dann sehen wir uns lieber den Trailer an. Die Handlung wirkt spannend.","إذن من الأفضل أن نشاهد الإعلان. تبدو القصة مثيرة."],
    [1,"Die Hauptfigur gefällt mir. Sie spielt eine Journalistin in Berlin.","تعجبني الشخصية الرئيسية. إنها تؤدي دور صحفية في برلين."],
    [0,"Während des Films teilen wir keine Fotos und beantworten keine Nachrichten.","أثناء الفيلم لن نشارك صورًا ولن نجيب عن رسائل."],
    [1,"Das wird schwer. Meine Bildschirmzeit war heute schon vier Stunden.","سيكون ذلك صعبًا. وقت الشاشة عندي بلغ أربع ساعات اليوم."],
    [0,"Ein Vorteil ist, dass wir uns besser auf den Film konzentrieren können.","من المميزات أننا نستطيع التركيز على الفيلم بصورة أفضل."],
    [1,"Und ein Nachteil ist, dass niemand unsere wichtigen Nachrichten liest.","ومن العيوب أن أحدًا لن يقرأ رسائلنا المهمة."],
    [0,"Nach dem Film schauen wir zehn Minuten aufs Handy. Das ist ein guter Kompromiss.","بعد الفيلم ننظر إلى الهاتف عشر دقائق. هذا حل وسط جيد."],
    [1,"Einverstanden. Einerseits bleiben wir erreichbar, andererseits haben wir einen ruhigen Abend.","موافق. نبقى متاحين من ناحية ونقضي أمسية هادئة من ناحية أخرى."],
    [0,"Jetzt drück auf Start. Mein Handy bleibt wirklich in der Schublade.","الآن شغّل الفيلم. سيبقى هاتفي فعلًا في الدرج."],
    [1,"Meins auch. Heute gewinnt der Film gegen den kleinen Bildschirm.","وهاتفي أيضًا. اليوم سيفوز الفيلم على الشاشة الصغيرة."]
  ],
  4: [
    [0,"Nach der Party sitzen Emma und Omar noch in der Küche und sprechen über den Abend.","بعد الحفلة يجلس إيما وعمر في المطبخ ويتحدثان عن الأمسية."],
    [1,"Ich war zuerst aufgeregt, weil plötzlich so viele Menschen im Zimmer standen.","كنت متوترًا أولًا لأن عددًا كبيرًا من الناس كان في الغرفة فجأة."],
    [0,"Aber nach ein paar Minuten hast du sehr glücklich ausgesehen.","لكنك بدوت سعيدًا جدًا بعد دقائق قليلة."],
    [1,"Ja, besonders als meine Schwester die alten Fotos gezeigt hat.","نعم، خصوصًا عندما عرضت أختي الصور القديمة."],
    [0,"Auf einem Foto warst du vielleicht sechs Jahre alt und sehr stolz.","في إحدى الصور كان عمرك نحو ست سنوات وكنت فخورًا جدًا."],
    [1,"Damals hatte ich gerade schwimmen gelernt. Daran erinnere ich mich noch gut.","كنت قد تعلمت السباحة وقتها وما زلت أتذكر ذلك جيدًا."],
    [0,"Deine Freunde haben sich wirklich viel Mühe mit der Feier gegeben.","بذل أصدقاؤك جهدًا كبيرًا فعلًا في الحفلة."],
    [1,"Ich möchte mich bei jedem persönlich bedanken und nicht nur eine Nachricht schicken.","أريد شكر كل شخص بصورة شخصية وليس برسالة فقط."],
    [0,"Du könntest morgen anrufen und sagen, worüber du dich besonders gefreut hast.","يمكنك الاتصال غدًا وذكر أكثر شيء أسعدك."],
    [1,"Gute Idee. Nur schade, dass mein Cousin nicht kommen konnte.","فكرة جيدة. من المؤسف فقط أن ابن عمي لم يستطع الحضور."],
    [0,"Er war bestimmt enttäuscht. Seine Zugverbindung ist ausgefallen.","كان محبطًا بالتأكيد. لقد أُلغيت رحلة قطاره."],
    [1,"Ich rufe ihn später an. Vielleicht feiern wir nächste Woche noch einmal klein.","سأتصل به لاحقًا. ربما نحتفل بشكل صغير الأسبوع القادم."],
    [0,"Dann kann er dir persönlich gratulieren und sein Geschenk mitbringen.","عندها يمكنه تهنئتك شخصيًا وإحضار هديته."],
    [1,"Eigentlich brauche ich kein weiteres Geschenk. Gemeinsame Zeit reicht mir.","في الحقيقة لا أحتاج هدية أخرى. يكفيني الوقت المشترك."],
    [0,"Das ist eine schöne Einstellung. Du klingst wirklich dankbar.","هذه طريقة تفكير جميلة. تبدو ممتنًا فعلًا."],
    [1,"Das bin ich auch. Dieser Abend bleibt eine besondere Erinnerung.","أنا كذلك فعلًا. ستبقى هذه الأمسية ذكرى مميزة."]
  ],
  5: [
    [0,"Nach dem Termin im Bürgeramt geht Lina zur Bank am Marktplatz.","بعد موعد مكتب المواطنين تذهب لينا إلى البنك في ساحة السوق."],
    [1,"Guten Tag. Was kann ich für Sie tun?","مرحبًا. كيف يمكنني مساعدتك؟"],
    [0,"Ich möchte gern ein Konto eröffnen. Welche Unterlagen brauche ich dafür?","أريد فتح حساب. ما المستندات المطلوبة؟"],
    [1,"Wir brauchen Ihren Ausweis, Ihre Adresse und dieses ausgefüllte Formular.","نحتاج بطاقة هويتك وعنوانك وهذه الاستمارة بعد ملئها."],
    [0,"Könnten Sie mir bitte erklären, wo ich unterschreiben muss?","هل يمكنك توضيح مكان التوقيع من فضلك؟"],
    [1,"Natürlich. Unterschreiben Sie unten rechts und tragen Sie hier Ihre Telefonnummer ein.","بالطبع. وقّعي أسفل اليمين واكتبي رقم هاتفك هنا."],
    [0,"Kann ich mit dem Konto später auch online Geld überweisen?","هل يمكنني تحويل المال عبر الإنترنت بهذا الحساب لاحقًا؟"],
    [1,"Ja. Die Zugangsdaten bekommen Sie in den nächsten Tagen per Post.","نعم. ستصلك بيانات الدخول بالبريد خلال الأيام القادمة."],
    [0,"Ich bin erst vor einer Woche in dieses Viertel gezogen.","انتقلت إلى هذا الحي منذ أسبوع واحد فقط."],
    [1,"Dann kennen Sie die Innenstadt wahrscheinlich noch nicht so gut.","إذن غالبًا لا تعرفين وسط المدينة جيدًا بعد."],
    [0,"Stimmt. Ich muss heute außerdem noch eine Bewerbung abschicken.","صحيح. ويجب عليّ أيضًا إرسال طلب وظيفة اليوم."],
    [1,"In der Bibliothek gegenüber können Sie kostenlos einen Computer benutzen.","يمكنك استخدام كمبيوتر مجانًا في المكتبة المقابلة."],
    [0,"Das ist praktisch. Morgen habe ich sogar schon ein Vorstellungsgespräch.","هذا عملي. لدي غدًا بالفعل مقابلة عمل."],
    [1,"Dann wünsche ich Ihnen viel Erfolg. Zu welcher Stelle haben Sie sich beworben?","أتمنى لك النجاح. لأي وظيفة قدمتِ؟"],
    [0,"Für eine Stelle im Kundenservice. Dafür habe ich bereits Erfahrung.","لوظيفة في خدمة العملاء، ولدي خبرة بالفعل في هذا المجال."],
    [1,"Sehr gut. Das Konto ist gleich eröffnet, dann können Sie alles Weitere erledigen.","جيد جدًا. سيفتح الحساب حالًا ثم يمكنك إنجاز بقية الأمور."]
  ],
  6: [
    [0,"Am Nachmittag hilft Aya bei der Vorbereitung einer Veranstaltung in der Firma.","بعد الظهر تساعد آية في التحضير لفعالية في الشركة."],
    [1,"Aya, bist du für die Gästeliste oder für den Raum zuständig?","آية، هل أنت مسؤولة عن قائمة الضيوف أم القاعة؟"],
    [0,"Für beides ein bisschen. Zuerst kontrolliere ich die Anmeldungen.","عن الاثنين قليلًا. سأراجع التسجيلات أولًا."],
    [1,"Der Vortrag beginnt um sechs. Die Technik muss vorher funktionieren.","تبدأ المحاضرة الساعة السادسة ويجب أن تعمل التقنية قبل ذلك."],
    [0,"Ich verbinde gleich den Laptop mit dem großen Bildschirm.","سأوصل الكمبيوتر بالشاشة الكبيرة حالًا."],
    [1,"Gut. Danach ruf bitte den Referenten zurück. Er hat eine Nachricht hinterlassen.","جيد. بعدها اتصلي بالمحاضر، فقد ترك رسالة."],
    [0,"Er kommt mit dem Zug. Hoffentlich erreicht er seinen Anschluss.","سيأتي بالقطار. آمل أن يلحق بقطاره التالي."],
    [1,"Wenn er ihn verpasst, beginnt die Veranstaltung später.","إذا فاته القطار فستبدأ الفعالية متأخرة."],
    [0,"Soll ich am Bahnhof nach einer anderen Verbindung suchen?","هل أبحث عن رحلة أخرى من المحطة؟"],
    [1,"Ja, und frag ihn, auf welchem Gleis sein Zug ankommt.","نعم، واسأليه على أي رصيف سيصل قطاره."],
    [0,"Zu meinen Aufgaben gehört heute wirklich alles: Telefon, Technik und Gäste.","مهامي اليوم تشمل كل شيء فعلًا: الهاتف والتقنية والضيوف."],
    [1,"Das ist am ersten Arbeitstag viel, aber du machst das sehr ruhig.","هذا كثير في أول يوم عمل لكنك تتصرفين بهدوء."],
    [0,"Später möchte ich gern selbst Veranstaltungen organisieren.","أريد لاحقًا أن أنظم فعاليات بنفسي."],
    [1,"Dann ist heute eine gute Übung für deinen Traumberuf.","إذن اليوم تدريب جيد لمهنة أحلامك."],
    [0,"Der Referent ruft gerade an. Ich nehme das Gespräch im Büro an.","المحاضر يتصل الآن. سأجيب في المكتب."],
    [1,"Perfekt. Ich kümmere mich inzwischen um die Stühle und Getränke.","ممتاز. سأهتم في الوقت نفسه بالكراسي والمشروبات."]
  ],
  7: [
    [0,"Am nächsten Morgen probiert Malik tatsächlich den Weg mit dem Fahrrad aus.","في صباح اليوم التالي يجرب مالك فعلًا الطريق بالدراجة."],
    [1,"Sofia, ich stehe an einer großen Kreuzung. Wo muss ich jetzt abbiegen?","صوفيا، أنا عند تقاطع كبير. أين أنعطف الآن؟"],
    [0,"Siehst du die Baustelle neben der Straßenbahnhaltestelle?","هل ترى موقع البناء بجانب محطة الترام؟"],
    [1,"Ja, aber der normale Fahrradweg ist dort gesperrt.","نعم، لكن مسار الدراجات المعتاد مغلق هناك."],
    [0,"Dann fahr rechts an der Baustelle vorbei und danach immer geradeaus.","إذن مر من يمين موقع البناء ثم تابع مستقيمًا."],
    [1,"Hier ist viel Verkehr. Mit der U-Bahn wäre ich wahrscheinlich schneller.","حركة المرور كثيفة هنا. ربما كنت سأكون أسرع بالمترو."],
    [0,"Heute gibt es dort auch eine Verspätung. Das Fahrrad ist trotzdem eine gute Wahl.","هناك تأخير في المترو اليوم أيضًا. الدراجة ما زالت اختيارًا جيدًا."],
    [1,"Ich sehe jetzt ein blaues Schild und eine Ampel.","أرى الآن لافتة زرقاء وإشارة مرور."],
    [0,"An der Ampel links, dann erreichst du in fünf Minuten dein Ziel.","انعطف يسارًا عند الإشارة وستصل إلى هدفك خلال خمس دقائق."],
    [1,"Muss ich das Fahrrad an einer bestimmten Station zurückgeben?","هل يجب أن أعيد الدراجة في محطة محددة؟"],
    [0,"Ja, direkt vor deiner Firma gibt es eine Station für Leihräder.","نعم، توجد محطة للدراجات المستأجرة أمام شركتك مباشرة."],
    [1,"Das ist praktisch. Ein Nachteil ist nur der starke Wind heute.","هذا عملي. العيب الوحيد هو الرياح القوية اليوم."],
    [0,"Dafür stehst du nicht im Stau und musst nicht umsteigen.","لكن في المقابل لن تقف في الزحام ولن تبدل وسيلة المواصلات."],
    [1,"Stimmt. Und ich bin trotz der kleinen Umleitung fast pünktlich.","صحيح. وأنا تقريبًا في الموعد رغم التحويلة الصغيرة."],
    [0,"Fahr vorsichtig und achte an der Kreuzung auf die Fußgänger.","قد بحذر وانتبه للمشاة عند التقاطع."],
    [1,"Danke für die Wegbeschreibung. Morgen kenne ich den Weg schon allein.","شكرًا على وصف الطريق. غدًا سأعرفه وحدي."]
  ],
  8: [
    [0,"Zwei Tage vor der Prüfung treffen sich Klara und Yusuf in der Bibliothek.","قبل الامتحان بيومين تلتقي كلارا ويوسف في المكتبة."],
    [1,"Ich habe meinen Zeitplan eingehalten, aber der Wortschatz ist noch schwierig.","التزمت بخطة الوقت لكن المفردات ما زالت صعبة."],
    [0,"Lern nicht alles auswendig. Ordne die Wörter nach Themen.","لا تحفظ كل شيء فقط. رتب الكلمات حسب الموضوعات."],
    [1,"Ich habe Karteikarten gemacht, aber manchmal verwechsle ich die Artikel.","صنعت بطاقات لكنني أخلط أحيانًا بين أدوات التعريف."],
    [0,"Dann schreib der, die und das in verschiedenen Farben.","إذن اكتب der وdie وdas بألوان مختلفة."],
    [1,"Gute Idee. Im Wörterbuch schlage ich auch immer einen Beispielsatz nach.","فكرة جيدة. أبحث أيضًا عن جملة مثال في القاموس."],
    [0,"Nach vierzig Minuten solltest du eine kurze Pause machen.","بعد أربعين دقيقة ينبغي أن تأخذ استراحة قصيرة."],
    [1,"Ich habe Angst, dass ich in der Pause zu lange aufs Handy schaue.","أخشى أن أنظر إلى الهاتف طويلًا أثناء الاستراحة."],
    [0,"Stell einen Wecker auf zehn Minuten und leg das Handy danach weg.","اضبط منبهًا لعشر دقائق ثم ضع الهاتف بعيدًا."],
    [1,"Morgen muss ich außerdem meine Präsentation üben.","يجب عليّ أيضًا التدرب على العرض غدًا."],
    [0,"Sprich frei und benutze nur wenige Stichpunkte.","تحدث بحرية واستخدم نقاطًا مختصرة قليلة فقط."],
    [1,"Kannst du zuhören und mir danach eine ehrliche Rückmeldung geben?","هل يمكنك الاستماع وإعطائي رأيًا صريحًا بعدها؟"],
    [0,"Natürlich. Achte besonders auf eine deutliche Aussprache und Blickkontakt.","بالطبع. انتبه خصوصًا إلى النطق الواضح والتواصل البصري."],
    [1,"Wenn ich einen Fehler mache, werde ich schnell nervös.","عندما أخطئ أتوتر بسرعة."],
    [0,"Fehler sind normal. Verbessere dich kurz und sprich einfach weiter.","الأخطاء طبيعية. صحح نفسك باختصار وواصل الكلام."],
    [1,"Danke. Mit diesem Plan fühle ich mich schon besser vorbereitet.","شكرًا. بهذه الخطة أشعر أنني مستعد بصورة أفضل."]
  ],
  9: [
    [0,"Am Samstag beginnt das Finale, und David sitzt mit anderen Fans im Stadion.","يوم السبت تبدأ المباراة النهائية ويجلس ديفيد مع مشجعين آخرين في الملعب."],
    [1,"Salma, wir sind da! Eure Mannschaft läuft gerade auf den Platz.","سلمى، نحن هنا! فريقكم يدخل الملعب الآن."],
    [0,"Ich bin so aufgeregt. Wir haben uns lange auf diesen Wettkampf vorbereitet.","أنا متحمسة جدًا. استعددنا طويلًا لهذه المنافسة."],
    [1,"Die Fans feuern euch laut an. Das gibt bestimmt zusätzliche Energie.","المشجعون يشجعونكم بصوت عالٍ. هذا يمنحكم طاقة إضافية بالتأكيد."],
    [0,"In der ersten Hälfte müssen wir ruhig spielen und gut zusammenarbeiten.","في الشوط الأول يجب أن نلعب بهدوء ونتعاون جيدًا."],
    [1,"Eure Gegnerinnen sind schnell, aber eure Mannschaft hat mehr Ausdauer.","منافساتكم سريعات لكن فريقكم يملك قدرة تحمل أكبر."],
    [0,"Da kommt der erste Pass. Jetzt haben wir eine gute Chance!","ها هي التمريرة الأولى. لدينا فرصة جيدة الآن!"],
    [1,"Tor! Unglaublich, das war großartig!","هدف! لا يصدق، كان رائعًا!"],
    [0,"Wir dürfen uns nicht zu früh freuen. Das Spiel dauert noch lange.","يجب ألا نفرح مبكرًا. المباراة ما زالت طويلة."],
    [1,"Nach der Pause steht es eins zu eins. Wie fühlst du dich?","بعد الاستراحة النتيجة واحد لواحد. كيف تشعرين؟"],
    [0,"Müde, aber ich will bis zum Ende durchhalten.","متعبة، لكنني أريد الصمود حتى النهاية."],
    [1,"Wir glauben an euch. Das nächste Tor klappt bestimmt.","نحن نؤمن بكم. الهدف التالي سينجح بالتأكيد."],
    [0,"Noch eine Minute. Unsere Stürmerin schießt und trifft!","بقيت دقيقة واحدة. مهاجمتنا تسدد وتصيب الهدف!"],
    [1,"Ihr habt gewonnen! Die ganze Tribüne jubelt.","لقد فزتم! المدرج كله يهتف."],
    [0,"Was für ein Sieg. Jetzt bin ich einfach nur stolz auf die Mannschaft.","يا له من فوز. أنا الآن فخورة فقط بالفريق."],
    [1,"Kommt nachher zu uns. Wir möchten gemeinsam mit euch feiern.","تعالوا إلينا بعد المباراة. نريد الاحتفال معكم."]
  ],
  10: [
    [0,"Am Freitag kommt Rami zum ersten Treffen der Nachbarn in den Hof.","يوم الجمعة يأتي رامي إلى أول لقاء للجيران في الفناء."],
    [1,"Schön, dass du da bist. Hast du dich in der neuen Wohnung schon eingerichtet?","جميل أنك هنا. هل رتبت الشقة الجديدة بالفعل؟"],
    [0,"Fast. Einige Kartons stehen noch im Keller, und ein Regal fehlt.","تقريبًا. ما زالت بعض الصناديق في القبو وينقصنا رف."],
    [1,"Mein Mann hat Werkzeug. Er kann dir morgen beim Aufbau helfen.","زوجي لديه أدوات ويمكنه مساعدتك غدًا في التركيب."],
    [0,"Das wäre ein großer Gefallen. Dafür gieße ich gern eure Blumen im Urlaub.","ستكون هذه خدمة كبيرة. وفي المقابل يسعدني سقي زهوركم في الإجازة."],
    [1,"Danke. Wir suchen sowieso jemanden, der auch den Briefkasten leert.","شكرًا. نحن نبحث أصلًا عمن يفرغ صندوق البريد أيضًا."],
    [0,"Kein Problem. Sag mir einfach, wann ihr wegfahrt.","لا مشكلة. أخبريني فقط متى ستسافرون."],
    [1,"Übrigens hat sich gestern jemand über Lärm im Treppenhaus beschwert.","بالمناسبة اشتكى شخص أمس من الضوضاء في بيت الدرج."],
    [0,"Das waren wahrscheinlich wir beim Auspacken. Das tut mir leid.","غالبًا كنا نحن أثناء تفريغ الصناديق. أنا آسف."],
    [1,"Es war noch vor der Ruhezeit. Aber abends sollte es leiser sein.","كان ذلك قبل وقت الهدوء، لكن يجب أن يكون الصوت أخفض مساءً."],
    [0,"Natürlich. Wir nehmen Rücksicht und tragen die restlichen Möbel am Vormittag.","بالطبع. سنراعي الآخرين وننقل بقية الأثاث صباحًا."],
    [1,"Dann gibt es sicher kein Problem mit der Hausordnung.","إذن لن تكون هناك مشكلة مع قواعد المبنى."],
    [0,"Ich finde es gut, dass man hier offen miteinander sprechen kann.","يعجبني أن الناس هنا يستطيعون التحدث بصراحة."],
    [1,"Eine gute Nachbarschaft beginnt mit freundlichen Gesprächen.","الجيرة الجيدة تبدأ بمحادثات ودية."],
    [0,"Da stimme ich zu. Ich bringe beim nächsten Treffen etwas zu essen mit.","أوافق. سأحضر طعامًا في اللقاء القادم."],
    [1,"Sehr gern. Dann lernst du auch die Nachbarn aus dem dritten Stock kennen.","بكل سرور. وستتعرف أيضًا على جيران الطابق الثالث."]
  ],
  11: [
    [0,"Eine Woche später sprechen Julia und Karim darüber, ob ihr neuer Plan funktioniert.","بعد أسبوع تتحدث يوليا وكريم عما إذا كانت خطتهما الجديدة نجحت."],
    [1,"Ich habe zwei Spaziergänge geschafft und drei Abende das Handy ausgeschaltet.","نجحت في المشي مرتين وأغلقت الهاتف ثلاث أمسيات."],
    [0,"Das klingt gut. Hattest du dadurch wirklich weniger Stress?","هذا جيد. هل أصبح لديك ضغط أقل فعلًا؟"],
    [1,"Ja. Die Zeit ist langsamer vergangen, weil ich nicht ständig Nachrichten gelesen habe.","نعم. مر الوقت ببطء أكثر لأنني لم أقرأ الرسائل باستمرار."],
    [0,"Ich verbringe meinen Feierabend jetzt öfter mit einem Buch.","أقضي وقتي بعد العمل الآن غالبًا مع كتاب."],
    [1,"Früher wollte ich auch mehr lesen, aber ich habe es immer verschoben.","كنت أريد أيضًا القراءة أكثر لكنني كنت أؤجل ذلك دائمًا."],
    [0,"Man braucht ein konkretes Ziel. Wie viele Seiten möchtest du täglich lesen?","يحتاج المرء إلى هدف محدد. كم صفحة تريد قراءتها يوميًا؟"],
    [1,"Zehn Seiten sind realistisch. Eine Stunde wäre wahrscheinlich zu viel.","عشر صفحات واقعية. ساعة كاملة ستكون كثيرة غالبًا."],
    [0,"Und was machst du mit Terminen, die nicht wirklich wichtig sind?","وماذا تفعل بالمواعيد غير المهمة فعلًا؟"],
    [1,"Ich sage öfter ab oder schlage einen anderen Tag vor.","أعتذر عنها أكثر أو أقترح يومًا آخر."],
    [0,"Das ist nicht unhöflich. Du musst deine eigene Zeit auch schützen.","هذا ليس غير مهذب. يجب أن تحمي وقتك أيضًا."],
    [1,"Mein großer Wunsch ist eine Reise, für die ich bisher nie Zeit hatte.","رغبتي الكبيرة رحلة لم أجد لها وقتًا من قبل."],
    [0,"Trag sie jetzt in den Kalender ein, sonst bleibt sie nur ein Traum.","سجلها الآن في التقويم وإلا ستبقى مجرد حلم."],
    [1,"Du hast recht. Im September würde ich gern eine Woche ans Meer fahren.","معك حق. أود السفر أسبوعًا إلى البحر في سبتمبر."],
    [0,"Dann kannst du jeden Monat etwas Geld und freie Zeit dafür planen.","يمكنك إذن التخطيط كل شهر لبعض المال والوقت الحر."],
    [1,"So wird aus einem Wunsch langsam ein erreichbares Ziel.","وهكذا تتحول الرغبة تدريجيًا إلى هدف يمكن تحقيقه."]
  ],
  12: [
    [0,"Nach dem Konzert hören Nina und Adel im Zug noch einmal einige Lieder der Band.","بعد الحفل تستمع نينا وعادل في القطار إلى بعض أغاني الفرقة مجددًا."],
    [1,"Dieses Lied klingt live ganz anders als auf der Aufnahme.","تبدو هذه الأغنية في الحفل مختلفة تمامًا عن التسجيل."],
    [0,"Der Rhythmus war auf der Bühne viel stärker, und das Publikum hat mitgesungen.","كان الإيقاع على المسرح أقوى كثيرًا وغنى الجمهور معه."],
    [1,"Mir gefällt besonders die Melodie am Anfang. Sie ist ruhig und klar.","تعجبني خصوصًا النغمة في البداية، فهي هادئة وواضحة."],
    [0,"Hast du den Text verstanden? In dem Lied geht es um eine lange Reise.","هل فهمت الكلمات؟ تتحدث الأغنية عن رحلة طويلة."],
    [1,"Nicht jedes Wort. Aber der Sänger hat sehr deutlich gesprochen.","ليس كل كلمة، لكن المغني نطق بوضوح شديد."],
    [0,"Auf meinem Foto sieht man die ganze Band auf der Bühne.","في صورتي تظهر الفرقة كلها على المسرح."],
    [1,"Im Vordergrund steht die Gitarristin, und im Hintergrund sieht man das Schlagzeug.","في المقدمة تقف عازفة الجيتار وفي الخلف تظهر الطبول."],
    [0,"Das Licht war blau und violett. Dadurch wirkt das Bild fast wie ein Gemälde.","كانت الإضاءة زرقاء وبنفسجية، لذلك تبدو الصورة كلوحة تقريبًا."],
    [1,"Schick mir das Foto bitte. Ich möchte es meiner Schwester zeigen.","أرسل لي الصورة من فضلك. أريد عرضها على أختي."],
    [0,"Sie spielt selbst ein Instrument, oder?","هي تعزف آلة موسيقية أيضًا، أليس كذلك؟"],
    [1,"Ja, sie spielt Klavier und tritt manchmal mit einer kleinen Gruppe auf.","نعم، تعزف البيانو وتقدم عروضًا أحيانًا مع مجموعة صغيرة."],
    [0,"Vielleicht kann ihre Gruppe beim nächsten Stadtfest spielen.","ربما يمكن لمجموعتها العزف في مهرجان المدينة القادم."],
    [1,"Dafür brauchen sie noch einen guten Namen und ein bekanntes Lied.","يحتاجون لذلك إلى اسم جيد وأغنية معروفة."],
    [0,"Wir können sie am Wochenende besuchen und beim Üben zuhören.","يمكننا زيارتها في عطلة نهاية الأسبوع والاستماع إلى تدريبهم."],
    [1,"Gern. Nach diesem Konzert habe ich noch mehr Lust auf Live-Musik.","بكل سرور. بعد هذا الحفل أصبحت أرغب أكثر في الموسيقى الحية."]
  ]
};
